### PR TITLE
fix(create user page): Redirect to home from cancel button in create …

### PR DESCRIPTION
**Pull request by aeng**
…user page

https://zanata.atlassian.net/browse/ZNTA-872

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1178)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### fix\(create user page\): Redirect to home from cancel button in create …
> 
> …user page
> 
> 
> 
> https://zanata.atlassian.net/browse/ZNTA-872
> 
> 
> 
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1178#-:-KIPm44GhJqO-edzsbjm:1417088721)*

**Comment by anipeter** [comment]
* Already had a yahoo user. Removed the user and tried logging in again.
* The new user page opens with a notification "Login failed" (Screenshot attached). 
* The "Cancel" button is still not redirected to home page :( 
login with yahoo

**Comment by anipeter** [comment]
New User Page does not allow to cancel without entering the mandatory details. Issue reported. Waiting for build
new user page for openid

**Comment by anipeter** [comment]
@aeng Cancel button is not working in the current build 5954 :( 
But in previous build 5936 cancel button redirected to home page rightly except that the fields had to be filled.

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
works good

**Pull request merged**
