### PR TITLE
fix(ZNTA-1363): handle stats being disabled

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1363

See also https://zanata.atlassian.net/browse/ZNTA-1364, https://issues.jboss.org/browse/WFLY-3377 and https://issues.jboss.org/browse/ISPN-5421

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1284)

### CODE REVIEW

**Comment by aeng** [comment]
@seanf I will need to sit down with you to understand more on this PR.

**Comment by seanf** [comment]
@aeng sure. But basically, if stats aren't enabled for a given cache (for whatever reason), AdvancedCache.getStats() throws an exception, so I substitute a dummy Stats object. It's possible AdvancedCache.getStats() has changed, but I think it's simply become more difficult to enable stats on caches (see https://issues.jboss.org/browse/WFLY-3377 and https://issues.jboss.org/browse/ISPN-5421)

I'm sure there's a cleaner way of dealing with this, but if we're going to spend more than minimal time on it, I'm thinking we should use generic JMX access instead of depending on Infinispan classes (and the private jboss module for infinispan).

https://docs.jboss.org/infinispan/8.1/apidocs/jmxComponents.html

**Comment by aeng** [comment]
Reviewed 8 of 9 files at r1.
Review status: 8 of 9 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-war/src/main/java/org/zanata/action/CacheAction.java, line 77 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1284#-KR11vSvY8i1phJ-zLPh:-KR11vSvY8i1phJ-zLPi:b-6gpwa) ([raw file](https://github.com/zanata/zanata-server/blob/60f99401469d50fac5f35c48f21cc18274d5fb96/zanata-war/src/main/java/org/zanata/action/CacheAction.java#L77)):*
> ```Java
>             } else {
>                 log.debug("Statistics are not enabled for cache '{}'", cacheName);
>                 return new UnavailableStats(-1);
> ```

Perhaps a comment of what -1 and -2 means?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1284)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1284#-:-KRaZ_apG3P9DLjOMWcW:bnfp4nl)*

**Comment by djansen-redhat** [comment]
:white_check_mark: I think this is ok

**Pull request merged**
