### PR TITLE
fix(js alert): disable js alert tests due to issue with chromedriver

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1278

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1253)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
LGTM I would have preferred something like @Ignore("Chromedriver issue with alert popups") but this is fine.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1253#-:-KNZPM_3US6rb8Fey8FV:124224447)*

**Comment by djansen-redhat** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1253)*

**Comment by seanf** [comment]
@aeng Have you got a link for a chromedriver bug about this?

Why did this just start happening?

**Comment by aeng** [comment]
@seanf Unfortunately this issue is reoccurring almost everytime in new release of chromedriver.
I'm testing with the 2.14 and 2.22 and both having same issue of that. The cause was mainly race condition on intercepting the alert by chromedriver.

**Comment by djansen-redhat** [comment]
:white_check_mark: Jenkins approved

**Pull request merged**
