### PR TITLE
Simplify test with CDI-Unit ProducerConfig

### PR DESCRIPTION
**Pull request by seanf**
Requires: 
- [x] https://github.com/BrynCooke/cdi-unit/pull/92
- [x] [3.1.4 release for cdi-unit](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.jglue.cdi-unit%22%20a%3A%22cdi-unit%22).
- [x] cdi-unit dependency 3.1.4-SNAPSHOT updated to 3.1.4

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1233)

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@carlosmunoz Another one to review, please.

**Comment by carlosmunoz** [comment]
@seanf Reviewing using gitcolony. Let me know if you are getting notifications on review comments.

**Comment by seanf** [comment]
@carlosmunoz Yes, I'm getting notifications from gitcolony, thanks.

I'm going to rebase on master so I can fix the indentation.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Seems to be working as expected

**Pull request merged**
