### PR TITLE
Disable tm import button if no file selected

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1004620

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/6f5fa763226ed58dc1b68106820003997fc4ed9b

**Comment by seanf** [comment]
The merge commit 6f5fa76  has broken the functional test `org.zanata.feature.administration.EditTranslationMemoryTest.rejectEmptyTranslation`.  The pull request build failed the same test.

**Pull request closed without merging**
