### PR TITLE
fix(npm): update dom-event package in frontend

### PR DESCRIPTION
**Pull request by aeng**

### CODE REVIEW

**Comment by seanf** [comment]
:+1: Looks fine, but do we need to add any more packages? 

eg: `concat left-pad map one property right-pad strip subscribe`

which were all reported by this script: https://gist.github.com/cwonrails/962c6503a12821cd161f

**Comment by aeng** [comment]
`left-pad` is fixed. Someone tookover the repo. I managed to build locally with this fix.

**Comment by seanf** [comment]
@aeng Looks like the build succeeded.

**Comment by definite** [comment]
:+1:

**Pull request merged**
