### PR TITLE
Remove jsessionid and upgrade Undertow for WildFly 8.2

### PR DESCRIPTION
**Pull request by seanf**
Based on https://github.com/zanata/zanata-server/pull/784 but using WildFly 8.2 combined with Undertow modules from WildFly 9 (because proper WildFly 9 still has some problems).

### CODE REVIEW

**Comment by seanf** [comment]
The full functional tests actually passed with this Frankenstein combination.

**Comment by carlosmunoz** [comment]
So...
1. What is the problem with Wildfly 9?
2. Does this mean that we are targeting Wildfly 8 with a modified Undertow module?

**Comment by seanf** [comment]
On 2015-04-28 15:36, Carlos Munoz wrote:
> So...
> 1. What is the problem with Wildfly 9?

Specifically, the problem where clicking "login" tries to take you to
the login form, but with an appended jsessionid parameter, which leads
to a 404.


> 2. Does this mean that we are targeting Wildfly 8 with a modified
> Undertow module?

Yes, this PR changes the default WildFly to be 8.2.0.Final, with some
extra Undertow 1.2 modules which were taken from WildFly 9.


-- 
Sean Flanigan

Principal Software Engineer
Localisation Tools Engineering
Red Hat

**Comment by seanf** [comment]
It actually seems to work, but given the unknown risks in upgrading Undertow this way, we're going to skip WildFly 8.2.0.Final and go with WildFly 9 beta (at least for testing) instead: https://github.com/zanata/zanata-server/pull/784

I also cherry picked b168cf687bc63aab00522b7d9398053bdaab9b76 as https://github.com/zanata/zanata-server/pull/789.

**Pull request closed without merging**
