### PR TITLE
Remove excess waits for test page

### PR DESCRIPTION
**Pull request by djansen-redhat**

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
Looks good.  I've kicked off all functional tests.

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Pull request merged**
