### PR TITLE
use docker user defined network instead of linking

### PR DESCRIPTION
**Pull request by huangp**
Enable docker to use user defined network. So all the containers we run from the scripts will join the same network and see each other.
## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1318)

### CODE REVIEW

**Comment by seanf** [comment]
*[docker/Dockerfile, line 3 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1318#-KTwYSxIvgx1hWV-aURh:-KTwYSxIvgx1hWV-aURi:bt31c2b) ([raw file](https://github.com/zanata/zanata-server/blob/880a0e27a6767232b5a76261548218d888c8086e/docker/Dockerfile#L3)):*
> ```Dockerfile
> FROM jboss/wildfly:10.1.0.Final
> 
> ENV DB_HOSTNAME=zanatadb DB_USERNAME=zanata DB_PASSWORD=zanatapw DB_NAME=zanata
> ```

We should pass these in from `rundev.sh` instead of hard-coding them.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1318)*

**Comment by seanf** [comment]
Review status: 0 of 4 files reviewed at latest revision, 2 unresolved discussions.

---

*[docker/rundb.sh, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1318#-KTwYhjlUOsRh6FyKnZ0:-KTwYhjlUOsRh6FyKnZ1:b-x0bjsb) ([raw file](https://github.com/zanata/zanata-server/blob/880a0e27a6767232b5a76261548218d888c8086e/docker/rundb.sh#L24)):*
> ```Shell
>       DOCKER_NETWORK="$OPTARG"
>       ;;
>     H)
> ```

Lower-case `-h` is the conventional help option.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1318)*

**Comment by huangp** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[docker/Dockerfile, line 3 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1318#-KTwYSxIvgx1hWV-aURh:-KTwclS_4t44qMRfUrdb:b-896fix) ([raw file](https://github.com/zanata/zanata-server/blob/880a0e27a6767232b5a76261548218d888c8086e/docker/Dockerfile#L3)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> We should pass these in from `rundev.sh` instead of hard-coding them.
</details>
Done.

---

*[docker/rundb.sh, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1318#-KTwYhjlUOsRh6FyKnZ0:-KTwcmfmJVLa9ZxQSY4D:bw68w5g) ([raw file](https://github.com/zanata/zanata-server/blob/880a0e27a6767232b5a76261548218d888c8086e/docker/rundb.sh#L24)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Lower-case `-h` is the conventional help option.
</details>
Done. I thought -H and --help were the convention. But I am fine with both.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1318)*

**Comment by djansen-redhat** [comment]
You don't want QA on this one?

**Comment by seanf** [comment]
@djansen-redhat if you use `rundb.sh` and `rundev.sh`, I do think we could use your input.

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1318#-:-KU0JCOtk7sZtBKak67q:bnfp4nl)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1318#-:-KUFKozQAJ0sFH4w8rwR:bnfp4nl)*

**Pull request closed without merging**
