### PR TITLE
fix(change email): redirection to home page after email change

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-871

This will have the same issue as account activation where the message won't display but redirection works.
One of the solution I can think of is instead of using /account/validate_email/
{key} and /account/activate/{key}
to validate, use
http://localhost/zanata?validateEmail= {key}
* http://localhost/zanata?activateAccount={key}
With that, we can ensure message gets displayed properly.

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by aeng** [comment]
@zanata-jenkins please retest this

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, waiting for green light

**Comment by djansen-redhat** [comment]
Fixed test (hopefully)

**Pull request merged**
