### PR TITLE
Fix generate api issue

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1193597

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by carlosmunoz** [comment]
@aeng could we add this to the release branch?

**Comment by carlosmunoz** [comment]
Also, why was this a problem only for French?

**Comment by aeng** [comment]
It's the "single quote" in french, causing exception in javascript. And skip the process of generating API key.

**Comment by aeng** [comment]
Moved to https://github.com/zanata/zanata-server/pull/698 targeting release branch.

**Pull request closed without merging**
