### PR TITLE
BACKPORT perf(liquibase): merge addColumn changes

### PR DESCRIPTION
**Pull request by seanf**
(cherry picked from commit 6ac8d8a3b9172166d4c96416c6bc79f6be0d1f23)

See also https://github.com/zanata/zanata-server/pull/952

### CODE REVIEW

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
The enforcer failure should be fixed by https://github.com/zanata/zanata-server/commit/ce7cadfc1ae3f1075068977b03dfb8cff686fb72 as part of https://github.com/zanata/zanata-server/pull/954

**Comment by seanf** [comment]
Rebased on top of `release` and also cherry-picked the enforcer fix from https://github.com/zanata/zanata-server/commit/ce7cadfc1ae3f1075068977b03dfb8cff686fb72

**Comment by definite** [comment]
https://zanata.atlassian.net/browse/ZNTA-665

**Pull request merged**
