### PR TITLE
Re-enable commonmark preview

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/877" target="_blank">ReviewNinja

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by carlosmunoz** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested (build was old, rebased and built manually)

**Pull request merged**
