### PR TITLE
ZNTA-1328 Use RestResource for JAX-RS Application classes set

### PR DESCRIPTION
**Pull request by seanf**
Depends on https://github.com/zanata/zanata-api/pull/45 (won't compile without it).

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1118)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
👍  (has conflicts though)

**Comment by seanf** [comment]
@carlosmunoz Rebased to fix the conflict.

**Comment by seanf** [comment]
Yep, still won't compile without https://github.com/zanata/zanata-api/pull/45.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by definite** [comment]
@zanata-jenkins test this please

**Comment by definite** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
I need to find time to get this working again.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by carlosmunoz** [comment]
:lgtm:
-(Awaiting review) +Reviewed 

---

Reviewed 9 of 12 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1118#-:-KRX7BjovOtrOZhuLSvq:b-j0a94j)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: I believe this is good to go

**Pull request merged**
