### PR TITLE
fix(request join group): limit message field in request join group dialog

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-846

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1179)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1179)*

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### fix\(request join group\): limit message field in request join group dialog
> 
> https://zanata.atlassian.net/browse/ZNTA-846
> 
> 
> 
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1179#-:-KIPkg8It5UKhcN0cK5l:1417088721)*

**Comment by anipeter** [comment]
Working good. 
Observations:
* In a scenario where one tries sending message with more than 300 characters get the error message "value must be shorter than or equal to 300 characters" in RED, and after adjusting the character count to 300 and message is being sent, this error message still appears. Screenshot attached.
pr-1179 error message displayed while sending request

**Comment by aeng** [comment]
@anipeter The warning message is not `live` update. I think as long as after you shorten the message, you're able to send, then it should be fine. (Also, all field is reset after successful send)

**Comment by anipeter** [comment]
:+1:

**Comment by aeng** [comment]
Build passed http://zanata-build.lab.eng.bne.redhat.com/job/zanata-server-github-pull-requests/5949/.

**Pull request merged**
