### PR TITLE
ZNTA-1042 Control CORS with system property

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1042

Rebase of https://github.com/zanata/zanata-server/pull/1149

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1156)

### CODE REVIEW

**Comment by seanf** [comment]
@carlosmunoz This PR is the same as https://github.com/zanata/zanata-server/pull/1149, but could you please review the docs change? An entry will be added to the release notes (from JIRA) as part of the release process.

**Comment by carlosmunoz** [comment]
Docs look good, though maybe we should put the CORS content in its own sub-section.

Also, does this mean we no longer need to add an entry in the release notes for bugs which are fixed? (because they will get added as part of the release process?)

**Comment by seanf** [comment]
> Also, does this mean we no longer need to add an entry in the release notes for bugs which are fixed? (because they will get added as part of the release process?)

That's my understanding. Right @definite ?

**Comment by seanf** [comment]
> Docs look good, though maybe we should put the CORS content in its own sub-section.

What did you have in mind? A different file, a different position in this file, or simply one `#` instead of two for the heading?

**Comment by seanf** [comment]
Note: a version of my CORS changes (in https://github.com/zanata/zanata-server/pull/1156) was copied into https://github.com/zanata/zanata-server/commit/3b67e4dd5156dfb77804ef5898e30d1a58197af2 (which is part of https://github.com/zanata/zanata-server/pull/1125) so we will have to watch the conflict resolution when they are merged together.

**Comment by djansen-redhat** [comment]
This looks fine to me, with one minor observation.  The docs state that, when CORS is enabled, the header value "Access-Control-Allow-Methods: PUT,POST,DELETE,GET,OPTIONS" will be in the response header, but it was always returned in the response regardless of setting.  The other options were omitted correctly.
@seanf @aeng I do not know if this is significant, in any way, but it can (likely) be fixed easily by moving the .add line into the conditional.  Comments?

**Comment by aeng** [comment]
Sounds to me its just depends on how strict we want it to be. With current implementation (always return Access-Control-Allow-Methods: PUT,POST,DELETE,GET,OPTIONS), it just a way of saying, 
`if user can start their browser with disabling CORS check, then they can perform those action in our rest endpoint`

If we only returns 'Access-Control-Allow-Methods: PUT,POST,DELETE,GET,OPTIONS' when its a whitelisted requester, then we are preventing any actions to be perform even when user starts their browser with disabling CORS check.

**Comment by seanf** [comment]
> Sounds to me its just depends on how strict we want it to be. With current implementation (always return Access-Control-Allow-Methods: PUT,POST,DELETE,GET,OPTIONS), it just a way of saying, 
"if user can start their browser with disabling CORS check, then they can perform those action in our rest endpoint"

Surely if the browser disable CORS checks, this header becomes completely irrelevant.

> If we only returns 'Access-Control-Allow-Methods: PUT,POST,DELETE,GET,OPTIONS' when its a whitelisted requester, then we are preventing any actions to be perform even when user starts their browser with disabling CORS check.

If CORS checks are disabled, they're disabled, aren't they?

**Comment by aeng** [comment]
> If CORS checks are disabled, they're disabled, aren't they?
Not sure, need QA to test this scenario if it matters.

**Comment by seanf** [comment]
> This looks fine to me, with one minor observation. The docs state that, when CORS is enabled, the header value "Access-Control-Allow-Methods: PUT,POST,DELETE,GET,OPTIONS" will be in the response header, but it was always returned in the response regardless of setting. The other options were omitted correctly.

> @seanf @aeng I do not know if this is significant, in any way, but it can (likely) be fixed easily by moving the .add line into the conditional. Comments?

I don't know if it's significant either, but docs and code really ought to match, and we might as well change the code to do what the docs say. It seems like the safer option anyway, since if you don't specify the whitelist system property, you won't get any CORS headers.

I'll make the change.

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1156)*

**Comment by seanf** [comment]
@djansen-redhat Could you retest please?

**Comment by djansen-redhat** [comment]
:white_check_mark: Works well, as far as I can determine

**Pull request merged**
