### PR TITLE
fix(validation):remove line count check in leading newline validation

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-726

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
:+1:

**Comment by aeng** [comment]
Merged into release. https://github.com/zanata/zanata-server/commit/eb6e239001040117ac8bf774fd4eda5839871deb

**Pull request closed without merging**
