### PR TITLE
feat(banner): change startup banner to show logo

### PR DESCRIPTION
**Pull request by carlosmunoz**

### CODE REVIEW

**Comment by huangp** [comment]
:+1: ok...

**Comment by carlosmunoz** [comment]
retest this please

**Comment by carlosmunoz** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:see_no_evil: *backs away slowly*

**Comment by carlosmunoz** [comment]
Merged in commit 9076adb423c0b8a5f06b5ef94dd0f2f8ea3e2281

**Comment by seanf** [comment]
@carlosmunoz It's kind of annoying how big the banner is.  It pushes useful version information off the top of the console.

**Comment by carlosmunoz** [comment]
@seanf If only there were a way to scroll up the logs easily, we could call it a "scroll wheel"...  :wink:

**Pull request closed without merging**
