### PR TITLE
fix(doc status): Fix doc status api endpoint (#1120)

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1120

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1176)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
*[pom.xml, line 90 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1176#-KIB_3SWLp9d0dzAvOTw:-KIB_3SWLp9d0dzAvOTx:-982593358) ([raw file](https://github.com/zanata/zanata-server/blob/9f31e2dcddfd4859556edf75716748980f415e08/pom.xml#L90)):*
> ```XML
> 
>     <zanata.assets.version>8.2</zanata.assets.version>
>     <zanata.api.version>3.9.1-SNAPSHOT</zanata.api.version>
> ```

A release version pointing to a snapshot version? Shouldn't we do an api release of 3.9.1 and point to that?
Also, what has changed between 9.0 and 9.1, that could invalidated RC1 testing?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1176)*

**Comment by aeng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 90 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1176#-KIB_3SWLp9d0dzAvOTw:-KIBapcN4ccmZebHZTZK:-939217356) ([raw file](https://github.com/zanata/zanata-server/blob/9f31e2dcddfd4859556edf75716748980f415e08/pom.xml#L90)):*
<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary>
> A release version pointing to a snapshot version? Shouldn't we do an api release of 3.9.1 and point to that?
> Also, what has changed between 9.0 and 9.1, that could invalidated RC1 testing?
</details>
The issue was introduced earlier in 3.9.0-SNAPSHOT. The error was only with 1 end point which is my fault. So we will need to release 3.9.1 to have this work. It wont invalidate RC1 testing as Server release is using api 3.9.0 and this fix is based from  api 3.9.0

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1176)*

**Comment by djansen-redhat** [comment]
*[pom.xml, line 90 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1176#-KIB_3SWLp9d0dzAvOTw:-KIBc34bwYHb1uaGlJfr:-272271846) ([raw file](https://github.com/zanata/zanata-server/blob/9f31e2dcddfd4859556edf75716748980f415e08/pom.xml#L90)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> The issue was introduced earlier in 3.9.0-SNAPSHOT. The error was only with 1 end point which is my fault. So we will need to release 3.9.1 to have this work. It wont invalidate RC1 testing as Server release is using api 3.9.0 and this fix is based from  api 3.9.0
</details>
OK sounds good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1176)*

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### fix\(doc status\): Fix doc status api endpoint \(\#1120\)
> 
> https://zanata.atlassian.net/browse/ZNTA-1120
> 
> 
> 
> 
> 
> 
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1176#-:-KIQ98XpUa58G6givNur:1417088721)*

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Pull request merged**
