### PR TITLE
Update to zanata assets 6.1.1

### PR DESCRIPTION
**Pull request by seanf**
https://bugzilla.redhat.com/show_bug.cgi?id=1216304

This should help with the `form__loader` problem seen when testing http://assets-zanata.rhcloud.com/6.1.1/styleguide/

 - [x] Re-enable ignored tests for RHBZ1216304

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
Some tests are timing out due to implicit waits.  We'll see if #776 helps.

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
We should retest after https://github.com/zanata/zanata-assets/pull/3 is merged and deployed.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
Rebase on #792 - that will prevent those pesky timeouts again

**Comment by seanf** [comment]
Running again with full tests...

**Comment by djansen-redhat** [comment]
Does this need another full FT run?

**Comment by seanf** [comment]
Already running, github just got its wires tangled.

**Comment by seanf** [comment]
Something about this branch (or assets 6.1.1) is causing tests to take much, much longer than usual.  Too long.

**Comment by seanf** [comment]
@djansen-redhat Could I get you to try debugging the slow testing issue?  I think it's happening pretty consistently

**Comment by djansen-redhat** [comment]
@seanf - fix is in. Thanks for the help debugging that one.

**Comment by djansen-redhat** [comment]
:white_check_mark: Assuming a full FT run passes in good time, we can set this good-to-go.

**Pull request merged**
