### PR TITLE
Improve review statistics - approved vs translated

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1209670

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
- [ ] Release note

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. Add release note and I'll verify.

**Comment by djansen-redhat** [comment]
Waiting for green light.

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/53417cf3fa5374f96ddf1d9b0abe14c56ff59ec0

**Pull request closed without merging**
