### PR TITLE
Fix save editor option

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1222710

### CODE REVIEW

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
- [ ] Release note

**Comment by djansen-redhat** [comment]
@aeng does this need a "Saved user options" notification message as well?

**Comment by aeng** [comment]
@djansen-redhat I dont see reason not to have it.

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested.

**Comment by aeng** [comment]
Merged in integration/master. https://github.com/zanata/zanata-server/commit/cac387508126917ba1af248332369679fc462d45

**Pull request closed without merging**
