### PR TITLE
Implement plural support for zanata-spa

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1172437

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed in Zanata-SPA https://github.com/zanata/zanata-spa/pull/89

**Comment by djansen-redhat** [comment]
:x: The Esc keyboard shortcut doesn't seem to work
:x: Saving seems to be flaky, sometimes the spinner doesn't stop
:question: Is it expected that, when translating the first target in a set of plurals, pressing copy on the *second* source copies it to the first target?
:x: Pressing copy seems to add a newline to the target after the text

**Comment by aeng** [comment]
@djansen-redhat :question: Is it expected that, when translating the first target in a set of plurals, pressing copy on the second source copies it to the first target? 

Yes. Copy source will copy to the focused text area. But if you're using key shortcut for copy source, it will try to copy the corresponding source[focused target index] to focused target. If there's more target than source, it will copy the last source to the focused target.

**Comment by aeng** [comment]
@djansen-redhat :question: Pressing copy seems to add a newline to the target after the text

Confirmed there's new line character from source. Zanata-spa doesn't show it, check with our editor.

**Comment by aeng** [comment]
Transfered to new PR for release branch: https://github.com/zanata/zanata-server/pull/674

**Pull request closed without merging**
