### PR TITLE
chore: bump recommended EAP/WildFly versions

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by djansen-redhat** [comment]
The pull request build says "-Dwildfly.version=9.0.0.Final" - is this expected?

**Comment by seanf** [comment]
@djansen-redhat 
No, I forgot to remove that parameter in Jenkins when we backported #864.  Thanks.

@zanata-jenkins test this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:+1: :white_check_mark: Reviewed and tested

**Pull request merged**
