### PR TITLE
Upgrade RichFaces to 4.5.2.Final

### PR DESCRIPTION
**Pull request by seanf**
https://developer.jboss.org/people/michpetrov/blog/2014/12/02/richfaces-451final-release-announcement
https://developer.jboss.org/people/michpetrov/blog/2015/01/15/richfaces-452final-release-announcement

### CODE REVIEW

**Comment by seanf** [comment]
@carlosmunoz Could you please remind me how we build zanata-server.zip?  Can we upgrade its Mojarra to 2.1.28?  Or should this PR wait until we switch our tests over to WildFly instead of zanata-server.zip?

**Comment by carlosmunoz** [comment]
zanata-server.zip is now deprecated. It's now all about wildfly and expanding the 'overlay' zip on top of it, so I say we should concentrate on that.

**Comment by seanf** [comment]
On hold until we switch any build jobs which use zanata-server.zip to use wildfly instead.

**Comment by seanf** [comment]
This will need to be bumped to 4.5.2: https://developer.jboss.org/people/michpetrov/blog/2015/01/15/richfaces-452final-release-announcement

**Comment by seanf** [comment]
Two tests failed:

 - `MultiFileUploadTest.removeFileFromUploadList` is already known to be intermittent.
 - `TranslateTextTest.translateBasicTextFile` looks like a real bug.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
The failing tests were not in fact caused by the RichFaces upgrade, but have been taken care of by https://github.com/zanata/zanata-server/pull/702 and others.

**Comment by carlosmunoz** [comment]
:+1: Not much to review. Build is failing though.

**Comment by seanf** [comment]
Only one test failed, intermittently, on wildfly 8.2.  I don't think that was caused by this change.

**Comment by carlosmunoz** [comment]
ok

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. This looks like another one where errors, if any, will be present themselves "in passing" and I'd rather not spend an entire release test cycle for it.

**Comment by seanf** [comment]
Merge postponed due to https://github.com/zanata/zanata-server/pull/577 breakage.

**Comment by seanf** [comment]
Obsoleted by https://github.com/zanata/zanata-server/pull/728

**Pull request closed without merging**
