### PR TITLE
fix(glossary info): include lastModifiedBy info in entry

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1167

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1200)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 2 of 3 files at r1.
Review status: 2 of 3 files reviewed at latest revision, 2 unresolved discussions.

---

*[frontend/src/main/web/src/containers/Glossary/EntryModal.js, line 27 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1200#-KJrxGLOcNMUSm1lcQrF:-KJrxGLPZc9pu1HNv5uh:-650389641) ([raw file](https://github.com/zanata/zanata-server/blob/a92a1514ac33aa70a064b699bdbc78193aad0dc0/frontend/src/main/web/src/containers/Glossary/EntryModal.js#L27)):*
> ```JavaScript
>         parts.push(term.lastModifiedBy);
>       }
>       if (!isEmpty(toString(term.lastModifiedDate))) {
> ```

Can't you just test whether term.lastModifiedDate is null or undefined? Convert it to string then test with isEmpty seems more expensive

---

*[frontend/src/main/web/src/utils/DateHelper.js, line 71 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1200#-KJrxqmNDJlXAExAfasK:-KJrxqmOUxkO5OljOFpI:-740901572) ([raw file](https://github.com/zanata/zanata-server/blob/a92a1514ac33aa70a064b699bdbc78193aad0dc0/frontend/src/main/web/src/utils/DateHelper.js#L71)):*
> ```JavaScript
> 
>   getDate: function (milliseconds) {
>     if (!isEmpty(toString(milliseconds))) {
> ```

I think you can just use moment(milliseconds) and then test the resulting moment object with isValid. The moment object is much easier to deal with then Date.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1200)*

**Comment by aeng** [comment]
Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[frontend/src/main/web/src/containers/Glossary/EntryModal.js, line 27 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1200#-KJrxGLOcNMUSm1lcQrF:-KJsAZBEnAuQ1XffdqOU:-160784612) ([raw file](https://github.com/zanata/zanata-server/blob/a92a1514ac33aa70a064b699bdbc78193aad0dc0/frontend/src/main/web/src/containers/Glossary/EntryModal.js#L27)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Can't you just test whether term.lastModifiedDate is null or undefined? Convert it to string then test with isEmpty seems more expensive
</details>
good point. I think checking for undefined should be sufficient.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1200)*

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### fix\(glossary info\): include lastModifiedBy info in entry
> 
> https://zanata.atlassian.net/browse/ZNTA-1167
> 
> 
> 
</details>


---

Review status: 1 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1200#-:-KJsI8mDJbdfxPxo4Oqh:1417088721)*

**Comment by djansen-redhat** [comment]
- [ ] Translation term has invalid date
invaliddate

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1200#-:-KKLYjYhFOlGvAD-jvuU:1417088721)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Pull request merged**
