### PR TITLE
Update assets version to 6.1 for whitespace changes

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=875965

### CODE REVIEW

**Comment by seanf** [comment]
It looks like this is going to pull in seven months' worth of zanata-assets changes.  Is that what we want to do in a point release?

**Comment by aeng** [comment]
Some of the UI already depending on assets 7. And there's no much changes in CSS styling. We will test the UI.

**Comment by seanf** [comment]
> Some of the UI already depending on assets 7. 

In `release`?  Doesn't seem that way.

> And there's no much changes in CSS styling. 

Okay, but it seems like there could be changes in JavaScript too.

> We will test the UI.

All of it?  If we made a more conservative zanata-assets release (say `6.1`), we might only need to re-test the affected UI, ie the editor.

**Comment by aeng** [comment]
@seanf I will check with @lukebrooker if he can based off the changes in version 6 then to avoid unnecessary testing in point release.

**Comment by aeng** [comment]
We will create assets 6.1 for this change. This will also ensure the browser cached css gets updated when its deployed.

**Comment by seanf** [comment]
zanata-assets seems to be lacking in git tags.  If it had tags, it would be easy to review what has changed between 6 and 6.1.

**Comment by seanf** [comment]
> zanata-assets seems to be lacking in git tags. If it had tags, it would be easy to review what has changed between 6 and 6.1.

Sorry, I forgot that zanata-assets is laid out with directories for versions.  But where's the 6.1 directory?

**Comment by seanf** [comment]
@aeng Is it just that this pull request is referring to the new assets version before it actually exists?

**Comment by aeng** [comment]
@seanf be patient my friend. Its in https://github.com/zanata/zanata-assets/tree/master/php/6.1

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested.
It's really difficult to see what effect changing that character has on Zanata as a whole.

**Comment by seanf** [comment]
@aeng @lukebrooker  The diff between `zanata-assets` 6 and 6.1 (`diff -ur 6 6.1`) still seems far too big for a point release, but at least there's no change to the .js files.

**Comment by lukebrooker** [comment]
@seanf Most of the changes are just because it's copying existing files to a new folder. You only really need to look at src/assets/sass/application.scss for the real changes.

**Comment by lukebrooker** [comment]
@seanf `git diff bb299a76557a173378ac6184d0fedfd5f63e0cfb 34858b070ce6ba2d5daecc91c60fde57701de60f src/assets/sass/application.scss`

**Pull request merged**
