### PR TITLE
Add more checks for bad/stale TM results

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by carlosmunoz** [comment]
I only have a question about the result of using the `PassThroughTokenizer` when the analyzed field is not a lower case one. What's the intended effect there?

**Comment by seanf** [comment]
Well, the /intention/ is to parse the query (or index the field) without
change - don't split into tokens; don't change the case.

Do you think the intention might be wrong, or the implementation?

On 13 October 2015 at 09:30, Carlos Munoz <notifications@github.com> wrote:

> I only have a question about the result of using the PassThroughTokenizer
> when the analyzed field is not a lower case one. What's the intended effect
> there?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-server/pull/1005#issuecomment-147548504>
> .
>



-- 
Sean Flanigan

Principal Software Engineer
Globalisation Tools Engineering
Red Hat

**Comment by carlosmunoz** [comment]
So, in the case of a non-lower case field we don't apply the `StandardFilter`?

**Comment by djansen-redhat** [comment]
The failure at build 4688 (setRegisterURLTest) can be ignored

**Comment by djansen-redhat** [comment]
:white_check_mark: Reasonably sure this doesn't break anything

**Pull request merged**
