### PR TITLE
Use the same dependency versions in frontend and zanata-editor ZNTA1220

### PR DESCRIPTION
**Pull request by davidmason**
## Requirements from JIRA issue:
- all dependencies that are common to both modules should specify the same version in package.json of both modules
- all dependencies must specify an exact version (no prefix with ^ or ~)
- version updates can be in either module, or both
- frontend and zanata-editor must both build and run properly after this change
## Actual changes made (and why)
- Updated dependency versions in both modules.
- Minimal fixes on tests in frontend, and configured tests to actually run. Tests were not configured anywhere to run and they were broken (so probably not run for a long time). Several tests were disabled to get a passing test build, with FIXME comments added. Tests are now run manually with `npm test` but we should also make sure the maven build will run this.
- Disabled several linting rules in zanata-editor. The updated linting dependencies add several new constraints, but I will make these fixes and re-enable the rules after the initial review so that review is more straightforward.

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1236)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 12 of 12 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1236#-:-KMbJwFC7WjPl8CTGhju:1417088721)*

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 52 of 52 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1236#-:-KN0ZHLskuh3oGBdgKqy:1417088721)*

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 4 of 8 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1236#-:-KN4j6TA6pTtSc6OSfAz:1417088721)*

**Comment by djansen-redhat** [comment]
:white_check_mark: looks good

**Pull request merged**
