### PR TITLE
fix(add language):add new language using selected text

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-657

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:+1:

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
:+1:

**Comment by aeng** [comment]
Merged into release. https://github.com/zanata/zanata-server/commit/071e2444b5533c027d7fb39f083102d94a70dac7

**Pull request closed without merging**
