### PR TITLE
Upgrade to liquibase 3.4.2

### PR DESCRIPTION
**Pull request by seanf**
http://www.liquibase.org/2015/11/liquibase-3-4-2-released.html

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:+1:

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested.
Jenkins appears to have died while running the functional tests -
[INFO] [talledLocalContainer] java.io.IOException: No space left on device

**Comment by seanf** [comment]
@zanata-jenkins test this please.

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. It's fine, assuming Jenkins green light.

**Pull request merged**
