### PR TITLE
fix(ZNTA-537): bring back session expired page

### PR DESCRIPTION
**Pull request by carlosmunoz**
This page had been lost as part of the CDI migration.
Bringing it back as well as removing unnecessary JSF artifacts as
DeltaSpike handlers cover both ajax and non-ajax scenarios.

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by carlosmunoz** [comment]
@definite Can you please QA this?

**Comment by djansen-redhat** [comment]
Waiting for @seanf CDI stuff to be merged first

**Comment by seanf** [comment]
@carlosmunoz We should look at merging this into https://github.com/zanata/zanata-server/pull/1072

**Comment by seanf** [comment]
@carlosmunoz I've had a go at merging your changes with mine (which are now on `master`). See what you think.

**Comment by carlosmunoz** [comment]
@seanf @djansen-redhat I reviewed the code changes and I tested the functionality still works. Moving to QA.

**Comment by djansen-redhat** [comment]
:white_check_mark: Reasonably sure this works as expected

**Pull request merged**
