### PR TITLE
feat(shortcut): add shortcut for approve and reject translation

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-746

### CODE REVIEW

**Comment by aeng** [comment]
@djansen-redhat Need to sit down with you on the racing condition you mentioned.

**Comment by carlosmunoz** [comment]
Sending to @huangp for review as he might have better insights on the GWT side of things.

**Comment by huangp** [comment]
:+1:

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
Works good.

**Comment by aeng** [comment]
Thanks @anipeter

**Pull request merged**
