### PR TITLE
fix: add loader to user profile page

### PR DESCRIPTION
**Pull request by carlosmunoz**
Loader is added when the page is loading data so as to not show a blank page.

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@huangp I've assigned this for a review since it's your code originally

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
Doesn't stop ticking when user changes the period (This Month, Last Month, etc...)

**Comment by carlosmunoz** [comment]
@djansen-redhat Made a fix to solve the problem you detected

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by carlosmunoz** [comment]
Squash merged in def7eab34e8d1bf146fab9163e486115591abc57

**Pull request closed without merging**
