### PR TITLE
fix(ZNTA-778): add utf8 for glossary po file upload

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-778

### CODE REVIEW

**Comment by seanf** [comment]
@aeng Perhaps this should target the `release` branch.

**Comment by aeng** [comment]
@seanf we are releasing 3.8.0 from master soon.

**Comment by aeng** [comment]
anyhow, I've closed the PR.

**Comment by seanf** [comment]
Oh right, I forgot we hadn't branched yet.

On 18 November 2015 at 13:01, Alex Eng <notifications@github.com> wrote:

> @seanf <https://github.com/seanf> we are releasing 3.8.0 from master soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-server/pull/1041#issuecomment-157587842>
> .
>



-- 
Sean Flanigan

Principal Software Engineer
Globalisation Tools Engineering
Red Hat

**Comment by seanf** [comment]
See #1043

**Pull request closed without merging**
