### PR TITLE
Update search

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1233524

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/882" target="_blank">ReviewNinja

**Comment by huangp** [comment]
:+1:

**Comment by huangp** [comment]
Need to fix the build though

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by aeng** [comment]
@zanata-jenkins test this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
- [ ] Entering a term such as "cam" and selecting Search Zanata for... shows a count of three, but no projects listed

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested.
The build system is borked though.

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/158ad02d0883b0dc522974afd02fe1100b9cc5b2

**Pull request closed without merging**
