### PR TITLE
fix adding arbitrary language in zanata

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1180988

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by definite** [comment]
@zanata-jenkins rebuild this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
Failed tests:
-[ ] Input "sr@latin" should be shown as sr@latin
-[ ] Input "sr-RS@latin" should be shown as sr-RS@latin

**Comment by definite** [comment]
:+1:

**Pull request merged**
