### PR TITLE
Update to wildfly 9.0.0.CR2

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/873)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/873" target="_blank">ReviewNinja

**Comment by djansen-redhat** [comment]
@seanf Do we want to update now, or after release? What benefits does CR2 provide?

**Comment by seanf** [comment]
@djansen-redhat  Anyone using Zanata on WildFly really needs to run the latest version to get security updates, so I like to test on the newest versions.  This is the release announcement (currently 404?!): http://webcache.googleusercontent.com/search?q=cache%3Awildfly.org%2Fnews%2F2015%2F06%2F10%2FWildFly9-CR2-Released%2F&oq=wildfly.org%2Fnews%2F2015%2F06%2F10%2FWildFly9-CR2-Released%2F&aqs=chrome..69i64j69i57.423j0j4&sourceid=chrome&es_sm=93&ie=UTF-8

**Comment by seanf** [comment]
@djansen-redhat the wildfly build was successful

**Comment by djansen-redhat** [comment]
@seanf I have reviewed this and accepted CI's verification of it.  I am fine with the change, but I'll leave it to @definite to manage the release - but it must be put in *before* release testing begins.

**Comment by seanf** [comment]
@definite are you happy for this to go in for release testing?  If so, please merge the PR.

**Pull request merged**
