### PR TITLE
Fix zanata.file.directory documentation

### PR DESCRIPTION
**Pull request by djansen-redhat**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1181)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:lgtm:

<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary>
> #### Fix zanata\.file\.directory documentation
</details>


---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1181#-:-KIR9scfMhP21bjAuLhD:1417088721)*

**Comment by carlosmunoz** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1181)*

**Comment by anipeter** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
Good to go with a note:
Tried making errors in the system property, but it did not show any error and was successfully able to access the Projects & documents in it.

**Pull request merged**
