### PR TITLE
Fix tooltip label for create new group button

### PR DESCRIPTION
**Pull request by djansen-redhat**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1203)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
The Create New Group button in user dashboard groups list was showing the property id.

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1203)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@anipeter please test (check the tooltip on the New Group button)

**Comment by anipeter** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
looks good :+1:

**Pull request merged**
