### PR TITLE
ZNTA-991 hibernate validator class loading issue in wildfly

### PR DESCRIPTION
**Pull request by huangp**
https://zanata.atlassian.net/browse/ZNTA-991

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1168)

### CODE REVIEW

**Comment by seanf** [comment]
:+1:

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@huangp this change breaks zanata-test-war now, due to a conflict with @definite's change in b7e35713bdc2791ecc9216a927401e7349869208

**Comment by djansen-redhat** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1168)*

**Comment by djansen-redhat** [comment]
:white_check_mark: verified on EAP 6.4.6 and WF 10 final

**Pull request merged**
