### PR TITLE
fix(ZNTA-638): upgrade ehcache

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-638

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by carlosmunoz** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:see_no_evil: Tested by Leeroy Jenkiiiiins

**Pull request merged**
