### PR TITLE
fix(project settings): fix exception when set project to 'invite only'

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1125

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1180)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-translation.xhtml, line 58 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1180#-KIQ9TugbwlySpHR2QJy:-KIQ9Tuh23T-sJlLftCe:440130358) ([raw file](https://github.com/zanata/zanata-server/blob/6b3df3c8585a6539411c4548fb42303d4f5183b6/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-translation.xhtml#L58)):*
> ```HTML
> </h2>
> 
> <h:form id="settings-translation-form" styleClass="l--push-bottom-0">
> ```

Are you sure `a4j:jsFunction` will work outside of the form? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1180)*

**Comment by aeng** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-translation.xhtml, line 58 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1180#-KIQ9TugbwlySpHR2QJy:-KIQA-6p02YwpS0icO01:1078578920) ([raw file](https://github.com/zanata/zanata-server/blob/6b3df3c8585a6539411c4548fb42303d4f5183b6/zanata-war/src/main/webapp/WEB-INF/layout/project/settings-tab-translation.xhtml#L58)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> Are you sure `a4j:jsFunction` will work outside of the form? 
</details>
I moved it inside..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1180)*

**Comment by carlosmunoz** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### fix\(project settings\): fix exception when set project to &#39;invite only&#39;
> 
> https://zanata.atlassian.net/browse/ZNTA-1125
> 
> 
> 
</details>


---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1180#-:-KIQAU2Vt1o5vm_CxUzD:1417088721)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested

**Pull request merged**
