### PR TITLE
adjust markup and function calls for scrollable panels

### PR DESCRIPTION
**Pull request by lukebrooker**
The other part of the fix is in zanata-assets:
https://github.com/zanata/zanata-assets/commit/7079cddc066216c3e28ea977322e566bf98c5ddc

### CODE REVIEW

**Comment by lukebrooker** [comment]
@carlosmunoz

**Comment by carlosmunoz** [comment]
Codewise I have no problems with it. It's 100% facelet code which can be tough to review.

**Comment by djansen-redhat** [comment]
@lukebrooker Do I need to do something unusual to test this? e.g. install some version of assets?

**Comment by lukebrooker** [comment]
As long as you get new man deps it should be fine.

**Comment by djansen-redhat** [comment]
:white_check_mark: Looks good

**Pull request merged**
