### PR TITLE
Fix text comparison

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by davidmason** [comment]
:+1:

It took a moment to see the point of this. I can't help but find `if (!text.equals(text))` amusing. This sort of thing is why I like to make some tests that fail on purpose, making use of whatever custom test helpers we have made so we know if they are working. Same sort of thing with linting - make a bad file and ensure that all the expected problems are found.

**Comment by davidmason** [comment]
@seanf not sure if this was ready to review. The change so far looks good to me, but I guess it unmasks a few failing tests that need fixing so there may be a bit more to review.

**Comment by seanf** [comment]
@djansen-redhat Could you look at the broken tests please?

**Comment by djansen-redhat** [comment]
Holy crud that's embarrassing.
EditTranslationMemoryTest fails because the entered filename is changed to c:\fakepath\name
EditorFilterMessagesTest fails because a space is added after the text is entered.

@seanf do you want me to add a commit to ignore these instances of difference?

**Comment by seanf** [comment]
Yes please, Damian.

On 6 October 2015 at 15:11, Damian Jansen <notifications@github.com> wrote:

> Holy crud that's embarrassing.
> EditTranslationMemoryTest fails because the entered filename is changed to
> c:\fakepath\name
> EditorFilterMessagesTest fails because a space is added after the text is
> entered.
>
> @seanf <https://github.com/seanf> do you want me to add a commit to
> ignore these instances of difference?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-server/pull/998#issuecomment-145743454>.
>



-- 
Sean Flanigan

Principal Software Engineer
Globalisation Tools Engineering
Red Hat

**Comment by djansen-redhat** [comment]
This is fine assuming a green light.

**Comment by seanf** [comment]
Thanks @djansen-redhat

**Pull request merged**
