### PR TITLE
Fix input field not save when using same text as placeholder: https://bu...

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1185134

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested.  Build has also passed but not reflected here correctly.

**Comment by aeng** [comment]
Merged into release. https://github.com/zanata/zanata-server/commit/4be04f5e536047adfa7f5434b0916804b7bcf92d

**Comment by davidmason** [comment]
@aeng it looks like the only code changes are layout changes and a variable name. Does this really do what the title says?

**Comment by djansen-redhat** [comment]
@aeng Not *exactly*. The major issue is using the actual Zanata ToU url in a placeholder will cause our current system to break.
In future, we should fix the field so that it can tell if the text entered is placeholder or user entered.

**Comment by davidmason** [comment]
There is a fix on the branch I am working in that will separate placeholder text into an attribute properly, so we should be able to fix the field once that is merged.

**Pull request closed without merging**
