### PR TITLE
fix(login redirect):prevent login page redirection after activate account

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-815

Due to bug in jsf 2.1, we are unable to display activation message in the login screen after redirection. This will be solve in the CDO branch.

### CODE REVIEW

**Comment by aeng** [comment]
@zanata-jenkins retest this build please

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested.
Waiting on Jenkins' greenlight.

**Comment by aeng** [comment]
@zanata-jenkins retest this build please

**Comment by aeng** [comment]
@zanata-jenkins retest this build please

**Comment by aeng** [comment]
@zanata-jenkins retest this build please

**Comment by aeng** [comment]
@zanata-jenkins retest this build please

**Pull request merged**
