### PR TITLE
feat(ZNTA-1023): add FileService.fileTypeInfoList()

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1023
https://zanata.atlassian.net/browse/ZNTA-1248

Requires https://github.com/zanata/zanata-api/pull/56
Enables https://github.com/zanata/zanata-client/pull/113

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1244)

### CODE REVIEW

**Comment by aeng** [comment]
I assume we are not changing all the push operation (client, browser) to use file endpoint yet?

---

Review status: 0 of 2 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1244#-:-KN0SdzuOaLzwh-btL2n:-123780237)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1244#-:-KN0Ssy7L8I1iHGidNQS:1417088721)*

**Comment by aeng** [comment]
+Reviewed 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1244#-:-KN0T3dPDBkGLW1yg_Lj:1212982243)*

**Comment by aeng** [comment]
-(Awaiting review) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1244#-:-KN0TN_UKtAmGKy4JUdK:-1466862653)*

**Comment by seanf** [comment]
The work to use the File endpoint for everything (at least in the client) is being tracked in some new issues under the epic https://zanata.atlassian.net/browse/ZNTA-1020, for instance https://zanata.atlassian.net/browse/ZNTA-1238 and https://zanata.atlassian.net/browse/ZNTA-1032

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1244#-:-KN0X96Zt0r-8Sy-3Yih:-1530017790)*

**Comment by djansen-redhat** [comment]
I can't seem to build this. I've built the api change, but this comes back with:
```
[INFO]          [ERROR] Errors in 'file:/home/djansen/dev/zanata-server/zanata-war/src/main/java/org/zanata/webtrans/client/Application.java'
[INFO]             [ERROR] org.zanata.webtrans.shared.model.ProjectIterationId cannot be resolved to a type
[INFO]          [ERROR] Errors in 'file:/home/djansen/dev/zanata-server/zanata-war/src/main/java/org/zanata/webtrans/client/gin/WebTransGinjector.java'
[INFO]             [ERROR] org.zanata.webtrans.client.presenter.DocumentListPresenter cannot be resolved to a type
[INFO]          [ERROR] Errors in 'file:/home/djansen/dev/zanata-server/zanata-war/src/main/java/org/zanata/webtrans/shared/model/ProjectIterationId.java'
[INFO]             [ERROR] org.zanata.common.ProjectType cannot be resolved to a type
[INFO]          [ERROR] Errors in 'file:/home/djansen/dev/zanata-server/zanata-war/src/main/java/org/zanata/webtrans/client/UncaughtExceptionHandlerImpl.java'
[INFO]             [ERROR] org.zanata.webtrans.client.presenter.TargetContentsPresenter cannot be resolved to a type
[INFO]          [ERROR] Errors in 'file:/home/djansen/dev/zanata-server/zanata-war/src/main/java/org/zanata/webtrans/shared/model/WorkspaceId.java'
[INFO]             [ERROR] org.zanata.webtrans.shared.model.ProjectIterationId cannot be resolved to a type
```
and so on. Any idea what I may have missed?

**Comment by seanf** [comment]
@djansen-redhat Sorry, I had been using `-Dnogwt` for my local builds, and one of the changes in zanata-api broke GWT compilation. I have updated https://github.com/zanata/zanata-api/pull/56 to make it work with GWT.

**Comment by djansen-redhat** [comment]
:white_check_mark: tested. Testing this appears to have uncovered a backwards compatibility issue, which prevented me from fully pushing a file to the server, but I don't think that's a problem for this change.

**Comment by seanf** [comment]
@djansen-redhat Thanks. Could I get you to update the JIRA states too, please?

**Pull request merged**
