### PR TITLE
Bump WildFly to 9.0.0.Final

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by seanf** [comment]
@djansen-redhat I think it was just the PR name, not the commits, which had the `\u0001` character.  No need to rebuild after all.

**Comment by djansen-redhat** [comment]
@seanf git log shows me "**^A**Bump WildFly to 9.0.0.Final"

**Comment by djansen-redhat** [comment]
:-1: @seanf This change indicates -9.0.0.final, but [the PR build](http://zanata-build.lab.eng.bne.redhat.com/job/zanata-server-github-pull-requests/3906/consoleFull) is apparently using 9.0.0.CR2.

**Comment by seanf** [comment]
@djansen-redhat That might caused by our byzantine Jenkins config, messing with `wildfly.version` in unpredictable ways.  Backporting https://github.com/zanata/zanata-server/pull/864 to release would help a bit.

I've removed the **^A** from the git commit.

**Comment by djansen-redhat** [comment]
:+1:

**Pull request merged**
