### PR TITLE
Display version state in a standard way

### PR DESCRIPTION
**Pull request by davidmason**
https://bugzilla.redhat.com/show_bug.cgi?id=1202670

Already reviewed in https://github.com/zanata/zanata-server/pull/736 but have rebased on release since changes are needed there.

One change could not be rebased because it is on the version merge template, which exists only on master. I will make a separate pull request for that change after this is merged to release and release is merged to master.

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:x: Release note

**Comment by davidmason** [comment]
> - :x: Release note

@djansen-redhat branch `release` has no `docs/release-notes.md`. I can add a note to `CHANGELOG.md` on this branch (seems like that has not been updated for some time), and put it in `docs/release-notes.md` in the branch on `master`. Does that sound suitable?

**Comment by seanf** [comment]
@davidmason I added release-notes.md to my branch.  If https://github.com/zanata/zanata-server/pull/740 goes in first, you could merge it in and add to the file.

I think we should move CHANGELOG.md into release-notes.md (if it's not there yet) and get rid of it.

**Comment by davidmason** [comment]
> I think we should move CHANGELOG.md into release-notes.md (if it's not there yet) and get rid of it.

:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Looks good to me. You can fight @seanf for merge on this

**Pull request closed without merging**
