### PR TITLE
Upgrade commonmark.js to 0.19.0

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/840" target="_blank">ReviewNinja

**Comment by carlosmunoz** [comment]
:+1: Reviewed commits a44ad08 to a0d1df2

**Comment by definite** [comment]
:+1:

**Comment by seanf** [comment]
Merged in 2d337fa.

**Pull request closed without merging**
