### PR TITLE
Fix null exception in more activity load

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1231054

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/880" target="_blank">ReviewNinja

**Comment by huangp** [comment]
:+1:

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Pull request merged**
