### PR TITLE
Redirect to language list page if language is not supported

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1198898

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/846" target="_blank">ReviewNinja

**Comment by huangp** [comment]
:+1:

**Comment by huangp** [comment]
- [ ] release note

**Comment by djansen-redhat** [comment]
:+1: Nice
:white_check_mark: Tested

**Pull request merged**
