### PR TITLE
Ensure full stack traces and heap dumps in tests

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1303)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: +(No QA) +Reviewed 

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1303#-:-KSdj2nmCmMQcmLyPg8n:bt4q7fc)*

**Comment by aeng** [comment]
Will this cause `out of disk space` issue if there's general error on each test? We were having the issue before where it log entire chrome `404` page with animation.

**Comment by seanf** [comment]
@aeng I believe it only dumps the heap the first time.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Pull request merged**
