### PR TITLE
Use JNDI to obtain mail server from app server

### PR DESCRIPTION
**Pull request by seanf**
In EAP 6, the mail server configuration can be controlled with `mail-session` in the `mail` subsystem, and with an `outbound-socket-binding` in `socket-binding-group`.  This is used to configure the mail session available through JNDI as `java:jboss/mail/Default` and this is the config which can be used to enable JavaMelody's email features.

Switching Zanata to use the JNDI mail session (in `components.xml`) avoids the need to configure the mail server twice, and also allows the app server admin to change the mail server setup without going into Zanata's admin screens.

### CODE REVIEW

**Comment by seanf** [comment]
@djansen-redhat Have you got the `standalone.xml` you were using in the email test?  And which platform was the server on?

**Comment by djansen-redhat** [comment]
@seanf Unfortunately not. I am using Fedora 20.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@djansen-redhat Is there anything I can do to help with this one?

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, looks fine

**Comment by seanf** [comment]
@aeng what happened to the contents of https://github.com/zanata/zanata-server/wiki/Email ?  I had information in there about the new way of configuring email.

**Comment by seanf** [comment]
@djansen-redhat @aeng I found the missing information in the wiki history, and added it to the admin guide.

**Comment by seanf** [comment]
The restored docs are here for now: https://github.com/zanata/zanata-server/blob/use-jndi-for-mail/docs/user-guide/system-admin/configuration/installation.md#email-configuration-zanata-36-or-earlier

**Comment by seanf** [comment]
@djansen-redhat Please look at my changes for the release notes and the sysadmin docs.

**Comment by aeng** [comment]
@seanf Can you please update in docs.zanata.org for the email config?

**Comment by djansen-redhat** [comment]
@aeng @seanf I might give this another go-through before we merge, I could have tested it better

**Comment by seanf** [comment]
@djansen-redhat so you reviewed the docs changes again?

**Comment by djansen-redhat** [comment]
@seanf yes

**Comment by seanf** [comment]
Merged as 3991bfa.

**Pull request closed without merging**
