### PR TITLE
Disable implicit wait in Selenium tests

### PR DESCRIPTION
**Pull request by seanf**
We will have to add some explicit waits (before/around checks) to make this work, but the end result should be a lot more robust.

- [x] Waiting for https://github.com/zanata/zanata-server/pull/779
- [x] Waiting for https://github.com/zanata/zanata-server/pull/782

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
Rebuilding with all functional tests, now that #779 is in release.

**Comment by seanf** [comment]
Waiting for the `form__loader` fix in assets.

**Comment by seanf** [comment]
See also http://assets-zanata.rhcloud.com/6.1.1/styleguide/

**Comment by seanf** [comment]
See also https://github.com/zanata/zanata-server/pull/782

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
We should retest after zanata/zanata-assets#3 is merged and deployed.

**Comment by seanf** [comment]
Rebase and retest after https://github.com/zanata/zanata-server/pull/782 is merged.

**Comment by seanf** [comment]
If it turns out we can't turn off implicit waits completely (or not yet), I suggest we implement our own versions of `findElement(By by)` and `findElements(By by)` which will not perform implicit waits, but will simply use JavaScript DOM lookups (probably with help from jQuery).

This is a list of the By selector types we currently use:

	$ sed -n 's/.*By[.]\([a-zA-Z]*\).*/\1/p' src/**/*.java | sort -u
	className
	cssSelector
	id
	linkText
	name
	tagName
	xpath

We would need to implement support for some or all of the above `By` types, but we could skip the others (like partialLinkText).

**Comment by seanf** [comment]
If we end up implementing our own `findElement(By by)` and `findElements(By by)`, @davidmason suggested that we use the following functions rather than depend on jQuery (at least for the simpler `By` types):

 - https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelectorAll
 - https://developer.mozilla.org/en-US/docs/Web/API/NodeList/length

**Comment by djansen-redhat** [comment]
Replaced by #804

**Pull request closed without merging**
