### PR TITLE
Log start/finish for each Arquillian test

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/832" target="_blank">ReviewNinja

**Comment by carlosmunoz** [comment]
:+1: (am I supposed to do something with review ninja?)

**Comment by seanf** [comment]
@carlosmunoz We're mainly using it to get notifications, not to manage the process.  If you connect to ReviewNinja, it can email you when new PRs are created, or existing PRs are updated.  A bit better than GitHub's own notifications.

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Pull request merged**
