### PR TITLE
zanata-spa UI fixes

### PR DESCRIPTION
**Pull request by davidmason**
Update zanata-spa to commit 7d6c54600db4d8b747f8a919b1aa2fd89b1f6824

Changes:

 - [x] Add 100% height to editor wrapper so background is 100% in firefox
 - [x] Fix dropdown/transunit overflow problems
 - [x] Applying difference properties to the right elements… again.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/866" target="_blank">ReviewNinja

**Comment by davidmason** [comment]
:+1: code changes reviewed in zanata-spa repo.

**Comment by djansen-redhat** [comment]
- [ ] [Menu on dropdowns is overflowing to the right](http://i.imgur.com/mXBkTxX.png)

**Comment by davidmason** [comment]
:+1: reviewed new commits in zanata-spa :dog:

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@definite @davidmason This should also be in release 3.7.0.

**Comment by davidmason** [comment]
Merged to branch `release`, and merged `release` to `integration/master`.

This should close automatically when `integration/master` is verified and automatically merged to `master`.

**Comment by seanf** [comment]
@davidmason Actually, it should have closed as soon as you merged to `integration/master` (PR target branch).  Are you sure you didn't rebase or amend these commits?

**Comment by davidmason** [comment]
@seanf I did a squash-merge of it, so now that I think about it I do not expect it to pick up automatically.

**Comment by davidmason** [comment]
@seanf I did a squash-merge of it, so now that I think about it I do not expect it to pick up automatically. I will close this manually when the verify build completes successfully.

**Comment by davidmason** [comment]
Squash-merged in https://github.com/zanata/zanata-server/commit/8a50c5785f901823e28f62ab1a287ab5d5ceb0ca

**Pull request closed without merging**
