### PR TITLE
Extract general components from frontend to zanata-ui

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1230

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1238)

### CODE REVIEW

**Comment by davidmason** [comment]
This one is just removing all the components that are extracted to zanata-ui, right?

---

Review status: 0 of 164 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1238#-:-KMgqlYw7o2E4mdNRVfN:1929975167)*

**Comment by aeng** [comment]
Yes.

---

Review status: 0 of 164 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1238#-:-KMgtDUVw3MzH7iVszGF:-480046914)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +(On QA) 

---

Reviewed 137 of 208 files at r1, 2 of 4 files at r2, 177 of 177 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1238#-:-KMvf81FD5j_A2vlVCQC:1855663026)*

**Comment by djansen-redhat** [comment]
Waiting for green light

**Comment by huangp** [comment]
+Reviewed 

---

Review status: 214 of 215 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1238#-:-KMwEdU4QMfQOMEbGBtD:1212982243)*

**Comment by huangp** [comment]
Reviewed 1 of 177 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1238)*

**Pull request merged**
