### PR TITLE
Migrate Seam 2 to CDI

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-530

### CODE REVIEW

**Comment by seanf** [comment]
Some of these commits are going into https://github.com/zanata/zanata-server/pull/889 so that they can be merged sooner.

**Comment by seanf** [comment]
This now depends on https://github.com/zanata/zanata-server/pull/894

**Comment by seanf** [comment]
See also https://github.com/zanata/zanata-server/pull/908 (Replace Seam Security).

**Comment by seanf** [comment]
I have merged in the heads of the other CDI branches again.

**Comment by seanf** [comment]
Looks like TranslationMemoryAction.lastTaskResult (`@Produces` field, used to be `@In Out` bijected) will always be null. @carlosmunoz where should this value come from?

**Comment by seanf** [comment]
> Looks like TranslationMemoryAction.lastTaskResult (`@Produces` field, used to be `@In @Out` bijected) will always be null. @carlosmunoz where should this value come from?

We need to specify a scope too. ViewScoped?

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
Sean's review checklist:

- [ ] Transaction management (`TransactionUtil`/`@Transactional`)
- [ ] Event handling (`Event.fire`/`@Observes`)
- [ ] Exception handling
- [ ] New security interceptors
- [ ] Navigation rules (formerly in `pages.xml`)
- [ ] `AsyncTaskManager` and `@Async`
- [ ] producer methods/fields (`@Produces`)
- [ ] ApplicationScoped
- [ ] RequestScoped
- [ ] SessionScoped
- [ ] ViewAccessScoped
- [ ] ViewScoped
- [ ] WindowScoped
- [ ] Dependent (or unspecified scope) NB: no interceptors!

unused scopes:
- [x] TransactionScoped
- [x] ThreadScoped
- [x] Singleton

**Comment by huangp** [comment]
Patrick's review check list:
- [ ] Transaction management (`TransactionUtil`/`@Transactional`)
- [ ] Event handling (`Event.fire`/`@Observes`)
- [ ] Exception handling
- [ ] New security interceptors
- [ ] Navigation rules (formerly in `pages.xml`)
- [ ] `AsyncTaskManager` and `@Async`
- [ ] producer methods/fields (`@Produces`)
- [ ] ApplicationScoped
- [ ] RequestScoped
- [ ] SessionScoped
- [ ] ViewAccessScoped
- [ ] ViewScoped
- [ ] WindowScoped
- [ ] Dependent (or unspecified scope) NB: no interceptors!

**Comment by seanf** [comment]
@huangp the javadocs for AbstractExceptionHandler says it is for JSF and REST. How is it "hooked up" for REST exception handling (I can't see any JAX-RS annotations)? 

How can we ensure that JSF concerns (eg FacesMessages) don't interfere with REST requests?

**Comment by huangp** [comment]
I realized it when my REST throws exceptions and it gets caught first in
these handlers. Maybe not for all type of exceptions but for the ones that
is generated from within deltaspike, to be specific, security interceptors,
it will raise an exception event first. And that in result will hit this
handlers first. Then bubble the exception up which will then hit JAX-RS
exception mapper.

FacesMessages is in window scope that's why we check for that scope first
before we try to use it.

On Thu, Dec 10, 2015 at 2:32 PM, Sean Flanigan <notifications@github.com>
wrote:

> @huangp <https://github.com/huangp> the javadocs for
> AbstractExceptionHandler says it is for JSF and REST. How is it "hooked up"
> for REST exception handling (I can't see any JAX-RS annotations)?
>
> How can we ensure that JSF concerns (eg FacesMessages) don't interfere
> with REST requests?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-server/pull/886#issuecomment-163485557>.
>



-- 
Patrick Huang
Senior Software Engineer
Engineering - Internationalisation
Red Hat, Asia-Pacific Pty Ltd
Level 1, 193 North Quay
Brisbane 4000
Office: +61 7 3514 8278
Fax: +61 7 3514 8199
IRC: pahuang
github: github.com/huangp
Website: www.redhat.com

**Comment by seanf** [comment]
@huangp so, basically we don't know why these exception handlers are active for REST requests?

**Comment by carlosmunoz** [comment]
Sean's review checklist:

- [ ] Transaction management (`TransactionUtil`/`@Transactional`)
- [ ] Event handling (`Event.fire`/`@Observes`)
- [ ] Exception handling
- [ ] New security interceptors
- [ ] Navigation rules (formerly in `pages.xml`)
- [ ] `AsyncTaskManager` and `@Async`
- [ ] producer methods/fields (`@Produces`)
- [ ] ApplicationScoped
- [ ] RequestScoped
- [ ] SessionScoped
- [ ] ViewAccessScoped
- [ ] ViewScoped
- [ ] WindowScoped
- [ ] Dependent (or unspecified scope) NB: no interceptors!

unused scopes:
- [ ] TransactionScoped
- [ ] ThreadScoped
- [ ] Singleton

**Comment by seanf** [comment]
@huangp @carlosmunoz 

If anyone else is currently reviewing the scopes, note that I just pushed a commit which adds explicit scopes to the beans which were using default scopes (at least the Named beans). I used RequestScoped for the RESTEasy service beans, Dependent for the others.

**Comment by seanf** [comment]
@carlosmunoz I don't really understand JSF (and faces-config.xml) well enough to review the item "Navigation rules (formerly in pages.xml)", so I hope you'll be able to look at that part.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
I don't recommend we use squash merge for this branch. The git history may be a mess, but I think it will be really helpful for understanding why things are the way they are.

**Comment by carlosmunoz** [comment]
> @carlosmunoz I don't really understand JSF (and faces-config.xml) well enough to review the item "Navigation rules (formerly in pages.xml)", so I hope you'll be able to look at that part.

Done.

**Comment by djansen-redhat** [comment]
1. sign in and go to a project
2. go to a version, language, document
3. Click the magnifying glass to go to Project Search and Replace
4. Enter 'a' (no quote) into the search box
5. Press Search

http://pastebin.test.redhat.com/335017

```
14:11:02,631 ERROR [org.zanata.webtrans.server.SeamDispatch] (http-localhost.localdomain/127.0.0.1:8080-8) Error dispatching action: java.lang.ClassCastException: org.jboss.weld.proxies.Serializable$Session$SharedSessionContract$-1849318850$Proxy$_$$_WeldClientProxy cannot be cast to org.hibernate.event.spi.EventSource: java.lang.ClassCastException: org.jboss.weld.proxies.Serializable$Session$SharedSessionContract$-1849318850$Proxy$_$$_WeldClientProxy cannot be cast to org.hibernate.event.spi.EventSource
```

**Comment by huangp** [comment]
Last commit should fix this

On Mon, Dec 14, 2015 at 2:15 PM, Damian Jansen <notifications@github.com>
wrote:

>
>    1. sign in and go to a project
>    2. go to a version, language, document
>    3. Click the magnifying glass to go to Project Search and Replace
>    4. Enter 'a' (no quote) into the search box
>    5. Press Search
>
> http://pastebin.test.redhat.com/335017
>
> 14:11:02,631 ERROR [org.zanata.webtrans.server.SeamDispatch] (http-localhost.localdomain/127.0.0.1:8080-8) Error dispatching action: java.lang.ClassCastException: org.jboss.weld.proxies.Serializable$Session$SharedSessionContract$-1849318850$Proxy$_$$_WeldClientProxy cannot be cast to org.hibernate.event.spi.EventSource: java.lang.ClassCastException: org.jboss.weld.proxies.Serializable$Session$SharedSessionContract$-1849318850$Proxy$_$$_WeldClientProxy cannot be cast to org.hibernate.event.spi.EventSource
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-server/pull/886#issuecomment-164339248>.
>



-- 
Patrick Huang
Senior Software Engineer
Engineering - Internationalisation
Red Hat, Asia-Pacific Pty Ltd
Level 1, 193 North Quay
Brisbane 4000
Office: +61 7 3514 8278
Fax: +61 7 3514 8199
IRC: pahuang
github: github.com/huangp
Website: www.redhat.com

**Comment by seanf** [comment]
(Moved from the pull request description)

- [x] Rebase this branch and re-run sed script after #908 goes in
- [x] Implement support for session/event scope in SeamAutowire.   (Or port ZanataIdentityTest to CDI-Unit.)  See https://github.com/zanata/zanata-server/commit/ac5c32b2f040535319843d7210365b0dd8c7a181#commitcomment-12458024
- [x] Merge all the other PRs relating to CDI: https://github.com/zanata/zanata-server/labels/CDI - this branch now incorporates #1001 
- [x] ZanataSecurityInterceptor is still using `@ZanataSecured`. Should be able to use DeltaSpike's `@Secured` or similar, instead of this interceptor? https://zanata.atlassian.net/browse/ZNTA-808
- [x] Get things working on WildFly again (project page, GWT editor) https://zanata.atlassian.net/browse/ZNTA-792

## issues found ##
- [x] async tasks seems to mess up transaction in current request (org.zanata.feature.dashboard.DashboardTest)
- [x] validation message has changed to include client id (org.zanata.feature.security.SecurityTest#resetPasswordSuccessful)
- [x] push large documents (presumably a factor) will cause following error log but the push seems to be successful (e.g. source and translation saved.
```
14:36:50,887 WARN  [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (pool-10-thread-6) SQL Error: 0, SQLState: null
14:36:50,887 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (pool-10-thread-6) javax.resource.ResourceException: IJ000460: Error checking for a transaction
14:36:50,888 ERROR [org.jboss.weld.Event] (pool-10-thread-6) WELD-000401 Failure while notifying an observer of event TextFlowTargetStateEvent(actorId=null, projectIterationId=5, documentId=25, textFlowId=44733, localeId=ja, textFlowTargetId=9949, newState=Translated, previousState=New)
14:36:50,888 WARN  [org.hibernate.ejb.AbstractEntityManagerImpl] (pool-10-thread-6) HHH000326: Cannot join transaction: do not override hibernate.transaction.factory_class
14:36:50,888 ERROR [org.jboss.weld.Event] (pool-10-thread-6) WELD-000401 Failure while notifying an observer of event TextFlowTargetStateEvent(actorId=null, projectIterationId=5, documentId=25, textFlowId=44733, localeId=ja, textFlowTargetId=9949, newState=Translated, previousState=New)
```
- [x] `ConcurrentModificationException` logged on server when a session times out (fixed by f0d133e?)
- [x] Leaking JMS `QueueSession`s reported in server log (created by `JmsResourcesProducer.createQueueSession`)
- [x] error page url (redirected to) e.g. http://localhost:8080/zanata/error?dswid=12345 result in 404
- [x] delete user will trigger NoSuchUserException in the background but user is deleted (UI unchanged)
- [x] after activation and log in, it redirects back to log in page (https://zanata.atlassian.net/browse/ZNTA-815)
## TODO adapt/check components.xml config
https://zanata.atlassian.net/browse/ZNTA-790
- [x] core:init settings (seems to work)
- [ ] ~~set 20 min conversation/WindowScoped timeout ([not built-in for DeltaSpike](https://issues.apache.org/jira/browse/DELTASPIKE-437))~~
- [x] QuartzDispatcher
- [x] REST: /restv1
- [x] web:multipart-filter configuration?
- [x] web:multipart-filter again, disabled!
- [x] mailQueueSender?
- [x] web:identity-filter not needed
- [x] persistence:entity-manager-factory (seems to work)
- [x] persistence:managed-persistence-context (seems to work)
- [x] NotLoggedInEvent/LoginSuccessfulEvent (UserRedirectBean)
- [x] web:redirect-filter?
- [x] ApplicationConfiguration:debug
- [x] ApplicationConfiguration:authenticatedSessionTimeoutMinutes=180
- [x] EssentialDataCreator (seems to work)
- [x] mail:mail-session:java:jboss/mail/Default

## Things to review
- [x] check all `@Produces` methods for correct scope
- [x] check all `@Produces` methods for corresponding `@Disposes` method (if required)
- [x] check that all logic from `pages.xml` has been migrated: https://zanata.atlassian.net/browse/ZNTA-789
- [ ] ~~check that our bean scopes aren't too large, eg Conversation->ViewAccessScoped - will our sessions become bloated? (https://zanata.atlassian.net/browse/ZNTA-791)~~

## Things to test (moved to https://zanata.atlassian.net/browse/ZNTA-799)

**Comment by seanf** [comment]
Ignoring intermittent test `org.zanata.feature.language.JoinLanguageTeamTest.translatorJoinsLanguageTeam`. Thanks @djansen-redhat

**Pull request merged**
