### PR TITLE
feat(editor): Update alpha editor

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-841

https://github.com/zanata/zanata-spa/pull/98

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1201)

### CODE REVIEW

**Comment by seanf** [comment]
This PR could use a more meaningful name, I think.

**Comment by djansen-redhat** [comment]
- [ ] 403 error (localhost:7878/zanata/rest/source+trans/af) on messages.properties - the other test files I have seem to work.
- [ ] Changing the current language or document in breadcrumb setup does not change the breadcrumb label, meaning any other changes will revert back to the displayed document/language
- [ ] Cannot click on some of the listed languages
- Clicking the Project name, top left, leads to a 404 (has "/app/" in the url)
- [ ] Save as Untranslated not available when undoing a saved translation (Enter text into field, press save, press undo)
- [ ] Clicking the "Difference" toggle seems to cause a panel to flash in Chrome

**Comment by aeng** [comment]
>  What is the language menu to the left of the user avatar for?

Thats for localisation of the editor.

**Comment by djansen-redhat** [comment]
:white_check_mark: no major issues, some minor but can be fixed later

**Comment by aeng** [comment]
> Save as Untranslated not available when undoing a saved translation (Enter text into field, press save, press undo) (fix later)

Think the `undo edit` feature is mess up. It should only available when there's changes in translation, and should not be available after save.

**Comment by djansen-redhat** [comment]
Acknowledged.
:white_check_mark: retested.

**Comment by aeng** [comment]
> Clicking the "Difference" toggle seems to cause a panel to flash in Chrome (fix later)

Bug of css3 in chrome. `transform` of the toggle button causes the issue.

**Comment by djansen-redhat** [comment]
:white_check_mark: Re-verified

**Pull request merged**
