### PR TITLE
fix(gwt): avoid packaging .junit_symbolMaps/

### PR DESCRIPTION
**Pull request by seanf**
This should reduce the size of zanata.war, and probably speed up builds
a bit too.

### CODE REVIEW

**Comment by davidmason** [comment]
@seanf I probably would have classified this as type "chore" since it looks like it is primarily a build change. What do you think?

**Comment by seanf** [comment]
Hmm, could be either, the unnecessary ~25MB of .war file could be viewed as a non-functional bug.  It's not just changing the build process, it's also changing the artifact.

**Comment by seanf** [comment]
@davidmason Could you review this PR, please?

**Comment by davidmason** [comment]
:+1:

**Pull request merged**
