### PR TITLE
fix(ZNTA-1072):fix selectManyCheckbox in filter

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1072

### CODE REVIEW

**Comment by huangp** [comment]
@seanf I think this will defeat the purpose of your duplicate param filter. Maybe we need to iterate through both name and values and only remove them if both are the same.

**Comment by aeng** [comment]
@huangp I was thinking the same. This filter actually prevents grouped component in form, e.g. grouped checkboxes, group radio button. Whats the use case for this filter?

**Comment by seanf** [comment]
> @seanf I think this will defeat the purpose of your duplicate param filter. 

@huangp You're quite right. The job of this class is to eliminate duplicate params introduced by a bug in ocpsoft rewrite. I was hoping we wouldn't need duplicate params for ourselves, but apparently we do.

> Maybe we need to iterate through both name and values and only remove them if both are the same.

I had considered doing that, but wanted to keep the filter simple if possible. Are we sure that this would fix the current problem? Or might it _need_ two identical name/value combinations?

I don't suppose it would be possible to avoid the use of multiple param values?

The only complete fix would be a fix for https://github.com/ocpsoft/rewrite/issues/223

**Comment by seanf** [comment]
Also note the existence of https://github.com/zanata/zanata-server/pull/1153 which touches the same class. We're going to have conflicts.

**Comment by seanf** [comment]
I'll update #1153 to deduplicate identical values for the same parameter name.

**Comment by aeng** [comment]
Fixed in https://github.com/zanata/zanata-server/pull/1153.

**Pull request closed without merging**
