### PR TITLE
Disable implicit wait

### PR DESCRIPTION
**Pull request by djansen-redhat**
Instead of waiting for the WebDriver built-in waits, which can be very slow, wait only for the elements that are required for interaction and for the page ajax calls to complete.

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Half of this work is reviewed already, up to my changes at least.

**Comment by seanf** [comment]
Okay, I'm looking at https://github.com/zanata/zanata-server/compare/5c73d6d...disable-implicit-wait-master

**Comment by seanf** [comment]
@djansen-redhat :+1: LGTM

**Comment by djansen-redhat** [comment]
Only one small change after last review. It's green!

**Comment by seanf** [comment]
:+1:

**Comment by djansen-redhat** [comment]
Squash merge 1dd52588ccf7b0e2ce2a182e04cd83aa8827e3f6

**Pull request closed without merging**
