### PR TITLE
Update Fedora OpenID endpoint to secure one

### PR DESCRIPTION
**Pull request by puiterwijk**
Signed-off-by: Patrick Uiterwijk <puiterwijk@redhat.com>

### CODE REVIEW

**Comment by aeng** [comment]
@zanata-jenkins ok to test.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by puiterwijk** [comment]
Any feedback on this patch?

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Pull request merged**
