### PR TITLE
fix(show password):enable 'show' password after reset

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-818

### CODE REVIEW

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by carlosmunoz** [comment]
:+1:

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
Working good.

**Comment by aeng** [comment]
Merged into release. https://github.com/zanata/zanata-server/commit/829fe735f2a8d4588dc296261e21d30f6c9aff36

**Pull request closed without merging**
