### PR TITLE
fix(ZNTA-803): Fix broken link to admin monitoring page

### PR DESCRIPTION
**Pull request by djansen-redhat**
https://zanata.atlassian.net/browse/ZNTA-803

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@definite Admin monitoring link was not working as JSF decided it wasn't really a page.

**Comment by definite** [comment]
:+1:

**Comment by definite** [comment]
Zanata 3.8.0-rc-2-SNAPSHOT (git-jenkins-zanata-server-github-pull-requests-4982) does not seem to fix the bug.

**Comment by definite** [comment]
:+1:

**Comment by djansen-redhat** [comment]
Thanks @seanf

**Comment by seanf** [comment]
@djansen-redhat @definite Is it working on both eap and wildfly?

**Comment by definite** [comment]
It works in EAP, not sure about wildfly. @djansen-redhat, how's thing on your side?

**Comment by djansen-redhat** [comment]
@definite verified Wildfly 901final

**Pull request merged**
