### PR TITLE
Happy path testing

### PR DESCRIPTION
**Pull request by djansen-redhat**
- [x] Long winded end to end tests
- [x] Very short list of other BATs

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/978)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Will conflict with #970

**Comment by seanf** [comment]
So the plan is to include the end to end test in the BATs, and switch pull requests to run BATs only, with the other tests running when?  Is the plan still to convert those other tests into Arquillian tests?

**Comment by djansen-redhat** [comment]
Ideally, yes - "scenario" BAT tests on pull requests, other tests maybe once per day, and as much in Arquillian (particularly the negative tests) as possible.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@djansen-redhat looks like the tests were green.

**Pull request closed without merging**
