### PR TITLE
fix(side menu): fix ROOT context url path

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1164

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1197)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[frontend/src/main/web/src/legacy.js, line 51 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1197#-KJmxkrneJeikL3KhEg-:-KJmxkrneJeikL3KhEg0:1258863252) ([raw file](https://github.com/zanata/zanata-server/blob/24221c4750f50284b212446136887a40482dc88c/frontend/src/main/web/src/legacy.js#L51)):*
> ```JavaScript
> 
> const links = {
>   'context': window.config.baseUrl ? window.config.baseUrl : '',
> ```

It's not important, but would this work too (to avoid making the line much longer than it was)?

    'context': window.config.baseUrl || '',

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1197)*

**Comment by huangp** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[frontend/src/main/web/src/legacy.js, line 51 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1197#-KJmxWfEbGwIvqI0yHBd:-KJmxWfEbGwIvqI0yHBe:-1782398051) ([raw file](https://github.com/zanata/zanata-server/blob/24221c4750f50284b212446136887a40482dc88c/frontend/src/main/web/src/legacy.js#L51)):*
> ```JavaScript
> 
> const links = {
>   'context': window.config.baseUrl ? window.config.baseUrl : '',
> ```

I think you can just use ```window.config.baseUrl || ''```. It will be shorter. But it's not a blocking issue

---

*[frontend/src/main/web/src/containers/App.js, line 34 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1197#-KJmxt_Hf5kW1LdvqImV:-KJmxt_Hf5kW1LdvqImW:1662569705) ([raw file](https://github.com/zanata/zanata-server/blob/24221c4750f50284b212446136887a40482dc88c/frontend/src/main/web/src/containers/App.js#L34)):*
> ```JavaScript
> 
>     const links = {
>       'context': config.baseUrl ? config.baseUrl : '',
> ```

Same here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1197)*

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### fix\(side menu\): fix ROOT context url path
> 
> https://zanata.atlassian.net/browse/ZNTA-1164
> 
> 
> 
</details>


---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1197#-:-KJn8pnDuRf4e5UoHBHb:1417088721)*

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. Please mark as reviewed on Reviewable and publish.

**Pull request merged**
