### PR TITLE
Language react

### PR DESCRIPTION
**Pull request by kathryngo**
React + Bootstrap admin page
https://zanata.atlassian.net/browse/ZNTA-1333

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1280)

### CODE REVIEW

**Comment by davidmason** [comment]
@kathryngo is this assigned to me for review? If so, use labels to indicate where it is at with that.

**Comment by kathryngo** [comment]
Apologies David, label has been applied and yes please review if you can.

**Comment by davidmason** [comment]
@kathryngo has our standard eslint check been run on all this code?

**Comment by kathryngo** [comment]
@

**Comment by kathryngo** [comment]
Closed pull request. Do not merge

**Pull request closed without merging**
