### PR TITLE
Add JMS configuration to standalone.xml

### PR DESCRIPTION
**Pull request by carlosmunoz**
The necessary JMS configuration was missing from the overlay's standalone files.

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@huangp could you please check that I didn't mess anything up in the JMS configuration?

**Comment by huangp** [comment]
:+1: looks good to me except you commented out admin user jndi binding. Not sure if it's intentional.

**Comment by carlosmunoz** [comment]
Thanks!
Yes, it is intentional. It seems jboss doesn't like empty jndi property values. So I thought better to leave it commented out instead of coming up with a possibly wrong default value.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, just waiting on green light from Jenkins

**Comment by carlosmunoz** [comment]
Squash merged in 2c4f8ec240745b9ca7baac7b53168814e9e87046

**Pull request closed without merging**
