### PR TITLE
Detect incomplete transactions during tests

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1231)

- [x] Write unit tests

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by carlosmunoz** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-war/src/main/java/org/zanata/database/ConnectionWrapper.java, line 109 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1231#-KMRKQDCYBXVl1y4Yv5O:-KMRKQDCYBXVl1y4Yv5P:568916227) ([raw file](https://github.com/zanata/zanata-server/blob/572d55ad7712019a69422d8feb5a9f97dd96c619/zanata-war/src/main/java/org/zanata/database/ConnectionWrapper.java#L109)):*
> ```Java
>         if (this.autoCommit != autoCommit) {
>             this.autoCommit = autoCommit;
>             beforeTransactionComplete();
> ```

why the call to this method here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1231)*

**Comment by seanf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-war/src/main/java/org/zanata/database/ConnectionWrapper.java, line 109 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1231#-KMRKQDCYBXVl1y4Yv5O:-KMRhjDxxX6JSZru0FQw:1124686242) ([raw file](https://github.com/zanata/zanata-server/blob/572d55ad7712019a69422d8feb5a9f97dd96c619/zanata-war/src/main/java/org/zanata/database/ConnectionWrapper.java#L109)):*
According to the javadocs for setAutoCommit:

> NOTE: If this method is called during a transaction and the auto-commit mode is changed, the transaction is committed. If setAutoCommit is called and the auto-commit mode is not changed, the call is a no-op.

I'll add a comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1231)*

**Comment by carlosmunoz** [comment]
:lgtm:
-(Awaiting review) +Reviewed 

---

Reviewed 3 of 3 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1231#-:-KMRn_5rhX_p-VkMHTTC:-1149335731)*

**Comment by djansen-redhat** [comment]
Is this behaviour unit-testable?

**Comment by seanf** [comment]
Yes, it should be. I might find time for that eventually...

**Comment by seanf** [comment]
@carlosmunoz Could you review the new changes, please?

**Comment by carlosmunoz** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1231)*

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
There were three failures in the functional tests (org.zanata.feature.administration.EditTranslationMemoryTest), but they are unrelated to this change (broken in master :disappointed:).

**Comment by djansen-redhat** [comment]
:white_check_mark: With the added unit tests and Jenkins' blessing, I'm ok with this

**Pull request merged**
