### PR TITLE
Retry flaky tests

### PR DESCRIPTION
**Pull request by seanf**
- [ ] waiting for surefire/failsafe 2.19 to be released

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/770)

### CODE REVIEW

**Comment by seanf** [comment]
The retries don't work because of a bug in failsafe: https://issues.apache.org/jira/browse/SUREFIRE-1152

**Comment by seanf** [comment]
Waiting for https://issues.apache.org/jira/browse/SUREFIRE-1152 to be fixed and then released.

**Comment by seanf** [comment]
If the tests pass, I suggest we merge this to `integration/master` (since it depends on a SNAPSHOT and only merge to `release` when `maven-failsafe-plugin:2.19` has been released.

**Comment by seanf** [comment]
Basic tests (including FlakyTest) passed, full tests are still running.

**Comment by seanf** [comment]
Full functional tests passed, but the Arquillian tests ran out of memory (Jenkins problem).  Passed on a second try.

**Comment by djansen-redhat** [comment]
:white_check_mark: Looks good. Fails appropriately on a "real" failure.

**Comment by seanf** [comment]
Merged to `integration/master` as 7b514b8f7887cfa3671dc9053ed02a5e9cf8d2be.

**Comment by seanf** [comment]
Waiting to merge to `release` when we can use failsafe 2.19 final.

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
Covered by https://github.com/zanata/zanata-server/pull/1017

**Pull request closed without merging**
