### PR TITLE
fix(ZNTA-668): Server settings tests disabled

### PR DESCRIPTION
**Pull request by djansen-redhat**

### CODE REVIEW

**Comment by aeng** [comment]
:+1:

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Pull request closed without merging**
