### PR TITLE
feat(webhook): refactor and additional webhook

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1166

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1286)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 30 of 30 files at r1.
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[zanata-model/src/main/java/org/zanata/model/WebHook.java, line 117 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRQsmvl4-6JmrKF361c:-KRQsmvl4-6JmrKF361d:b5zbe48) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-model/src/main/java/org/zanata/model/WebHook.java#L117)):*
> ```Java
>             }
>         }
>     }
> ```

So here is to make sure this.types will become exactly the same a newTypes? Please put a javadoc on the method to help explaining the purpose.
   

---

*[zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 232 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRQu4iwsR1RmhwF7ELg:-KRQu4ix6gTqVRPBkpUJ:b-9dttiu) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L232)):*
> ```Java
> 
> //    private Map<Long, List<WebhookType>> webhookUrlMapToType = null;
> //    private Map<String, List<WebHook>> webhookUrlMapToWebHook = null;
> ```

remove this?

---

*[zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 1094 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRQuW1rtkPMFT55K5Lp:-KRQuW1rtkPMFT55K5Lq:by0lxse) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L1094)):*
> ```Java
>         identity.checkPermission(getInstance(), "update");
>         Set<WebhookType> types = getTypesFromString(strTypes);
>         if (isValidUrl(url, true) && !types.isEmpty()) {
> ```

What happen if types is empty? Looks like it will be no op. Should we notify the user this will be effectively removing webhook?

---

*[zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 1125 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRQwz-LgWWe-4JEipZb:-KRQwz-LgWWe-4JEipZc:b-5cfmcv) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L1125)):*
> ```Java
>         Set<WebhookType> types = getTypesFromString(strTypes);
>         if (webHook != null && isValidUrl(url, false) && !types.isEmpty()) {
>             getInstance().getWebHooks().remove(webHook);
> ```

Do we have to remove and add back in for update? Can we update the webHook entity directly?

---

*[zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 1128 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRQwbBtkmYtLzDxk5Vc:-KRQwbBtkmYtLzDxk5Vd:bg0mti6) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L1128)):*
> ```Java
>             secret = StringUtils.isBlank(secret) ? null : secret;
>             webHook.update(url, types, secret);
>             getInstance().getWebHooks().add(webHook);
> ```

Could we move all this logic in the DAO or service class? That  way when we migrate to React frontend, we don't need to migrate all this code again. 

---

*[zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 1152 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRQyVeM5hx7TEENC4U_:-KRQyVeNrhjgnkJzt-v0:b-gnuig7) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L1152)):*
> ```Java
>             return false;
>         }
>         if(checkDuplication) {
> ```

We may need a hibernate validator for this. If two maintainer are trying to add the same webhook at the same time, I think there is a chance they are able to both enter the duplicate url and save it. Check slug Unique validator for reference.

---

*[zanata-war/src/main/java/org/zanata/action/VersionHome.java, line 460 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRR0F09iy8GcL8uJxaL:-KRR0F0AtW9VDO7PFW7q:b-g9i2tb) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/VersionHome.java#L460)):*
> ```Java
>                 project.getCustomizedValidations());
>         String result = super.persist();
>         webhookServiceImpl.processWebhookVersionChanged(getProjectSlug(), slug,
> ```

you may need to check the result to determine whether the creation is actually success. Even so, there is a chance that the transaction may fail for whatever reason and your webhook event has already been published. I think the best place for firing webhook is to use an EntityListener on post commit event. 

---

*[zanata-war/src/main/java/org/zanata/action/VersionHome.java, line 577 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRR1UlqmUZTIjOTFeHq:-KRR1Ulrup2ibSptxKlM:b-gk2ifh) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/VersionHome.java#L577)):*
> ```Java
>         webhookServiceImpl.processWebhookVersionChanged(getProjectSlug(), slug,
>                 getProject().getWebHooks(),
>                 VersionChangedEvent.ChangeType.DELETED);
> ```

Same as above. Unless WebHooksPlublisher participate in transaction, we can't trust the update before transaction is committed. 

---

*[zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRR3mHMSPaMFEMLexjt:-KRR3mHMSPaMFEMLexju:b5ksf1b) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java#L26)):*
> ```Java
>     public List<WebHook> findByUrl(String url) {
>         Query q = getSession().createQuery("from WebHook where url =:url")
>             .setParameter("url", url)
> ```

I can't find url being indexed in database. You may want to create an index for this field if it's going to be searched.

---

*[zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java, line 230 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRR24ZG5b5GYhl2L37E:-KRR24ZG5b5GYhl2L37F:b-bz58ww) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java#L230)):*
> ```Java
> 
>             if (isCreateOperation) {
>                 webhookServiceImpl.processWebhookSourceDocumentChanged(
> ```

Need to wait till transaction is successful.

---

*[zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java, line 256 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRR29YlGIc-wYckSobe:-KRR29YlGIc-wYckSobf:b-bz58ww) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/service/impl/DocumentServiceImpl.java#L256)):*
> ```Java
>         HProjectIteration version = document.getProjectIteration();
>         HProject proj = version.getProject();
>         webhookServiceImpl.processWebhookSourceDocumentChanged(
> ```

Need to wait till transaction is successful.

---

*[zanata-war/src/main/java/org/zanata/service/impl/RegisterServiceImpl.java, line 241 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRR2KxZKWN3SbpUsuWg:-KRR2KxZKWN3SbpUsuWh:b-bz58ww) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/service/impl/RegisterServiceImpl.java#L241)):*
> ```Java
>             for (HProject proj : maintainedProjects) {
>                 proj.addMaintainer(activePerson);
>                 webhookServiceImpl.processWebhookMaintainerChanged(proj.getSlug(),
> ```

Need to wait till transaction is successful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 12 unresolved discussions.

---

*[zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 1094 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRQuW1rtkPMFT55K5Lp:-KRRJ0S_Jz1KwpHJDbfl:bykhbim) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L1094)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> What happen if types is empty? Looks like it will be no op. Should we notify the user this will be effectively removing webhook?
</details>
Frontend has validation to prevent it. I think we should provide some message too.

---

*[zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRR3mHMSPaMFEMLexjt:-KRRarzBVun9wgHIxwrd:bpucttc) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java#L26)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I can't find url being indexed in database. You may want to create an index for this field if it's going to be searched.
</details>
url is longtext in db, and don't think we can index it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286)*

**Comment by seanf** [comment]
*[zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java, line 26 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRR3mHMSPaMFEMLexjt:-KRRejbZCFiZKIU4Gat4:bqhz0s0) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java#L26)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> url is longtext in db, and don't think we can index it.
</details>
If we can't index it, perhaps we need to reconsider whether it should be longtext, or whether you should by able to search for webhooks by URL. Table scans are never a good idea for production code, because they scale so badly.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286)*

**Comment by seanf** [comment]
@aeng Given that `WebhooksPublisher.publish()` uses async HTTP, is it really worth using the `@Async` annotation (which uses worker threads) as well?

**Comment by aeng** [comment]
@seanf The Async needs to be there to ensure the CDI event works. Thats how I understand it. But let me know if its not needed.

**Comment by huangp** [comment]
Reviewed 17 of 18 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[docs/user-guide/projects/project-settings.md, line 168 at r3](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRWyhH56pfiSsEXHK5d:-KRWyhH56pfiSsEXHK5e:b-6w0pe1) ([raw file](https://github.com/zanata/zanata-server/blob/c2da9bf768e242591b93605645a754cedae7f498/docs/user-guide/projects/project-settings.md#L168)):*
> ```Markdown
> {
>     "eventType": "org.zanata.events.DocumentMilestoneEvent",
>     "milestone": "100% Translated",
> ```

Is this payload supposed to be the same as translation milestone event?

---

*[zanata-war/src/main/java/org/zanata/action/ProjectHome.java, line 1152 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRQyVeM5hx7TEENC4U_:-KRX2ItZZPIK3YxwXWhh:bepa65r) ([raw file](https://github.com/zanata/zanata-server/blob/6b92942f34f8635e23fd41aa27e1a2157132459f/zanata-war/src/main/java/org/zanata/action/ProjectHome.java#L1152)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> We may need a hibernate validator for this. If two maintainer are trying to add the same webhook at the same time, I think there is a chance they are able to both enter the duplicate url and save it. Check slug Unique validator for reference.
</details>
This is still an issue. Will @Unique(properties = {"url", "project"}) on WebHook work?

---

*[zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java, line 11 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRX-whdGC9VIWrXNGgl:-KRX-whdGC9VIWrXNGgm:by2t6mq) ([raw file](https://github.com/zanata/zanata-server/blob/fe5350b9f410f4d95bf444303642fe9cabf6aea5/zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java#L11)):*
> ```Java
> @Named("webHookDAO")
> @RequestScoped
> public class WebHookDAO extends AbstractDAOImpl<WebHook, Long> {
> ```

It doesn't look like we need this class anymore. It has no method of its own. You can just inject EntityManager directly for look up by id.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java, line 11 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRX-whdGC9VIWrXNGgl:-KRbKj-qheTaJk3YZ6aI:b-rwr6pq) ([raw file](https://github.com/zanata/zanata-server/blob/fe5350b9f410f4d95bf444303642fe9cabf6aea5/zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java#L11)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> It doesn't look like we need this class anymore. It has no method of its own. You can just inject EntityManager directly for look up by id.
</details>
I still prefer to have an enitity DAO for persist. What do you think? 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 6 of 6 files at r4.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java, line 11 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-KRX-whdGC9VIWrXNGgl:-KRbUTrtZupJb-vAFZg1:b-7cdhx7) ([raw file](https://github.com/zanata/zanata-server/blob/fe5350b9f410f4d95bf444303642fe9cabf6aea5/zanata-war/src/main/java/org/zanata/dao/WebHookDAO.java#L11)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> I still prefer to have an enitity DAO for persist. What do you think? 
</details>
I am fine with that. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-:-KRbUZXTfD7RyFmI6tbP:b49ms4)*

**Comment by huangp** [comment]
-(On QA) -Reviewed  

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-:-KRbV8LRsPIKyWErRN6E:bhurr0u)*

**Comment by huangp** [comment]
+(Under review) One last thing, we need to create a unique constraint on database to match what's in hibernate entity. So a unique constraint for (url, project) in WebHook table.

---

Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-:-KRbVELgx158YbhubsNj:b-bfvaoo)*

**Comment by huangp** [comment]
-(Under review) +Reviewed +(On QA) 

---

Reviewed 12 of 12 files at r5.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-:-KRfUEPNgh5tz6bPv7SS:b-jx885m)*

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1286#-:-KS480XpYsLOCoasFKQB:bnfp4nl)*

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
Test failures:
Error Message

HV000064: Unable to instantiate ConstraintValidator: class org.zanata.model.validator.UniqueValidator.

Stacktrace

javax.validation.ValidationException: HV000064: Unable to instantiate ConstraintValidator: class org.zanata.model.validator.UniqueValidator.
	at org.zanata.search.FilterConstraintToQueryJpaTest.setUpData(FilterConstraintToQueryJpaTest.java:138)
Caused by: java.lang.InstantiationException: org.zanata.model.validator.UniqueValidator
	at org.zanata.search.FilterConstraintToQueryJpaTest.setUpData(FilterConstraintToQueryJpaTest.java:138)
Caused by: java.lang.NoSuchMethodException: org.zanata.model.validator.UniqueValidator.<init>()
	at org.zanata.search.FilterConstraintToQueryJpaTest.setUpData(FilterConstraintToQueryJpaTest.java:138)

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: tested

**Pull request merged**
