### PR TITLE
fix(glossary): Fix glossary permission

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-615

### CODE REVIEW

**Comment by djansen-redhat** [comment]
This change appears to fix the problem, however a test is failing.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
This PR has passed the tests, but seems there was a comms failure for the report.

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Pull request merged**
