### PR TITLE
ZANATA-8 fix error uploading pot file from web UI

### PR DESCRIPTION
**Pull request by huangp**
fileType in uploadForm is now DocumentType.
https://zanata.atlassian.net/browse/ZANATA-8

- [ ] backport to release once verified

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/881" target="_blank">ReviewNinja

**Comment by aeng** [comment]
:+1: , quick and simple.

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by huangp** [comment]
backported to release branch

**Comment by seanf** [comment]
Apparently backported in https://github.com/zanata/zanata-server/commit/4726e0ee4a890323f606d8cb088f093a239198a5

**Pull request merged**
