### PR TITLE
rhbz1235495,ZANATA-20 - fix error in uploading po file from web UI

### PR DESCRIPTION
**Pull request by huangp**
https://bugzilla.redhat.com/show_bug.cgi?id=1235495

- [ ] backport to release

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:+1: Looks fine to me.
:white_check_mark: Tested.

**Comment by aeng** [comment]
Need to fix the built.

**Comment by huangp** [comment]
@zanata-jenkins retest this please

**Comment by huangp** [comment]
backported to release in 4c7934b

**Pull request merged**
