### PR TITLE
Remove Hibernate module for WildFly

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1203

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1222)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
Reviewed 13 of 13 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[zanata-overlay/build.gradle, line 68 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1222#-KLKQvbqOjLx0j1jYti0:-KLKQvbrdvkUbkGgiWHc:2056541716) ([raw file](https://github.com/zanata/zanata-server/blob/05a0b4f1dd5e9d6abacca63bad8490112223dcb9/zanata-overlay/build.gradle#L68)):*
> ```Gradle
>         }
>         // Download remote dependencies
>         downloadRemoteDeps(distro, distroDir)
> ```

We might want to keep this, in case there are ever other remote dependencies which need to be added. It would just not do much at the moment.

---

*[zanata-overlay/build.gradle, line 109 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1222#-KLK_YmmYf7eZpO0aTMA:-KLK_YmmYf7eZpO0aTMB:721328965) ([raw file](https://github.com/zanata/zanata-server/blob/05a0b4f1dd5e9d6abacca63bad8490112223dcb9/zanata-overlay/build.gradle#L109)):*
> ```Gradle
> }
> 
> def downloadRemoteDeps(String distro, String distroDir) {
> ```

Same comment as above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1222)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[zanata-overlay/build.gradle, line 68 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1222#-KLKQvbqOjLx0j1jYti0:-KLOVHXvFN-8P3vtkjpm:-883243575) ([raw file](https://github.com/zanata/zanata-server/blob/05a0b4f1dd5e9d6abacca63bad8490112223dcb9/zanata-overlay/build.gradle#L68)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> We might want to keep this, in case there are ever other remote dependencies which need to be added. It would just not do much at the moment.
</details>
Well... YAGNI. And KISS.

I'll see if I can bring back enough of it to make it (somewhat) clear how to use this feature, without having it actually download anything.

But do we think we'll use modules again anytime soon, or will we just be expending effort maintaining a function which won't be used for a couple of years, if ever?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1222)*

**Comment by carlosmunoz** [comment]
:lgtm:
+Reviewed

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[zanata-overlay/build.gradle, line 68 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1222#-KLKQvbqOjLx0j1jYti0:-KLOcI4T4SvTN-HTBvUy:-1431683331) ([raw file](https://github.com/zanata/zanata-server/blob/05a0b4f1dd5e9d6abacca63bad8490112223dcb9/zanata-overlay/build.gradle#L68)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Well... YAGNI. And KISS.
> 
> I'll see if I can bring back enough of it to make it (somewhat) clear how to use this feature, without having it actually download anything.
> 
> But do we think we'll use modules again anytime soon, or will we just be expending effort maintaining a function which won't be used for a couple of years, if ever?
</details>
Well, it's already there, so it's not like we're going to waste time developing it. And it's also in history. So you make the call. I might have a feeling this will evolve even further perhaps with docker or swarm.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1222#-:-KLOd0N4rRzxTfIE5bhn:-489062391)*

**Comment by seanf** [comment]
@carlosmunoz I've made a few documentation/comment changes. I've also brought back the wildfly module download (in overlay) as an example in comments. 

But if we want to download wildfly modules for Maven tests in future, we'll just have to refer to the git history for pom.xml. I really don't want to maintain those bits unless we need them.

**Comment by carlosmunoz** [comment]
:lgtm:
-(Awaiting review) +Reviewed 

---

Reviewed 4 of 7 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1222#-:-KLPBM1gDBWcQFp-wX4R:-1149335731)*

**Comment by seanf** [comment]
Notes for QA:

Functional tests and production builds no longer have a JDBC wrapper active: a debugging wrapper which does (and did) its very best to be inert when mysql is in use.

Also, as described in the release notes, the hibernate module for wildfly is no longer needed, nor is it installed by zanata-overlay.

**Comment by djansen-redhat** [comment]
:white_check_mark: This seems to be working as intended

**Comment by seanf** [comment]
Note: I had to revert these changes for now, because they break Arquillian tests (and thus the build) on WildFly.

**Pull request merged**
