### PR TITLE
fix: add rich: namespace explicitly

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-674

### CODE REVIEW

**Comment by seanf** [comment]
@carlosmunoz This workaround isn't really needed, as long as the Mojarra 2.1 modules are activated correctly in WildFly (https://zanata.atlassian.net/browse/ZNTA-674?focusedCommentId=13118&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-13118).

However, do you think we should make the change anyway?  It wouldn't hurt to be a bit more compatible with Mojarra 2.2, even if we don't plan to use it yet.

**Comment by carlosmunoz** [comment]
@seanf As long as it doesn't break anything, I don't see a problem with this change.
:+1:

**Comment by djansen-redhat** [comment]
The failure for build 4402 can be ignored.

**Comment by seanf** [comment]
Commit e348ace merged to integration/master.  I don't think we need this in release after all.

**Pull request closed without merging**
