### PR TITLE
Get a list of contributors for a Project version via the API

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-742

https://github.com/zanata/zanata-api/pull/38

### CODE REVIEW

**Comment by huangp** [comment]
:+1: I guess this depends on that API change

**Comment by aeng** [comment]
Yup, I will be building the war for QA.

**Comment by djansen-redhat** [comment]
- [ ] "imageUrl" attribute appears to be missing the http: string (starts at //)
- [ ] "loggedIn" attribute is ambiguous

**Comment by aeng** [comment]
`"imageUrl" attribute appears to be missing the http: string (starts at //)` - Thats the valid way to handle http or https depending on the client (browser)

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/d83afe34155ad0d0b20188a51d83561bbfbdd078

**Pull request closed without merging**
