### PR TITLE
refactor: replace jndi config with system properties

### PR DESCRIPTION
**Pull request by carlosmunoz**
Use system properties instead of JNDI bindings for configuration. This should allow for set configuration in the standalone.xml file as well as overriding properties from the command line.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1171)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
Review for this PR is at the original (incorrectly merged, and then backed out) PR #1152

**Comment by anipeter** [comment]
* Verified on build 5880
* Server successfully running with new property changes in standalone-zanata.xml
    <system-properties>
        <property name="javamelody.storage-directory" value="${user.home}/zanata/stats"/>
        <property name="hibernate.search.default.indexBase" value="${user.home}/zanata/indexes"/>
        <property name="ehcache.disk.store.dir" value="${user.home}/zanata/ehcache"/>
        <property name="jboss.as.management.blocking.timeout" value="1000"/>
        <property name="zanata.security.adminusers" value="admin"/>
        <property name="zanata.security.authpolicy.internal" value="zanata.internal"/>
        <property name="zanata.security.authpolicy.openid" value="zanata.openid"/>
        <property name="zanata.email.defaultfromaddress" value="no-reply@zanata.org"/>
        <property name="zanata.files.directory" value="${user.home}/zanata/files"/>
    </system-properties>
* Tested properties : admin user, internal & openid login auth, default email address

**Comment by carlosmunoz** [comment]
Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1171)*

**Comment by carlosmunoz** [comment]
Marking this as reviewed, as per the previously closed PR.

<details><summary><i>Previously, anipeter wrote…</i></summary>
> * Verified on build 5880
> 
> * Server successfully running with new property changes in standalone-zanata.xml
> 
>     <system-properties>
> 
>         <property name="javamelody.storage-directory" value="${user.home}/zanata/stats"/>
> 
>         <property name="hibernate.search.default.indexBase" value="${user.home}/zanata/indexes"/>
> 
>         <property name="ehcache.disk.store.dir" value="${user.home}/zanata/ehcache"/>
> 
>         <property name="jboss.as.management.blocking.timeout" value="1000"/>
> 
>         <property name="zanata.security.adminusers" value="admin"/>
> 
>         <property name="zanata.security.authpolicy.internal" value="zanata.internal"/>
> 
>         <property name="zanata.security.authpolicy.openid" value="zanata.openid"/>
> 
>         <property name="zanata.email.defaultfromaddress" value="no-reply@zanata.org"/>
> 
>         <property name="zanata.files.directory" value="${user.home}/zanata/files"/>
> 
>     </system-properties>
> 
> * Tested properties : admin user, internal & openid login auth, default email address
</details>


---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1171#-:-KI4sWTEOD8BEp57p6it:1838790331)*

**Comment by aeng** [comment]
Related Jira - https://zanata.atlassian.net/browse/ZNTA-1045

**Pull request merged**
