### PR TITLE
feat: add docker development images

### PR DESCRIPTION
**Pull request by carlosmunoz**
Add images, Dockerfile, scripts and documentation to be able to quickly run docker containers for Zanata development.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1211)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
This pull request replaces PR #1204 which has already been reviewed.

**Comment by carlosmunoz** [comment]
Also, please note this setup has problems on MacOS with boot2docker, perhaps because of this issue: https://github.com/boot2docker/boot2docker/issues/581

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-:-KKR-1IBRVG01px_gBQK:1417088721)*

**Comment by definite** [comment]
Reviewed 5 of 7 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

*[docker/Dockerfile, line 23 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKffs0OwCPnzccVSiR5:-KKffs0OwCPnzccVSiR6:-1114848660) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/Dockerfile#L23)):*
> ```Dockerfile
> 
> # standalone.xml (not needed for dev)
> # ADD conf/standalone.xml /opt/jboss/wildfly/standalone/configuration/
> ```

I would suggest to uncomment the ADD, unless we want to run `chcon -Rt svirt_sandbox_file_t conf` whenever we clone zanata-server 

---

*[docker/rundb.sh, line 8 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfhgWKWMidEn0lJ03S:-KKfhgWLmqCPzpAFal1q:907317703) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundb.sh#L8)):*
> ```Shell
> DB_SCHEMA=zanata
> DB_ROOT_PASSWORD=rootpw
> ```

Please insert following two lines before running docker:

```sh
mkdir -p $HOME/docker-volumes/zanata-mariadb
sudo chcon -Rt   svirt_sandbox_file_t  $HOME/docker-volumes/zanata-mariadb
```

Otherwise we got `permission deny`

---

*[docker/rundev.sh, line 14 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfivOBl9bNcWT04iSj:-KKfivOBl9bNcWT04iSk:-1827551626) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L14)):*
> ```Shell
> # change to top of the git working directory
> cd $DIR/../
> ZANATA_WAR=$(echo $PWD/zanata-war/target/zanata-*.war)
> ```

It is possible that multiple zanata-*.war in this directory: (e.g. zanata-war-3.9.1-SNAPSHOT.war, zanata-war-4.0.0-SNAPSHOT.war) 
This will lead error in later steps. (e.g.      -v $ZANATA_WAR:/opt/jboss/wildfly/standalone/deployments/ROOT.war)

Please also run
```
sudo chcon -Rt svirt_sandbox_file_t $ZANATA_WAR
```
to ensure the WAR files have correct SELinux  label

---

*[docker/rundev.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfjhVj_3ZEy0IQVQ2A:-KKfjhVj_3ZEy0IQVQ2B:-1338776465) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L20)):*
> ```Shell
> # chown -R 1000:1000 $ZANATA_DIR
> # make zanata directory accessible to docker containers (SELinux)
> chcon -Rt svirt_sandbox_file_t $ZANATA_DIR
> ```

`sudo chcon` is needed here. It make no sense to run chcon as normal user

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/Dockerfile, line 23 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKffs0OwCPnzccVSiR5:-KKfvMHmhwI9NHg7te9Y:-1016140973) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/Dockerfile#L23)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>
> I would suggest to uncomment the ADD, unless we want to run `chcon -Rt svirt_sandbox_file_t conf` whenever we clone zanata-server 
</details>
We probably should use `ADD`, but we've also got the option of  doing the `chcon` in `rundev.sh`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/Dockerfile, line 23 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKffs0OwCPnzccVSiR5:-KKgAcXZoYfMirJcJmsU:-241357126) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/Dockerfile#L23)):*
> doing the chcon in rundev.sh.

Should allow changes in standalone.xml to show up faster, eg when restarting an existing container.

---

*[docker/rundb.sh, line 8 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfhgWKWMidEn0lJ03S:-KKg6aHuoamTaaSagIZJ:-384334192) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundb.sh#L8)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>
> Please insert following two lines before running docker:
> 
> ```sh
> mkdir -p $HOME/docker-volumes/zanata-mariadb
> sudo chcon -Rt   svirt_sandbox_file_t  $HOME/docker-volumes/zanata-mariadb
> ```
> 
> Otherwise we got `permission deny`
</details>
Perhaps instead of changing the developer's security settings and requiring sudo in this script, I think it would be safer just to check the SELinux context, and tell the developer to run the above commands if problems arise.

Setting the context should only be needed once (per volume), when the volume directory is first created.

@definite, do you know how we could check the label (recursively)?

---

*[docker/rundev.sh, line 14 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfivOBl9bNcWT04iSj:-KKg8K1ITzjPmqeQNLKl:-1943920450) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L14)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>
> It is possible that multiple zanata-*.war in this directory: (e.g. zanata-war-3.9.1-SNAPSHOT.war, zanata-war-4.0.0-SNAPSHOT.war) 
> This will lead error in later steps. (e.g.      -v $ZANATA_WAR:/opt/jboss/wildfly/standalone/deployments/ROOT.war)
> 
> Please also run
> ```
> sudo chcon -Rt svirt_sandbox_file_t $ZANATA_WAR
> ```
> to ensure the WAR files have correct SELinux  label
</details>
Yes, I suppose we should check for multiple .war files, to save trouble in later steps.

With the `chcon` command, we probably need to set the context for standalone.xml as well.

We should output warning whenever we set the security context.

---

*[docker/rundev.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfjhVj_3ZEy0IQVQ2A:-KKgAFm-O9PX9DaoHsqF:-2057068813) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L20)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>
> `sudo chcon` is needed here. It make no sense to run chcon as normal user
</details>
I seem to able to run `chcon` without `sudo`, switching between:

    chcon -Rt home_root_t $ZANATA_DIR

and

    chcon -Rt svirt_sandbox_file_t $ZANATA_DIR

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by carlosmunoz** [comment]
Review status: 4 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/Dockerfile, line 23 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKffs0OwCPnzccVSiR5:-KKgEcmo9mYydBexbfeZ:1581859429) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/Dockerfile#L23)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> > doing the chcon in rundev.sh.
> 
> Should allow changes in standalone.xml to show up faster, eg when restarting an existing container.
</details>
So we decided to bring back the ADD as the image is being rebuilt every time the script runs. The overhead to add the standalone.xml file when it hasn't changed should be negligible.

---

*[docker/rundb.sh, line 8 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfhgWKWMidEn0lJ03S:-KKhEtZHEy0iNdHxElGu:1223658679) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundb.sh#L8)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Perhaps instead of changing the developer's security settings and requiring sudo in this script, I think it would be safer just to check the SELinux context, and tell the developer to run the above commands if problems arise.
> 
> Setting the context should only be needed once (per volume), when the volume directory is first created.
> 
> @definite, do you know how we could check the label (recursively)?
</details>
Done. The only part we didn't seem to need was the sudo before `chcon`

---

*[docker/rundev.sh, line 14 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfivOBl9bNcWT04iSj:-KKhF8JGCHxBQzb8WNtj:2065660069) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L14)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Yes, I suppose we should check for multiple .war files, to save trouble in later steps.
> 
> With the `chcon` command, we probably need to set the context for standalone.xml as well.
> 
> We should output warning whenever we set the security context.
</details>
Done for the `chcon` command. The check for multiple .war files will be left for later.

---

*[docker/rundev.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfjhVj_3ZEy0IQVQ2A:-KKhFLzYAv6gz42bZ4_a:-185629321) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L20)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I seem to able to run `chcon` without `sudo`, switching between:
> 
>     chcon -Rt home_root_t $ZANATA_DIR
> 
> and
> 
>     chcon -Rt svirt_sandbox_file_t $ZANATA_DIR
> 
</details>
Like @seanf said, I didn't need `sudo` here either.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by definite** [comment]
Reviewed 2 of 7 files at r1, 1 of 3 files at r2.
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/rundb.sh, line 8 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfhgWKWMidEn0lJ03S:-KKkY4CeqaM5IwXWJL8n:-606823575) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundb.sh#L8)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> Done. The only part we didn't seem to need was the sudo before `chcon`
</details>
Without the  first `mkdir -p $HOME/docker-volumes/zanata-mariadb`, in my machine, it would create the said directory as root:root with permission `drwxr-xr-x` , thus permission deny.

@seanf `ls -lRZ <dir>` should do.

---

*[docker/rundev.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfjhVj_3ZEy0IQVQ2A:-KKkZ1UjAfGqFXregFuU:-75978966) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L20)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> Like @seanf said, I didn't need `sudo` here either.
</details>
Mmm, perhaps that is because I run the staff SELinux mode ( http://blog.bodhizazen.net/linux/selinux-and-confined-users/ )

Perhaps I need to work around this myself.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by carlosmunoz** [comment]
Review status: 5 of 7 files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/rundb.sh, line 8 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfhgWKWMidEn0lJ03S:-KKkabDPhIAkMrwMlFks:-1315840913) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundb.sh#L8)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>
> Without the  first `mkdir -p $HOME/docker-volumes/zanata-mariadb`, in my machine, it would create the said directory as root:root with permission `drwxr-xr-x` , thus permission deny.
> 
> @seanf `ls -lRZ <dir>` should do.
</details>
Yes it does this on mine too. So is your concern only about calling that mkdir beforehand? if so, I think I don't have a problem with that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by definite** [comment]
Reviewed 2 of 3 files at r2.
Review status: 6 of 7 files reviewed at latest revision, 5 unresolved discussions.

---

*[docker/rundev.sh, line 18 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKlzN8uCtR0fgG2zAd-:-KKlzN8uCtR0fgG2zAd0:-798946926) ([raw file](https://github.com/zanata/zanata-server/blob/02a1d926b0da46ba5ff42d49176882bee78d011b/docker/rundev.sh#L18)):*
> ```Shell
> ZANATA_DIR=$HOME/docker-volumes/zanata
> # create the data directory and set permissions (SELinux)
> mkdir $ZANATA_DIR && chcon -Rt svirt_sandbox_file_t "$ZANATA_DIR"
> ```

Please add `-p` to mkdir like `mkdir -p $ZANATA_DIR`, so it will create the whole path without questioning, and it won't fail if  `$ZANATA_DIR` already exists.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by definite** [comment]
:+1:

**Comment by definite** [comment]
Reviewed 1 of 1 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docker/Dockerfile, line 23 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKffs0OwCPnzccVSiR5:-KKq6UBaARuMhpEz6rYn:676834233) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/Dockerfile#L23)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> So we decided to bring back the ADD as the image is being rebuilt every time the script runs. The overhead to add the standalone.xml file when it hasn't changed should be negligible.
</details>
LGTM

---

*[docker/rundb.sh, line 8 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfhgWKWMidEn0lJ03S:-KKq6WSTKV5ThJnnswKB:676834233) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundb.sh#L8)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> Yes it does this on mine too. So is your concern only about calling that mkdir beforehand? if so, I think I don't have a problem with that.
</details>
LGTM

---

*[docker/rundev.sh, line 14 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfivOBl9bNcWT04iSj:-KKq6g8tzX9AM3VLTQj8:676834233) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L14)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> Done for the `chcon` command. The check for multiple .war files will be left for later.
</details>
LGTM

---

*[docker/rundev.sh, line 20 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfjhVj_3ZEy0IQVQ2A:-KKq6_2TV22hmsLlEoTU:676834233) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L20)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>
> Mmm, perhaps that is because I run the staff SELinux mode ( http://blog.bodhizazen.net/linux/selinux-and-confined-users/ )
> 
> Perhaps I need to work around this myself.
</details>
LGTM

---

*[docker/rundev.sh, line 18 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKlzN8uCtR0fgG2zAd-:-KKq6YNLcZRNwsOQ0eeL:676834233) ([raw file](https://github.com/zanata/zanata-server/blob/02a1d926b0da46ba5ff42d49176882bee78d011b/docker/rundev.sh#L18)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>
> Please add `-p` to mkdir like `mkdir -p $ZANATA_DIR`, so it will create the whole path without questioning, and it won't fail if  `$ZANATA_DIR` already exists.
</details>
LGTM

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[docker/rundev.sh, line 14 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1211#-KKfivOBl9bNcWT04iSj:-KKq6uZkWeTvd-rMjQyS:980077423) ([raw file](https://github.com/zanata/zanata-server/blob/b5618076bc9df8d36c8e074705bc1188f908a699/docker/rundev.sh#L14)):*
<details><summary><i>Previously, definite (Ding-Yi Chen) wrote…</i></summary>
> LGTM
</details>
:lgtm: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1211)*

**Pull request merged**
