### PR TITLE
fix(editor history): reset view when editor history shows

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1384

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1289)

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:x: There are waaaaaaaaaaay too many commits in here to be valid. Check you haven't based from / rebased on master.

**Comment by aeng** [comment]
@djansen-redhat My bad. Fixed the crazy PR.

**Comment by djansen-redhat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1289)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested
:shipit: no rogue commits

**Pull request merged**
