### PR TITLE
Update to WildFly 9.0.0.CR1

### PR DESCRIPTION
**Pull request by seanf**
Disable jsessionid tracking to fix WildFly 9 problem: specifically, the problem where clicking "login" tries to take you to the login form, but with an appended jsessionid parameter, which leads to a 404.

https://bugzilla.redhat.com/show_bug.cgi?id=1197955

### CODE REVIEW

**Comment by carlosmunoz** [comment]
Looks good :+1:

**Comment by seanf** [comment]
Thanks for pinpointing the problem!

**Comment by djansen-redhat** [comment]
Why is this in release when we don't officially support Wildfly 9?

**Comment by carlosmunoz** [comment]
I'll let @seanf answer that question, but in any case this should not break Wildfly 8 or EAP.

**Comment by djansen-redhat** [comment]
With the understanding that the site basically "doesn't run" on WF9,
:white_check_mark: Tested

**Comment by djansen-redhat** [comment]
:eyes: eyeballed this, but mostly tested by CI.
:white_check_mark:

**Comment by djansen-redhat** [comment]
Reviewed e7d22c2

**Comment by seanf** [comment]
Just running the full functional tests again to be safe.

**Comment by seanf** [comment]
Full functional tests passed on 9.0 CR1.

@djansen-redhat Do you want to do anything more with this now that it's using 9.0.0.CR1 instead of 9.0 beta?

**Comment by seanf** [comment]
@carlosmunoz do you want to look at the zanata-overlay changes?

**Comment by carlosmunoz** [comment]
@seanf No issues here.

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
See also https://github.com/zanata/zanata-server/pull/799#issuecomment-100116076

**Comment by seanf** [comment]
@djansen-redhat This should have more sensible startup messages for WildFly 9 now.

**Comment by djansen-redhat** [comment]
I'm fine with this, go for it.

**Comment by seanf** [comment]
Squash-merged as 485f1b5.

**Pull request closed without merging**
