### PR TITLE
Clean for l10n validate

### PR DESCRIPTION
**Pull request by seanf**
You can run validation with this command:

    mvn -q com.googlecode.l10n-maven-plugin:l10n-maven-plugin:1.8:validate -pl zanata-war

 - [ ] Once this has been merged, we should run `mvn -q l10n:validate` for all pull requests and `integration/master` builds.

### CODE REVIEW

**Comment by seanf** [comment]
- [ ] Once this has been merged, we should run `mvn -q l10n:validate` for all pull requests.

**Comment by aeng** [comment]
:+1:

**Comment by seanf** [comment]
One functional test timed out.  Waiting for #777 to go in before retesting.

**Comment by seanf** [comment]
With #777, all functional tests passed.

**Comment by djansen-redhat** [comment]
> You can run validation with this command...

I expect that the response is supposed to be empty?
:white_check_mark: Tested

**Pull request merged**
