### PR TITLE
Ignore slow tests

### PR DESCRIPTION
**Pull request by seanf**
`@SlowTest` is currently not handled by our JUnit setup, so we have to `@Ignore` such tests, at least for now.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/867" target="_blank">ReviewNinja

**Comment by carlosmunoz** [comment]
@seanf Why did we need this change? `@SlowTest` was only a marker annotation as far as I know, and it wasn't being handled in any special way.

**Comment by seanf** [comment]
@carlosmunoz If we were already running these tests, then the TestNG :arrow_right: JUnit slowdown must be unrelated, but as we hadn't intended to run the slow tests, I think it still makes sense to ignore them.

**Comment by carlosmunoz** [comment]
Mmm... again, not sure if were in fact not intending to run these tests. 

I'm fine with the pull request in terms of code review, just not sure that we want to ignore the slow tests.

**Comment by seanf** [comment]
> I'm fine with the pull request in terms of code review, just not sure that we want to ignore the slow tests.

?? Not sure I understand.  How can you be happy with the code review if you think the change itself is a mistake?


Anyway, `CopyTransServiceImplTest.testCopyTrans` is the only SlowTest which wasn't already Ignored.  And it turns out it's not that slow (by our *terrible* standards), because it runs all four combinations (some tests have dozens) in two seconds total.

So I'm going to remove that particular `@Ignore`, but I think I'll keep this PR open while I try to optimise some of the slower tests (including parameterised tests).

**Comment by carlosmunoz** [comment]
> ?? Not sure I understand. How can you be happy with the code review if you think the change itself is a mistake?

I don't see any issues with the code itself if our intention is to ignore these tests for any reason (I trust your judgement on that). Personally I don't see such reason, but these days you are closer to the code than I am.

> Anyway, CopyTransServiceImplTest.testCopyTrans is the only SlowTest which wasn't already Ignored. And it turns out it's not that slow (by our terrible standards), because it runs all four combinations (some tests have dozens) in two seconds total.

> So I'm going to remove that particular @Ignore, but I think I'll keep this PR open while I try to optimise some of the slower tests (including parameterised tests).

Sounds like a plan.

**Comment by seanf** [comment]
Running into a lot of intermittent tests, but the build is finally green.  @carlosmunoz I assume you're happy with the last commit?

**Comment by seanf** [comment]
@carlosmunoz Could you please take another look at this PR?

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by carlosmunoz** [comment]
:+1: Reviewed.
A couple of ignored tests due to them being more on the "performance profiling" category.

**Comment by seanf** [comment]
(Rebased on top of `master`.)

**Pull request merged**
