### PR TITLE
ZNTA-1290 - manually triggered webhook

### PR DESCRIPTION
**Pull request by huangp**
JIRA issue URL: *[https://zanata.atlassian.net/browse/ZNTA-1290]*

*Can create a webhook and trigger it manually*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1312)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 14 of 18 files at r1.
Review status: 14 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-model/src/main/java/org/zanata/model/type/WebhookType.java, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-KTN5d6vsYJcoLeWDifR:-KTN5d6vsYJcoLeWDifS:bngnky6) ([raw file](https://github.com/zanata/zanata-server/blob/9c23440c41a8721d5bc12c11406eb3f464caebca/zanata-model/src/main/java/org/zanata/model/type/WebhookType.java#L18)):*
> ```Java
>     ProjectMaintainerChangedEvent("Project maintainer update"),
>     SourceDocumentChangedEvent("Document"),
>     ManuallyTriggeredEvent("Manual event")
> ```

Can we have more meaningful name for this webhook?

---

*[zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java, line 351 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-KTN7gj6KfwBGoiN95bM:-KTN7gj6KfwBGoiN95bN:bx0wajp) ([raw file](https://github.com/zanata/zanata-server/blob/9c23440c41a8721d5bc12c11406eb3f464caebca/zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java#L351)):*
> ```Java
> 
>     public void triggerManualWebhookEvent() {
>         List<WebHook> webHooks = webHookDAO.getWebHooksForType(projectSlug,
> ```

Can we cached webhooks in the bean? and reuse it for these 3 methods.

---

*[zanata-war/src/main/java/org/zanata/service/impl/WebhookServiceImpl.java, line 60 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-KTN6s5j6JWf6c-7wD-o:-KTN6s5j6JWf6c-7wD-p:b-qxldac) ([raw file](https://github.com/zanata/zanata-server/blob/9c23440c41a8721d5bc12c11406eb3f464caebca/zanata-war/src/main/java/org/zanata/service/impl/WebhookServiceImpl.java#L60)):*
> ```Java
>     @Inject
>     @Authenticated
>     private HAccount authenticatedUser;
> ```

Remove this if it is not used?

---

*[zanata-war/src/main/java/org/zanata/webhook/events/ManuallyTriggeredEvent.java, line 31 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-KTN6yq1zcy20QypDSKF:-KTN6yq1zcy20QypDSKG:bt27ug9) ([raw file](https://github.com/zanata/zanata-server/blob/9c23440c41a8721d5bc12c11406eb3f464caebca/zanata-war/src/main/java/org/zanata/webhook/events/ManuallyTriggeredEvent.java#L31)):*
> ```Java
> 
> /**
>  * Indicates an event triggered by a user.
> ```

Need more explaination for this event and what it is used for.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1312)*

**Comment by huangp** [comment]
Review status: 14 of 18 files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-model/src/main/java/org/zanata/model/type/WebhookType.java, line 18 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-KTN5d6vsYJcoLeWDifR:-KTN9Dz5UufVtmHB8HqE:b-fuhy7g) ([raw file](https://github.com/zanata/zanata-server/blob/9c23440c41a8721d5bc12c11406eb3f464caebca/zanata-model/src/main/java/org/zanata/model/type/WebhookType.java#L18)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Can we have more meaningful name for this webhook?
</details>
That's what it is. User can trigger it with and without anything change in Zanata.

---

*[zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java, line 351 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-KTN7gj6KfwBGoiN95bM:-KTNIEdmDQUcBb7S4FPP:b-7rl0jd) ([raw file](https://github.com/zanata/zanata-server/blob/9c23440c41a8721d5bc12c11406eb3f464caebca/zanata-war/src/main/java/org/zanata/action/VersionHomeAction.java#L351)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Can we cached webhooks in the bean? and reuse it for these 3 methods.
</details>
done.

---

*[zanata-war/src/main/java/org/zanata/service/impl/WebhookServiceImpl.java, line 60 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-KTN6s5j6JWf6c-7wD-o:-KTNIOa_pSnLwLOUzEiU:bta9wly) ([raw file](https://github.com/zanata/zanata-server/blob/9c23440c41a8721d5bc12c11406eb3f464caebca/zanata-war/src/main/java/org/zanata/service/impl/WebhookServiceImpl.java#L60)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Remove this if it is not used?
</details>
It is used for manually triggered event.

---

*[zanata-war/src/main/java/org/zanata/webhook/events/ManuallyTriggeredEvent.java, line 31 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-KTN6yq1zcy20QypDSKF:-KTNJHgkMfU48v1okmL-:b-896fix) ([raw file](https://github.com/zanata/zanata-server/blob/9c23440c41a8721d5bc12c11406eb3f464caebca/zanata-war/src/main/java/org/zanata/webhook/events/ManuallyTriggeredEvent.java#L31)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Need more explaination for this event and what it is used for.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1312)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 18 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1312#-:-KTQkJV9vxJetWiVuybn:bnfp4nl)*

**Comment by djansen-redhat** [comment]
- [ ] Webhook name field limit too high (wouldn't 15 be enough?)
- [ ] I couldn't break it, but I _feel_ that allowing special characters that will eventuate as part of a page is risky
- [ ] You can name them separately, but not execute them separately - intended?

**Comment by seanf** [comment]
The longer the webhook name, or the more webhook names, the wider the overflow menu is going to be. It's already a bit too wide, I think. 

If the manual webhook button were not part of an overflow menu, but moved to a normal button, it would be easier for users to find, and it could be labelled "Trigger manual WebHook" or similar, with the user-configured names shown in a tooltip (where they can't mess up the page layout).

**Comment by huangp** [comment]
As we discussed in the retrospective and planning meeting, we will stash the webhook name change and continue with the original requirement (no name and generic option name from the dropdown). This new feature can be done separately and preferably after the new project/version page.

**Comment by huangp** [comment]
@djansen-redhat 
Webhook name field limit too high (wouldn't 15 be enough?)
 - changed to 20

I couldn't break it, but I feel that allowing special characters that will eventuate as part of a page is risky
 - remove it from the dropdown option

You can name them separately, but not execute them separately - intended?
- At the moment all webhooks are fired together

Whitespace can be saved as webhook name, results in "Trigger , otherHook for zh-Hant" as option
- name no longer appear in option

Should have a Zanata url identifier in the body?
- done

Webhook Name in the body?
- webhook name is only used for Zanata users. Should not matter for the webhook receiver.

WebHooks list should show name, if set, instead of hook url
- done

**Comment by djansen-redhat** [comment]
Couple more points:
- [ ] No notification message on webhook sent
- [ ] Webhook with empty name shows a 1 character width panel

It currently shows both name and URL, despite the comment above, though this is OK.

**Comment by huangp** [comment]
Because all the webhooks are sent asynchronously and we don't have a global notification system yet. There is no reliable way to show a notification. I can only display a message after the click saying the request is sent (but whether it actually is sent and received is unknown).
Second point is done.

**Comment by djansen-redhat** [comment]
- [ ] Make webhook notification more generic, to avoid the no-name/too-many-names/mix-of issues

**Comment by djansen-redhat** [comment]
Reviewed 9 of 18 files at r1, 3 of 5 files at r3, 3 of 5 files at r4, 1 of 3 files at r5, 2 of 2 files at r6.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1312)*

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Pull request merged**
