### PR TITLE
chore: war file included in overlay

### PR DESCRIPTION
**Pull request by carlosmunoz**
This means the war file will now be fetched from the local maven repo
first and then from maven central, or passed via a parameter.

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@seanf Please review this in hopes we can use it to create an overlay module that already has the war file in it. This prevents a double download (once for the overlay, another for the war file).
It fetches the war file from the maven local repo, and allows for the version to be passed as a parameter. This means that the war file needs to have been installed using maven beforehand.

**Comment by seanf** [comment]
Looks fine to me, as long as the storage space holds out...

**Comment by carlosmunoz** [comment]
@definite Could you have a look?

**Comment by definite** [comment]
Note that the released versions of server go to 
http://repository-zanata.forge.cloudbees.com/release/org/zanata/server/
snapshots are neither in cloudbees, nor in sonatpye.
Thus it cannot found the release versions and show error messages like

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not find org.zanata:zanata-war:3.8.1.

**Comment by carlosmunoz** [comment]
So, the build will now look for the artifact in 1. the local maven repo (which means the zanata-war artifact has to be installed before running the overlay build), and 2. Maven central.

I could add the repo mentioned above to the list of places to look for the artifact, but that still doesn't cover snapshots. (those are covered by 1.)

**Comment by definite** [comment]
Snapshot in local .m2 seems fine.

**Comment by definite** [comment]
Step to reproduce:
1. git checkout server-3.8.2
2. git merge overlay-change
3. gradle package --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':runtime'.
> Could not find org.zanata:zanata-war:3.8.2.
  Searched in the following locations:
      https://repo1.maven.org/maven2/org/zanata/zanata-war/3.8.2/zanata-war-3.8.2.pom
      https://repo1.maven.org/maven2/org/zanata/zanata-war/3.8.2/zanata-war-3.8.2.jar
      file:/home/dchen/.m2/repository/org/zanata/zanata-war/3.8.2/zanata-war-3.8.2.pom
      file:/home/dchen/.m2/repository/org/zanata/zanata-war/3.8.2/zanata-war-3.8.2.jar
  Required by:
      :zanata-overlay:unspecified

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.artifacts.ResolveException: Could not resolve all dependencies for configuration
 ':runtime'.
	at org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration.rethrowFail
ure(DefaultLenientConfiguration.java:63)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultResolvedConfiguration.rethrowFai
lure(DefaultResolvedConfiguration.java:36)
	at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyResolver$FilesAg
gregatingResolvedConfiguration.rethrowFailure(SelfResolvingDependencyResolver.java:115)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver
$ErrorHandlingResolvedConfiguration.rethrowFailure(ErrorHandlingArtifactDependencyResolver.java
:191)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationF
ileCollection.getFiles(DefaultConfiguration.java:674)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getFiles(Defau
ltConfiguration.java:284)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getF
iles(Unknown Source)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTre
eConverter.convertInto(DefaultFileCollectionResolveContext.java:194)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResol
ve(DefaultFileCollectionResolveContext.java:106)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolve
AsFileTrees(DefaultFileCollectionResolveContext.java:78)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileTre
eConverter.convertInto(DefaultFileCollectionResolveContext.java:185)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResol
ve(DefaultFileCollectionResolveContext.java:101)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolve
AsFileTrees(DefaultFileCollectionResolveContext.java:78)
	at org.gradle.api.internal.file.CompositeFileCollection$1.resolve(CompositeFileCollecti
on.java:88)
	at org.gradle.api.internal.file.CompositeFileTree$FilteredFileTree.resolve(CompositeFil
eTree.java:92)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolve
Nested(DefaultFileCollectionResolveContext.java:146)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResol
ve(DefaultFileCollectionResolveContext.java:104)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolve
AsFileCollections(DefaultFileCollectionResolveContext.java:85)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext$FileCol
lectionConverter.convertInto(DefaultFileCollectionResolveContext.java:160)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.doResol
ve(DefaultFileCollectionResolveContext.java:101)
	at org.gradle.api.internal.file.collections.DefaultFileCollectionResolveContext.resolve
AsFileCollections(DefaultFileCollectionResolveContext.java:85)
	at org.gradle.api.internal.file.CompositeFileCollection.getSourceCollections(CompositeF
ileCollection.java:144)
	at org.gradle.api.internal.file.CompositeFileCollection.isEmpty(CompositeFileCollection
.java:56)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(Ski
pEmptySourceFilesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTa
skWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTas
kExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(Execut
eAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execut
e(DefaultTaskGraphExecuter.java:208)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execut
e(DefaultTaskGraphExecuter.java:186)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTa
sk(AbstractTaskPlanExecutor.java:62)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(Abstr
actTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecut
or.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExec
uter.java:111)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction
.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.j
ava:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher$6.run(DefaultGradleLauncher.java:174
)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperation
Executor.java:62)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperation
Executor.java:47)
	at org.gradle.initialization.DefaultGradleLauncher.runBuildOperation(DefaultGradleLaunc
her.java:189)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.
java:171)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.jav
a:35)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:
104)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:
97)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperation
Executor.java:62)
	at org.gradle.initialization.DefaultGradleLauncher.runRootBuildOperation(DefaultGradleL
auncher.java:184)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:9
7)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InP
rocessBuildActionExecuter.java:93)
	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildAction
Runner.java:28)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.jav
a:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionEx
ecuter.java:43)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionEx
ecuter.java:27)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildAction
Executer.java:72)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildAction
Executer.java:44)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsag
eSuggestingBuildActionExecuter.java:50)
	at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsag
eSuggestingBuildActionExecuter.java:27)
	at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:40)
	at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:170)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(Command
LineActionFactory.java:237)
	at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(Command
LineActionFactory.java:210)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAct
ion.java:35)
	at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAct
ion.java:24)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActi
onFactory.java:206)
	at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActi
onFactory.java:169)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.ja
va:33)
	at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.ja
va:22)
	at org.gradle.launcher.Main.doAction(Main.java:33)
	at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
	at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
	at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find org.zanat
a:zanata-war:3.8.2.
Searched in the following locations:
    https://repo1.maven.org/maven2/org/zanata/zanata-war/3.8.2/zanata-war-3.8.2.pom
    https://repo1.maven.org/maven2/org/zanata/zanata-war/3.8.2/zanata-war-3.8.2.jar
    file:/home/dchen/.m2/repository/org/zanata/zanata-war/3.8.2/zanata-war-3.8.2.pom
    file:/home/dchen/.m2/repository/org/zanata/zanata-war/3.8.2/zanata-war-3.8.2.jar
Required by:
    :zanata-overlay:unspecified
	at org.gradle.internal.resolve.result.DefaultBuildableComponentResolveResult.notFound(D
efaultBuildableComponentResolveResult.java:38)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMeta
DataResolver.resolveModule(RepositoryChainComponentMetaDataResolver.java:88)
	at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.RepositoryChainComponentMeta
DataResolver.resolve(RepositoryChainComponentMetaDataResolver.java:59)
	at org.gradle.api.internal.artifacts.ivyservice.clientmodule.ClientModuleResolver.resol
ve(ClientModuleResolver.java:44)
	at org.gradle.api.internal.artifacts.ivyservice.projectmodule.ProjectDependencyResolver
.resolve(ProjectDependencyResolver.java:72)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuil
der$ModuleVersionResolveState.resolve(DependencyGraphBuilder.java:575)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuil
der$ModuleVersionResolveState.getMetaData(DependencyGraphBuilder.java:585)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuil
der$DependencyEdge.calculateTargetConfigurations(DependencyGraphBuilder.java:270)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuil
der$DependencyEdge.attachToTargetConfigurations(DependencyGraphBuilder.java:244)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuil
der.traverseGraph(DependencyGraphBuilder.java:156)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuil
der.resolveDependencyGraph(DependencyGraphBuilder.java:94)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.graph.DependencyGraphBuil
der.resolve(DependencyGraphBuilder.java:84)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver
$1.execute(DefaultDependencyResolver.java:142)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver$1.execute(DefaultDependencyResolver.java:96)
	at org.gradle.internal.Transformers$4.transform(Transformers.java:137)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:61)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultIvyContextManager.withIvy(DefaultIvyContextManager.java:39)
	at org.gradle.api.internal.artifacts.ivyservice.resolveengine.DefaultDependencyResolver.resolve(DefaultDependencyResolver.java:96)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver$1.run(CacheLockingArtifactDependencyResolver.java:42)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:192)
	at org.gradle.cache.internal.DefaultCacheAccess.useCache(DefaultCacheAccess.java:175)
	at org.gradle.cache.internal.DefaultPersistentDirectoryStore.useCache(DefaultPersistentDirectoryStore.java:106)
	at org.gradle.cache.internal.DefaultCacheFactory$ReferenceTrackingCache.useCache(DefaultCacheFactory.java:187)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultCacheLockingManager.useCache(DefaultCacheLockingManager.java:64)
	at org.gradle.api.internal.artifacts.ivyservice.CacheLockingArtifactDependencyResolver.resolve(CacheLockingArtifactDependencyResolver.java:40)
	at org.gradle.api.internal.artifacts.ivyservice.SelfResolvingDependencyResolver.resolve(SelfResolvingDependencyResolver.java:41)
	at org.gradle.api.internal.artifacts.ivyservice.ShortcircuitEmptyConfigsArtifactDependencyResolver.resolve(ShortcircuitEmptyConfigsArtifactDependencyResolver.java:56)
	at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingArtifactDependencyResolver.resolve(ErrorHandlingArtifactDependencyResolver.java:46)
	at org.gradle.api.internal.artifacts.ivyservice.DefaultConfigurationResolver.resolve(DefaultConfigurationResolver.java:45)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveGraphIfRequired(DefaultConfiguration.java:363)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.resolveNow(DefaultConfiguration.java:338)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getResolvedConfiguration(DefaultConfiguration.java:331)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getResolvedConfiguration(Unknown Source)
	at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration$ConfigurationFileCollection.getFiles(DefaultConfiguration.java:672)
	... 72 more

**Comment by djansen-redhat** [comment]
@carlosmunoz the approach in https://github.com/zanata/zanata-server/commit/5ebc7bcb5d17ad1f2421243ecd6379f78e6142fd may be better than what I submitted here

**Comment by carlosmunoz** [comment]
Closing this as it will no longer target the release branch.

**Comment by carlosmunoz** [comment]
Replaced by #1128

**Pull request closed without merging**
