### PR TITLE
Fix tests on JVM 1.8; reduce executions

### PR DESCRIPTION
**Pull request by seanf**
1. Fix JVM 1.8 incompatibility
2. Reduce unnecessary test executions

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/871" target="_blank">ReviewNinja

**Comment by seanf** [comment]
Don't bother reviewing this yet; it currently breaks the GWT compiler.

**Comment by seanf** [comment]
@davidmason I amended the last commit to move the sorting down a bit, after the lists of added vars are populated.

**Comment by seanf** [comment]
@davidmason Could you review this please?

**Comment by davidmason** [comment]
:+1: all looks good.

**Pull request merged**
