### PR TITLE
Convert language page to React

### PR DESCRIPTION
**Pull request by ghost**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-1333

API: https://github.com/zanata/zanata-api/pull/63

_[Add a short description of what is changed here.]_
## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.
- Code quality
  - [ ] Code passes style check (checkstyle/eslint)
  - [ ] Code is clear and concise
  - [ ] UI code is internationalised
  - [ ] Code has adequate comments where appropriate
  - Code is in an appropriate place
    - [ ] Classes are in appropriate packages
    - [ ] Code fits with class's responsibilities (SRP)
  - [ ] Configuration files are documented enough
  - If code is removed
    - [ ] No remaining code references the removed code
      - [ ] No orphaned rewrite rules
    - [ ] No orphaned config settings
    - [ ] No remaining comments refer to the removed code
    - [ ] Unused imports and libraries are removed
- Testing
  - [ ] New code has tests
  - [ ] Changed code has tests
  - [ ] All tests pass
  - [ ] Test coverage stable or increased
- Documentation
  - [ ] New features are documented
  - [ ] Docs removed for deleted features
  - [ ] Docs updated for all changed features
  - [ ] Developer/sysadmin docs updated if appropriate
- If there are new dependencies
  - [ ] Does each new dependency pass all the
     [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

---

_This template can be updated in .github/PULL_REQUEST_TEMPLATE.md_

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1310)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 46 of 46 files at r1.
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[zanata-frontend/src/frontend/app/actions/languages.js, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU-dQFtOEM82XEUs8W8:-KU-dQFtOEM82XEUs8W9:bs6zeue) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-frontend/src/frontend/app/actions/languages.js#L46)):*
> ```JavaScript
>   let queries = []
>   if (query.search) {
>     queries.push('filter=' + query.search)
> ```

You may want to encode the search term if it's from user input

---

*[zanata-frontend/src/frontend/app/actions/languages.js, line 85 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU-dlbto3Qlq9BQkJGi:-KU-dlbto3Qlq9BQkJGj:b-twglca) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-frontend/src/frontend/app/actions/languages.js#L85)):*
> ```JavaScript
> const searchLocales = (query) => {
>   const endpoint = window.config.baseUrl + window.config.apiRoot +
>     '/locales/new?filter=' + query
> ```

query needs to be encoded

---

*[zanata-frontend/src/frontend/app/actions/languages.js, line 157 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU-fg1ix-tCePpVWwrt:-KU-fg1ix-tCePpVWwru:bpq4lui) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-frontend/src/frontend/app/actions/languages.js#L157)):*
> ```JavaScript
>         receivedAt: Date.now()
>       }
>     },
> ```

This block appears a lot and are very similar. Only type, the final dispatch object are different. Might be a good idea to generalize it to a function to reduce repetition. 

---

*[zanata-frontend/src/frontend/app/containers/Languages/Entry.js, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU-r-zQwBl18AoZsG10:-KU-r-zQwBl18AoZsG11:b-ts9zkj) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-frontend/src/frontend/app/containers/Languages/Entry.js#L38)):*
> ```JavaScript
>             <span>{localeDetails.localeId} [{localeDetails.nativeName}]</span>
>             {localeDetails.enabledByDefault &&
>               <span className='greentext badge Mstart(rq)'>
> ```

is this a mixture of bootstrap and atomic css?

---

*[zanata-war/src/main/java/org/zanata/dao/LocaleDAO.java, line 110 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0-OfofgYHH6PSkXH0:-KU0-OfofgYHH6PSkXH1:bbx28cf) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.java#L110)):*
> ```Java
>                 sortQuery.add(sortField.getEntityField() + order);
>             }
>             queryBuilder.append(Joiner.on(", ").join(sortQuery));
> ```

This query is so complicated I think it's best to extract to a method and then unit test it (to cover all the possible combinations). I will also put a debug log for it.

---

*[zanata-war/src/main/java/org/zanata/dao/LocaleDAO.java, line 125 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0-4tpy0oLSTZv7lvi:-KU0-4tpy0oLSTZv7lvj:b-fza3o4) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/dao/LocaleDAO.java#L125)):*
> ```Java
> 
>     public int countByFind(String filter, boolean onlyActive) {
>         return find(0, -1, filter, null, onlyActive).size();
> ```

We should use a count query instead of the normal query. Otherwise we will be wasting resources on gathering unused results and turn them into entity and then throw away.

---

*[zanata-war/src/main/java/org/zanata/rest/editor/dto/LocaleSortField.java, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU001n_yNEmlt14ovNq:-KU001n_yNEmlt14ovNr:bh75e27) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/dto/LocaleSortField.java#L38)):*
> ```Java
>         }
> 
>         boolean isAscending = !field.startsWith("-");
> ```

Is this '-' sign from UI request? We need to document this. 

---

*[zanata-war/src/main/java/org/zanata/rest/editor/dto/LocaleSortField.java, line 46 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU00K5fVLUDXPgJ9EhG:-KU00K5fVLUDXPgJ9EhH:byhfolp) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/dto/LocaleSortField.java#L46)):*
> ```Java
>                 isAscending);
>         }
>         return null;
> ```

So is this method is the factory method to create valid LocaleSortField? as if the field is not in fieldMap, it will be null? Let's put javadoc on it. And put nullable on the return type.

---

*[zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java, line 127 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0Y3DRcavjX-O2uI9u:-KU0Y3DRcavjX-O2uI9v:b-iyb0d7) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java#L127)):*
> ```Java
>             @QueryParam("size") @DefaultValue("10") int size) {
>         List<LocaleId> supportedLocaleIds =
>                 localeServiceImpl.getAllLocales(1, -1, null, null).stream()
> ```

I would suggest an overloaded method or another method with meaningful name to get all locales without paging and filter etc. So you don't need to have this 1, -1, null, null as arguments. 

---

*[zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java, line 132 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0UpaUlGtDsyyj1HWT:-KU0UpaUlGtDsyyj1HWU:b6vfid6) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java#L132)):*
> ```Java
> 
>         List<LocaleDetails> localeDetails =
>                 localeServiceImpl.getAllJavaLanguages().stream()
> ```

AllJavaLanguages() result is pretty much static for each deployment right? If so we may want to store it in a static field or produce (CDI producer method on localeServiceImp) it as a ApplicationScoped bean.

---

*[zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java, line 133 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0UdiJJTfncT4tx8J1:-KU0UdiKbv1AShYEA32u:b-osbl27) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java#L133)):*
> ```Java
>         List<LocaleDetails> localeDetails =
>                 localeServiceImpl.getAllJavaLanguages().stream()
>                         .filter(newLocale -> !supportedLocaleIds
> ```

The variable name is misleading. It's not a newLocale but a locale from all java languages. I suggest to name it lang or localeId.

---

*[zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java, line 209 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0VUPzQZ5wRsPGInTV:-KU0VUPzQZ5wRsPGInTW:b-38r3xb) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/service/LocalesService.java#L209)):*
> ```Java
>         identity.checkPermission("insert-language");
> 
>         if (localeServiceImpl.localeExists(localeDetails.getLocaleId())) {
> ```

I think making this method a PUT operation and idempotent will be more user friendly. Same as put project and put version. If it's already there, no op and return 200. otherwise create it and return 201. 

---

*[zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java, line 56 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0Wpe6b_LHU_UkZ8ZX:-KU0Wpe6b_LHU_UkZ8ZY:btmc8tk) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java#L56)):*
> ```Java
> 
>     /**
>      * Retrieves a full list of localized locales for server. The result is
> ```

"The result is" and then it cut off?

---

*[zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java, line 72 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0Wuw1y1KawOUdPZOV:-KU0Wuw1y1KawOUdPZOW:b-wlxtou) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java#L72)):*
> ```Java
> 
>     /**
>      * Retrieves a list of locales that is not added yet in the server. The result is
> ```

"The result is" then cut off?

---

*[zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java, line 103 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0X7DUZ2jd4eeJO01s:-KU0X7DUZ2jd4eeJO01t:b-pcfemv) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java#L103)):*
> ```Java
> 
>     /**
>      * Create new language in Zanata
> ```

Create a new language?

---

*[zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java, line 110 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0WWneW-U3ILSRdSLA:-KU0WWnfEh3UWlerXJ0v:b-nqzxr2) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/rest/editor/service/resource/LocalesResource.java#L110)):*
> ```Java
>      *         the server while performing this operation.
>      */
>     @POST
> ```

I would suggest to change it to PUT and make this method idempotent. 

---

*[zanata-war/src/main/java/org/zanata/security/SecurityFunctions.java, line 442 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0XlM9nf8mYI78Kisc:-KU0XlM9nf8mYI78Kisd:bp9kl9g) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/security/SecurityFunctions.java#L442)):*
> ```Java
> 
>     /* Only admin can delete language in the server */
>     @GrantsPermission(actions = { "delete-language", "insert-language" })
> ```

What's the "insert-language" doing here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1310)*

**Comment by seanf** [comment]
Any chance we could give this PR a better name (similar to a good git commit message)?

**Comment by seanf** [comment]
*[zanata-war/src/main/java/org/zanata/security/SecurityFunctions.java, line 442 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0XlM9nf8mYI78Kisc:-KU0_-FH6iLz6BZ6qZMp:bexfwda) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/security/SecurityFunctions.java#L442)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> What's the "insert-language" doing here?
</details>
Perhaps the method is misnamed and miscommented. It makes sense that only admin can insert OR delete a language.

But have we not had a permissions check for this until now?!?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1310)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 17 unresolved discussions, some commit checks failed.

---

*[zanata-frontend/src/frontend/app/actions/languages.js, line 157 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU-fg1ix-tCePpVWwrt:-KUG2ubxv6V9TRZF4jcg:bw50jzh) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-frontend/src/frontend/app/actions/languages.js#L157)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> This block appears a lot and are very similar. Only type, the final dispatch object are different. Might be a good idea to generalize it to a function to reduce repetition. 
</details>
I've tried that previously and the became very confusing to read especially with the chain ajax request. I would have it that way until we decide to change our library for ajax call.

---

*[zanata-frontend/src/frontend/app/containers/Languages/Entry.js, line 38 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU-r-zQwBl18AoZsG10:-KUFru1s3vPocxkk_xln:b-ixbs35) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-frontend/src/frontend/app/containers/Languages/Entry.js#L38)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> is this a mixture of bootstrap and atomic css?
</details>
Yes. As of now, we don't have margin/padding css in bootstrap style. Will migrate in different jira.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1310)*

**Comment by huangp** [comment]
Reviewed 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---

*[zanata-war/src/main/java/org/zanata/security/SecurityFunctions.java, line 442 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KU0XlM9nf8mYI78Kisc:-KUG6c9QWVSU37O5ZXPP:b-j79uk3) ([raw file](https://github.com/zanata/zanata-server/blob/8478704bfab25b7f92636535ed4333989fd1efcc/zanata-war/src/main/java/org/zanata/security/SecurityFunctions.java#L442)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Perhaps the method is misnamed and miscommented. It makes sense that only admin can insert OR delete a language.
> 
> But have we not had a permissions check for this until now?!?
</details>
Should this method and comment be renamed to reflect the fact that it also does check on insert-language?

---

*[zanata-war/src/main/java/org/zanata/servlet/annotations/AllJavaLocales.java, line 14 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-KUG6BAdcdUiHxqyAyXc:-KUG6BAdcdUiHxqyAyXd:b-fgh9ez) ([raw file](https://github.com/zanata/zanata-server/blob/313c3bc9e0805d0b478884efc28b947cb52c4e0a/zanata-war/src/main/java/org/zanata/servlet/annotations/AllJavaLocales.java#L14)):*
> ```Java
> 
> /**
>  * Qualifier used to inject all available java localeId from LocaleServiceImpl
> ```

You don't need to mention "from LocaleServiceImpl". Technically it can come from anywhere.  We shouldn't tie it to an implementation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1310)*

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 1 of 9 files at r2, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 18 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1310#-:-KUGF44v9eEdBxRfBRgs:b9a2vem)*

**Comment by djansen-redhat** [comment]
- [ ] Language page broken (seems to go to profile)
- [ ] Cannot add languages with lengthy plural forms (eg. Russian) "com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'pluralForms' at row 1"
- [ ] Page does not refresh when a language is added
- [ ] Search box loses focus when a search occurs

**Comment by seanf** [comment]
Could we please rename this to "Convert language page to React" or something?

**Comment by djansen-redhat** [comment]
- [ ] Sort seems to be by creation order, not by locale code
- [ ] Members sort is ascending - need to determine value of that or provide more options

**Comment by djansen-redhat** [comment]
- [ ] Cannot create an arbitrary language, save button does not enable

**Comment by djansen-redhat** [comment]
- [ ] Questionable thing - attempting to delete a language that has translations attached to it results in a "Disable it instead" message. However, I noticed that the members are actually silently removed in this process.

**Comment by alex-sl-eng** [comment]
@djansen-redhat Thats the behaviour right now if deleting is unsuccessful. We might need to take this as separate issue if we want to resolve this. Btw, I've moved this PR to https://github.com/zanata/zanata-platform/pull/3 to have a green build on both server and api.

**Pull request closed without merging**
