### PR TITLE
Warn on startup if EAP/WildFly too old

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by seanf** [comment]
@carlosmunoz Do you have any other review comments?

**Comment by carlosmunoz** [comment]
No more comments. :+1:

**Comment by huangp** [comment]
Should we also check mysql version? I remember seeing people asking on freenode when they have newer mysql running and getting nasty exceptions but don't know why

**Comment by seanf** [comment]
@huangp Yes, it would be good to check the mysql version (or at least log it), but I can't think of an easy way to do that in `ZanataInit`. Feel free to put in an RFE or a PR.

**Pull request merged**
