### PR TITLE
feat(editor): display flags and reference from pot file

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1243672

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
Last modified by and last modified date icons show even if no data

**Comment by djansen-redhat** [comment]
This is a bit strange -
broken_line

**Comment by aeng** [comment]
@djansen-redhat I think the status line break was already there. Not introduced in this branch.

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/46ab129a0f665cc7aac39986b838f2c9b628aa76

**Pull request closed without merging**
