### PR TITLE
fix(focus): add auto focus in create form, login and signup page

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-27

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1195)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### fix\(focus\): add auto focus in create form, login and signup page
> 
> https://zanata.atlassian.net/browse/ZNTA-27
> 
> 
> 
</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1195#-:-KJnA2woco95zqVq43fg:1417088721)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1195)*

**Comment by djansen-redhat** [comment]
:white_check_mark: THANK YOU for fixing this ancient bug.

**Pull request merged**
