### PR TITLE
feat(maintainers-tab,members-tab): Rhbz1246359 Link usernames to user…

### PR DESCRIPTION
**Pull request by djansen-redhat**
… profile

### CODE REVIEW

**Comment by djansen-redhat** [comment]
@davidmason It's all yours now :D

**Comment by djansen-redhat** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1246359

**Comment by djansen-redhat** [comment]
No longer required

**Comment by seanf** [comment]
@djansen-redhat did you want to delete the branch?

**Pull request closed without merging**
