### PR TITLE
Ignore flaky change password test

### PR DESCRIPTION
**Pull request by djansen-redhat**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/855" target="_blank">ReviewNinja

**Comment by aeng** [comment]
Question, how are we going to handle the flaky test? are we going to revisit them?

**Comment by aeng** [comment]
Apart from the question, everything is good. :+1:

**Comment by djansen-redhat** [comment]
@aeng yes, after the release I will revisit the flaky tests.  It may be simple, but I don't have the time to do much other than manually verify them for now.

**Pull request merged**
