### PR TITLE
fix(File upload): Remove file extension for gettext type upload in UI

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-981

### CODE REVIEW

**Comment by huangp** [comment]
:+1: 
the build is broken due to something else though

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, is good

**Comment by djansen-redhat** [comment]
@aeng is there any foreseeable need for migration of currently existing pot documents?

**Comment by aeng** [comment]
@djansen-redhat not needed as far I'm concern.

**Pull request merged**
