### PR TITLE
fix(ZNTA-1060): avoid NPE in DuplicateParamFilter

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1060

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by seanf** [comment]
@aeng @huangp Mind taking a look? The last commit is meant to address https://zanata.atlassian.net/browse/ZNTA-1072

**Comment by aeng** [comment]
:+1: . Good to fix the issue in https://github.com/zanata/zanata-server/pull/1160

**Comment by djansen-redhat** [comment]
@seanf this pr fixes both the issues listed above (NPE and multiple checkbox)

**Pull request merged**
