### PR TITLE
ZNTA-650 migrate action in pages.xml to jsf pages

### PR DESCRIPTION
**Pull request by huangp**
Migrated commits from #959 

https://zanata.atlassian.net/browse/ZNTA-650

### CODE REVIEW

**Comment by seanf** [comment]
What's this PR for again? Is it a merge for two other outstanding branches which have their own PRs?

**Comment by huangp** [comment]
This is the first part of #959 which only contain changes for migrating ```<action execute="#{...``` to jsf. It's safer to merge in. #959 will then only contain page flow changes (navigation rules)

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@seanf @huangp This looks like something that can be comfortably mark as tested via the functional tests, yes?

**Comment by djansen-redhat** [comment]
:see_no_evil: :shipit:

**Pull request merged**
