### PR TITLE
Simplify parent

### PR DESCRIPTION
**Pull request by seanf**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1119)

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
This will allow the parent pom to be slimmed down a bit in https://github.com/zanata/zanata-parent/pull/54

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by carlosmunoz** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 330 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-server/1119#-KMRMf95Y8qRJ41LGwUj:-KMRMf95Y8qRJ41LGwUk:-561148725) ([raw file](https://github.com/zanata/zanata-server/blob/ca969f6fa82c95c6b1be9197487165e38681a6ab/pom.xml#L330)):*
> ```XML
>         <artifactId>lombok</artifactId>
>         <version>${lombok.version}</version>
>         <scope>provided</scope>
> ```

mmm... why do we need this now? and why provided?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1119)*

**Comment by seanf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[pom.xml, line 330 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-server/1119#-KMRMf95Y8qRJ41LGwUj:-KMRjFVnLr7CMY90ipIh:1086083961) ([raw file](https://github.com/zanata/zanata-server/blob/ca969f6fa82c95c6b1be9197487165e38681a6ab/pom.xml#L330)):*
<details><summary><i>Previously, carlosmunoz (Carlos Munoz) wrote…</i></summary>
> mmm... why do we need this now? and why provided?
</details>
We need it here because I want to remove the Lombok dependency from zanata-parent - we only use it in Server anyway.

Even if we use Lombok in Zanata client in future (BAD idea), we would probably want to use a different version of it: the Fedora version, assuming it is ever packaged for Fedora.

*Provided* because Lombok's jar isn't supposed to be needed at runtime: https://projectlombok.org/mavenrepo/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1119)*

**Comment by carlosmunoz** [comment]
:lgtm:
-(Awaiting review) +Reviewed 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1119#-:-KMRmrQnYUF5pzvvG3dv:-1149335731)*

**Comment by djansen-redhat** [comment]
:white_check_mark: this looks fine

**Pull request merged**
