### PR TITLE
fix(ZNTA-931): incorrect scopes

### PR DESCRIPTION
**Pull request by broccolinisoup**
https://zanata.atlassian.net/browse/ZNTA-931

### CODE REVIEW

**Comment by carlosmunoz** [comment]
@broccolinisoup I think this has unintended commits from the previous rebase. Same thing happened to me the other day. 
An interactive rebase removing the unnecessary commits did the trick for me.

**Comment by broccolinisoup** [comment]
@carlosmunoz Do you mean Ding's commit? When doing interactive rebase deleting the Ding's commit line and keeping mine (2 commits) works?

**Comment by seanf** [comment]
:+1: 

One of the commits has the wrong email address for @broccolinisoup so we should make sure to squash-merge this one (just for nice github stats). (That's assuming github's squash-merge will choose the right author.)

**Comment by broccolinisoup** [comment]
I cleaned it up. @seanf  Thanks @aeng for your help.

PS: I learnt many things about Git today. Thanks.

**Comment by seanf** [comment]
Looks good.

**Comment by definite** [comment]
After I reset password and re-login, there is a brief error notification "Invalid Key" showing after I logined, otherwise the fix worked fine.

**Comment by djansen-redhat** [comment]
@definite I didn't get that message when I tried it - did you login immediately after resetting the password?

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@djansen-redhat , @broccolinisoup I think it is working on my side now. Perhaps it was a side-effect on previous commit.

**Pull request merged**
