### PR TITLE
Include editor code from zanata-spa in server module (ZNTA1193)

### PR DESCRIPTION
**Pull request by davidmason**
- copied code from zanata-spa to zanata-server/zanata-editor/src
 - configured to build and package as a jar
 - configured zanata-war to include the jar module, serves the built files to *server*/app
 - added some commenting to zanata-server/frontend/pom.xml (should be no config changes there)

@huangp it is probably easiest to check the first 2 commits separately first because that is just copying the code and deleting the old build code.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1229)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 254 of 254 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions, some commit checks failed.

---

*[pom.xml, line 2078 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnfEKDzTX1eLy92TzM:-KLnfEKEQNEy9I6uPu1N:-198272239) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/pom.xml#L2078)):*
> ```XML
>       <activation>
>         <property>
>           <name>!excludeEditor</name>
> ```

Maybe name it excludeNewEditor to be clear. Otherwise it's hard to guess what it does

---

*[frontend/pom.xml, line 94 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLng-Ee3BX8GkJYEJbg:-KLng-Ee3BX8GkJYEJbh:600926667) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/frontend/pom.xml#L94)):*
> ```XML
>         <configuration>
>           <environmentVariables>
>

**Comment by huangp** [comment]
Review status: all files reviewed at latest revision, 16 unresolved discussions, some commit checks failed.

---

*[zanata-editor/src/.gitignore, line 18 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnkitws3bhVg-5gbcR:-KLnkitws3bhVg-5gbcS:-1116107353) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/.gitignore#L18)):*
> ```
> 
> # imdone task board
> .imdone
> ```

Some of these may have already been defined in the upper level folder/maven module. But I guess it's okay to have it duplicated here.
Seeing that you accidentally committed bundle.js etc in, maybe it's good idea to put bundle.js bundle.css, bundle.js.map and bundle.css.map in here

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1229)*

**Comment by davidmason** [comment]
Review status: 248 of 253 files reviewed at latest revision, 16 unresolved discussions.

---

*[pom.xml, line 2078 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnfEKDzTX1eLy92TzM:-KLnu8bZhSBZj9N_PbC_:-778337157) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/pom.xml#L2078)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Maybe name it excludeNewEditor to be clear. Otherwise it's hard to guess what it does
</details>
Maybe `excludeAlphaEditor` since we are calling it that in other places.

---

*[frontend/pom.xml, line 94 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLng-Ee3BX8GkJYEJbg:-KLnp-YzgxGBFvJ3y8qb:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/frontend/pom.xml#L94)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I will probably change it to 'Ensure that the locally installed (by frontend-maven-plugin) node and npm are at the start of PATH'
</details>
Done.

---

*[zanata-editor/src/.gitignore, line 18 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnkitws3bhVg-5gbcR:-KLnpDchmWtZwZGl0-lN:1847811309) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/.gitignore#L18)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Some of these may have already been defined in the upper level folder/maven module. But I guess it's okay to have it duplicated here.
> Seeing that you accidentally committed bundle.js etc in, maybe it's good idea to put bundle.js bundle.css, bundle.js.map and bundle.css.map in here
</details>
I think that would be handled by the entry `build` above. I just ran a local build to create the app/build directory and its contents and it does not include them when I run `git status` so it looks fine.

The bundle.js etc. that I deleted are from before the editor is moved to be a submodule -  they were purposely copied into zanata-war and checked in, so not an accidental addition.

---

*[zanata-editor/src/package.json, line 2 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnhX4AqmTGM9pglLEr:-KLnrL0uGvZkRBGjlc7b:570562543) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/package.json#L2)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> do we still call it zanata-spa or should we name it something like zanata-editor?
</details>
Changed to zanata-editor.

---

*[zanata-editor/src/package.json, line 4 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnhbZ3PpvigaIs0fGN:-KLnrO1pKUjPa2rDzsZ7:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/package.json#L4)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> May change it to Zanata alpha editor for now
</details>
Done.

---

*[zanata-editor/src/package.json, line 5 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnhh0MQWsHs4lVU6Qg:-KLnrPGu8_pMLav57t3F:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/package.json#L5)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> This will need to change too
</details>
Done.

---

*[zanata-editor/src/package.json, line 12 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnhj2g0-t9ZwvZbhjv:-KLnrR9syIt19wneadWB:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/package.json#L12)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> And this
</details>
Done.

---

*[zanata-editor/src/package.json, line 25 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnhlvpZQ2U1AWR5N0k:-KLnrlz9HzLKzSgKQ9HN:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/package.json#L25)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> And this
</details>
Done.

---

*[zanata-editor/src/README.md, line 1 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnhvLYFxFd8pjGbqng:-KLnte3m-hICFlfbyRxs:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/README.md#L1)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Zanata (Alpha editor)
</details>
Done.

---

*[zanata-editor/src/app/README.md, line 5 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLniZTs1OKGf4dJPwix:-KLntvshRcpxYFweyER8:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/app/README.md#L5)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> needs to update
</details>
Done.

---

*[zanata-editor/src/app/README.md, line 9 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnibN2jKqnIJu9Xy2k:-KLnu57o2V14Ax95RZkI:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/app/README.md#L9)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> needs to update
</details>
Done.

---

*[zanata-editor/src/app/README.md, line 14 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnicu7BOEW8vOV0IQG:-KLnu5d-zE7AqqH0MVFE:-499146009) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/app/README.md#L14)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> needs to update
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1229)*

**Comment by davidmason** [comment]
Review status: 247 of 253 files reviewed at latest revision, 16 unresolved discussions.

---

*[zanata-war/src/main/webapp/app/bundle.js, line  \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnk7GZPWDKUrPg-zbF:-KLnxZgagytVllObWzj_:1856536709) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-war/src/main/webapp/app/bundle.js#L)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> don't commit this (you will need to rewrite history or squash merge in the end to get this out of git history)
</details>
All 4 of these deleted files are present in zanata-war *before* this PR, not added in this PR.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1229)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review)  +Reviewed +(On QA) 

---

Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-:-KLo8HePJy0xVVu_D1rj:-1425745978)*

**Comment by davidmason** [comment]
Jenkins: retest this please

:pray:

**Comment by definite** [comment]
:+1:  Behave same with master

**Comment by huangp** [comment]
Review status: 250 of 253 files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-editor/src/.gitignore, line 18 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1229#-KLnkitws3bhVg-5gbcR:-KLtIGugHzWHrw2p2mJh:1854847568) ([raw file](https://github.com/zanata/zanata-server/blob/862204528c4b0b197cf0fb24e29181d131cd5575/zanata-editor/src/.gitignore#L18)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I think that would be handled by the entry `build` above. I just ran a local build to create the app/build directory and its contents and it does not include them when I run `git status` so it looks fine.
> 
> The bundle.js etc. that I deleted are from before the editor is moved to be a submodule -  they were purposely copied into zanata-war and checked in, so not an accidental addition.
</details>
Ok. We should avoid checking in binary/build files anyway.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1229)*

**Pull request merged**
