### PR TITLE
upgrade zanata-common to 3.6.0

### PR DESCRIPTION
**Pull request by huangp**
https://bugzilla.redhat.com/show_bug.cgi?id=1029734

### CODE REVIEW

**Comment by djansen-redhat** [comment]
- [ ] :x: Release note

**Comment by huangp** [comment]
Added release note

**Comment by aeng** [comment]
:+1:

**Comment by djansen-redhat** [comment]
Just to clarify - this change makes it "not break", rather than successfully parse, when the header is invalid?

**Comment by huangp** [comment]
Yes and no. Before this change if you upload a po file with "\n" or "abc" in header entry, it will throw exception and terminate. Now it will log a warning and ignore the offending entry but continue parsing. To offer better feedback to user is out of scope for this one.

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Pull request merged**
