### PR TITLE
Test against surefire/failsafe snapshot

### PR DESCRIPTION
**Pull request by seanf**
This is just a test.

See https://issues.apache.org/jira/browse/SUREFIRE-1152?focusedCommentId=14713006&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14713006

### CODE REVIEW

**Comment by Tibor17** [comment]
@seanf 
I have fixed surefire 2.19-SNAPSHOT which means the rerun should work with all fork modes.
Can you please test rerun together with parameter reuseForks and forkCount ?
Let me know if you find some strange behavior. Meanwhile I will complete pull request which are almost done and we can go on with the release.

**Comment by seanf** [comment]
test this please

**Comment by Tibor17** [comment]
`functional-test` is the project with test?
I made a clone of your branch a run mvn install but the project fails right in `frontend`.
I am not familiar with this project but can you tell me what is now wrong and is different from ITs you wrote in surefire project? Our tests in surefire pass so everything should pass here under the same circumstances.

**Comment by seanf** [comment]
Very sorry @tibor17 I was talking to Jenkins!

**Comment by Tibor17** [comment]
If you need our help in Maven, feel free to open a ticket in Jira.

**Comment by seanf** [comment]
@Tibor17 the build status may not show up correctly, but in Jenkins the deliberately FlakyTest passed on the second try, which means rerun is working as it should.  That's with failsafe's default settings, `reuseForks=true` and `forkCount=1`.  Thanks.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by Tibor17** [comment]
@seanf 
We are in progress with the release Vote. Meanwhile you can test with 2.20-SNAPSHOT.

**Comment by Tibor17** [comment]
@seanf 
Version 2.19 was released and now appears in Maven Central.

**Comment by seanf** [comment]
That's great, thanks @Tibor17 .

**Pull request closed without merging**
