### PR TITLE
ZNTA-421 Swap TM highlighting

### PR DESCRIPTION
**Pull request by kathryngo**
https://zanata.atlassian.net/browse/ZNTA-421

This is the branch that needs to be merged. I will close the other pull request (https://github.com/zanata/zanata-server/pull/1296).

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1298)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 52 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS96U0z18hrUtsbo3_h:-KS96U0z18hrUtsbo3_i:b-eopgfp) ([raw file](https://github.com/zanata/zanata-server/blob/b4619e64d8ec23c1fedff68a1323710f7e23bdd5/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L52)):*
> ```Java
>     var i = -1;
>     var lcSearchTerm = searchTerm.toLowerCase();
>     var lcBodyTextcd  = bodyText.toLowerCase();
> ```

Accident?

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 83 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS96dqTTv7xUDyEcmTF:-KS96dqTTv7xUDyEcmTG:b-ih5jd9) ([raw file](https://github.com/zanata/zanata-server/blob/b4619e64d8ec23c1fedff68a1323710f7e23bdd5/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L83)):*
> ```Java
> 
>     @CoverageIgnore("JSNI")
>     private static native JavaScriptObject diff(String originalContents, String diffContents,
> ```

I think I would go with "oldText, newText" here too.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 91 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS972Kub9p9nC1g8zSZ:-KS972Kub9p9nC1g8zS_:b-9cny9g) ([raw file](https://github.com/zanata/zanata-server/blob/b4619e64d8ec23c1fedff68a1323710f7e23bdd5/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L91)):*
> ```Java
> 
>     var dmp = $wnd.diffMatchPatch;
>     var diffs = dmp.diff_main(originalContents, diffContents);
> ```

And here of course.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS96tvwXBZwPfDy7d5I:-KS96tvx7-6kRq4DGj-l:bitfxxb) ([raw file](https://github.com/zanata/zanata-server/blob/b4619e64d8ec23c1fedff68a1323710f7e23bdd5/zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml#L64)):*
> ```XML
>       <li class="bx--inline zeta">TM Diff Highlighting</li>
>       <li class="bx--inline diff-delete">TM MATCH</li>
>       <li class="bx--inline diff-insert">SEARCH TEXT</li>
> ```

How about "TM match" and "Search text"?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1298)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 52 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS96U0z18hrUtsbo3_h:-KS97luYZGPuCo1ckIGa:b-jrj79h) ([raw file](https://github.com/zanata/zanata-server/blob/b4619e64d8ec23c1fedff68a1323710f7e23bdd5/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L52)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Accident?
</details>
Yes. Thanks for picking that up

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1298)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS97gW6fjqbEXPINgsn:-KS97gW6fjqbEXPINgso:b-8rsje2) (no related file):*
@kathryngo Just for next time: to help with navigating between JIRA and GitHub, it's best if the pull request title includes a JIRA reference, and also it's good to add a JIRA link to the description. (I've already made the edit.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1298)*

**Comment by kathryngo** [comment]
*[a discussion](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS97gW6fjqbEXPINgsn:-KS98ZD2G24zjTN1LvsP:bvmb4vo) (no related file):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> @kathryngo Just for next time: to help with navigating between JIRA and GitHub, it's best if the pull request title includes a JIRA reference, and also it's good to add a JIRA link to the description. (I've already made the edit.)
</details>
Ok, I will make sure to do that in the future. Thank you.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1298)*

**Comment by seanf** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 52 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS96U0z18hrUtsbo3_h:-KS9Q2LY2w6a7mOJ44Pl:bqwdgxj) ([raw file](https://github.com/zanata/zanata-server/blob/b4619e64d8ec23c1fedff68a1323710f7e23bdd5/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L52)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary>
> Yes. Thanks for picking that up
</details>
Could I get you to remove the extra space, please?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1298)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 52 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-KS96U0z18hrUtsbo3_h:-KS9ed6czjEa3dcB6YJE:b-896fix) ([raw file](https://github.com/zanata/zanata-server/blob/b4619e64d8ec23c1fedff68a1323710f7e23bdd5/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L52)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Could I get you to remove the extra space, please?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1298)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1298#-:-KSA-xcWGH7Vic7YKsv1:bnfp4nl)*

**Comment by djansen-redhat** [comment]
What's happening with this one, ready for QA?  Reviewable is still yellow, but I see the lgtm stamp.

**Comment by seanf** [comment]
@kathryngo I've resolved the outstanding discussions. (LGTM should offer to do that, I think.)  If you're ready for QA, you should now add the "On QA" label in github. Thanks.

**Comment by kathryngo** [comment]
Done.

**Comment by kathryngo** [comment]
Aha, got it. Thanks

**Comment by djansen-redhat** [comment]
:white_check_mark: groovy.

**Comment by seanf** [comment]
@kathryngo Don't forget to delete your branch when merging your pull requests!

**Pull request merged**
