### PR TITLE
Try to log process info when SMTP port is unavailable

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by huangp** [comment]
looks like the groovy compilation is not set up correctly

**Comment by seanf** [comment]
> looks like the groovy compilation is not set up correctly

Oops, thanks. I guess my test build wasn't a clean build (IDEA must have compiled the .groovy for me).

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by huangp** [comment]
:+1: for the code change but you need to fix dependency issue

**Comment by seanf** [comment]
@huangp I'

**Comment by seanf** [comment]
@huangp I've taken out the line for groovy-all to make the dependency checker happy again.

**Pull request merged**
