### PR TITLE
feat(project glossary): Project glossary

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1101

api: https://github.com/zanata/zanata-api/pull/61
common: https://github.com/zanata/zanata-common/pull/30
client: https://github.com/zanata/zanata-client/pull/127

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1285)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 71 of 71 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[zanata-frontend/src/frontend/app/reducers/glossary.js, line 649 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1285#-KR78iWv2dcvqZJNjIXB:-KR78iWv2dcvqZJNjIXC:b-6inxsv) ([raw file](https://github.com/zanata/zanata-server/blob/29d8c65c414aba77cdd82a10d5b232fb40c2c6bd/zanata-frontend/src/frontend/app/reducers/glossary.js#L649)):*
> ```JavaScript
>         severity: SEVERITY.ERROR,
>         message: 'We are unable to get glossary information from server. ' +
>         'Please refresh this page and try again.'
> ```

This message repeats several times. Should extract it to a variable

---

*[zanata-war/src/main/java/org/zanata/rest/service/ProjectService.java, line 240 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1285#-KR7EnseD7GOhZ0IE2_G:-KR7EnseD7GOhZ0IE2_H:bo4qh40) ([raw file](https://github.com/zanata/zanata-server/blob/29d8c65c414aba77cdd82a10d5b232fb40c2c6bd/zanata-war/src/main/java/org/zanata/rest/service/ProjectService.java#L240)):*
> ```Java
>     }
> 
>     private static void transfer(HProject from, Project to) {
> ```

I remember Sean asked to rename these methods from transfer. Any reason you want to rename it back?

---

*[zanata-war/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java, line 140 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1285#-KR7FzZTzm2iFOExMMUN:-KR7FzZUM5X-WHBiAlFu:b5gt35n) ([raw file](https://github.com/zanata/zanata-server/blob/29d8c65c414aba77cdd82a10d5b232fb40c2c6bd/zanata-war/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java#L140)):*
> ```Java
>             if(hGlossaryEntry.getContentHash().startsWith("3d8c541a")) {
>                 System.out.println(hGlossaryEntry.getGlossary().getQualifiedName());
>             }
> ```

What is this magic hash?

---

*[zanata-war/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java, line 335 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1285#-KR7HzckE4KFlqbHh6Zo:-KR7HzckE4KFlqbHh6Zp:b-7u71w1) ([raw file](https://github.com/zanata/zanata-server/blob/29d8c65c414aba77cdd82a10d5b232fb40c2c6bd/zanata-war/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java#L335)):*
> ```Java
>                     && !term.getLocale().equals(transLocaleId.get())) {
>                 continue;
>             }
> ```

Now that we have java 8 stream, it may be easier to read if you just do a filter followed by forEach().

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1285)*

**Comment by huangp** [comment]
-(Awaiting review) +(Under review) 

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1285#-:-KR7KBlKER0eO2P4FxOj:b-uviksp)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[zanata-war/src/main/java/org/zanata/rest/service/ProjectService.java, line 240 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1285#-KR7EnseD7GOhZ0IE2_G:-KR7Pd6zexqNNhcI0ez-:bjyhsqa) ([raw file](https://github.com/zanata/zanata-server/blob/29d8c65c414aba77cdd82a10d5b232fb40c2c6bd/zanata-war/src/main/java/org/zanata/rest/service/ProjectService.java#L240)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I remember Sean asked to rename these methods from transfer. Any reason you want to rename it back?
</details>
I think its my mistake. Reverting it back.

---

*[zanata-war/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java, line 140 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1285#-KR7FzZTzm2iFOExMMUN:-KR7Q8v5SoOYppOEXu2l:b-w3m9jh) ([raw file](https://github.com/zanata/zanata-server/blob/29d8c65c414aba77cdd82a10d5b232fb40c2c6bd/zanata-war/src/main/java/org/zanata/service/impl/GlossaryFileServiceImpl.java#L140)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> What is this magic hash?
</details>
lol. Debug. Removing it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1285)*

**Comment by huangp** [comment]
:lgtm: -(Under review) +Reviewed +(On QA) 

---

Reviewed 2 of 4 files at r2.
Review status: 69 of 70 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1285#-:-KRQasbPlZ8thkN2TXOw:b-nx6778)*

**Comment by djansen-redhat** [comment]
Trying to translate a glossary entry for the project:
> POST XHR http://localhost:8180/rest/glossary/entries [HTTP/1.1 400 Bad Request 5ms]

**Comment by djansen-redhat** [comment]
I may have found a bug in Glossary, but I'm not sure it's related
Search term: Release Date: June, 2001
[NPE on glossary search](http://pastebin.com/QjubTTvv)

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, looks good, great feature

**Pull request merged**
