### PR TITLE
ZNTA-1271 make functional-test to use resteasy

### PR DESCRIPTION
**Pull request by huangp**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1299)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1299)*

**Comment by huangp** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@huangp Looks like enforcer failures.

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 7 of 7 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1299#-:-KSia4WmqupXjqjEgEHY:bnfp4nl)*

**Pull request merged**
