### PR TITLE
chore(dependency): point asset to 8.0-SNAPHOT (asset branch master)

### PR DESCRIPTION
**Pull request by definite**
This point to zanata-asset 8.0-SNAPSHOT, which is current in asset branch master.

### CODE REVIEW

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by davidmason** [comment]
This failing due to an *extremely strange and mysterious* behaviour.

The function `zanata.modal.show` uses jQuery to select an element and add a css class to it, and to select the body and add a css class and some inline style to it. This function is called form the delete button (Project general settings).

- If I run it from the web console, it works and a confirmation dialog is shown.
- If I click the button, the confirmation dialog is not shown.

Prepare yourself for the extremely strange part:

I added a bunch of logging to the function and rebuilt everything.

When I click the button, it logs the correct elements, shows the current css classes of the modal and the body, and I see the fading highlight animation in the DOM inspector for the class and style attributes on the body, and the class attribute on the modal. In all those ways it looks like the code is working as expected, **but** no class or style actually changes.

It is as though, when the function is triggered in an onclick, the values passed to jQuery to set class and style become empty strings (even though they are hard-coded in the script, and are present in the minified version of the script).

You have now crossed over

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by davidmason** [comment]
So the mysterious behaviour turned out to be pretty straightforward: the click event that triggered the call to `zanata.modal.show()` was also bubbling up the DOM and counting as a click outside the modal, which immediately hid the modal again.

**Comment by seanf** [comment]
As a user, I often find modals annoying, because of their habit of closing
something I didn't want closed, just because I clicked in empty space to
activate a window.  It sounds like Selenium finds them problematic for much
the same reason.

On 9 September 2015 at 07:59, David Mason <notifications@github.com> wrote:

> So the mysterious behaviour turned out to be pretty straightforward: the
> click event that triggered the call to zanata.modal.show() was also
> bubbling up the DOM and counting as a click outside the modal, which
> immediately hid the modal again.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-server/pull/949#issuecomment-138716061>.
>



-- 
Sean Flanigan

Principal Software Engineer
Globalisation Tools Engineering
Red Hat

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by davidmason** [comment]
There are several fixes in https://github.com/zanata/zanata-server/pull/948 for problems that assets 8 reveals. I suggest we upgrade to assets 8 in that PR and close this one.

**Comment by definite** [comment]
Pull request #948  contain this change, so close this one.

**Pull request closed without merging**
