### PR TITLE
fix(stats loading): fix stats loading in project, version, group page

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-527

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1292)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1292#-:-KRkQVwtHC1vZjGctVmJ:b49ms4)*

**Comment by djansen-redhat** [comment]
- [ ] Issue with refresh after loading in some instances

Otherwise is awesomesauce

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Pull request merged**
