### PR TITLE
fix(activate account): redirect to login page after account activate

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-720

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by anipeter** [comment]
Tested. Activation link gives the login screen with all desired fields, but no success message "Successfully Activated." Screenshot1 attached.
Clicking on the activation link second time, gave "No records" error message. Screenshot2 attached.
screenshot1 - login screen while clicking the activation link in email
screenshot2 - no records message screen while clicking on activation link 2nd time

**Comment by aeng** [comment]
1) There should be activation success message in the login screen. I will look into that.
2) The second screen shot is expected. The activation link will be invalid after its being used.

**Comment by aeng** [comment]
Created new Pull request for activation account message display. https://github.com/zanata/zanata-server/pull/1045

**Pull request merged**
