### PR TITLE
feat(shortcut): add shortcut for approve and reject translation

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-746

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Need to update EditorKeyShortcutsTest

**Comment by djansen-redhat** [comment]
I just noticed this is targeting the release branch - is that intended?

**Comment by aeng** [comment]
@djansen-redhat 

> I just noticed this is targeting the release branch - is that intended?
I will close this pull request and update to master brnach.

**Comment by aeng** [comment]
Updated to https://github.com/zanata/zanata-server/pull/1148

**Pull request closed without merging**
