### PR TITLE
Only show "approved" figure in version page if "Review required" is enable or value more than 0 

### PR DESCRIPTION
**Pull request by aeng**
Only show "approved" figure in version page if "Review required" is enable or value more than 0 

https://bugzilla.redhat.com/show_bug.cgi?id=1230419

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/859" target="_blank">ReviewNinja

**Comment by huangp** [comment]
:+1:

**Comment by definite** [comment]
Test cases:
- [ ] Require Review enabled
  - [ ] Approve percent is hidden when 0% initally
  - [ ] Approve percent is hidden when  down to 0% 
  - [ ] Approve percent is shown when greater than 0%
- [ ] Require Review Disabled
  - [x] Approve percent is hidden when 0% initally
  - [ ] Approve percent is hidden when  down to 0% 
  - [ ] Approve percent is shown when greater than 0%

**Comment by definite** [comment]
:+1:

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/4a222ec2f16cf0d5ec98124aab94b4c03d01aa46

**Pull request closed without merging**
