### PR TITLE
rhbz1183412 Uses server's default locale when sending emails

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
- [ ] :no_entry: Release note

**Comment by seanf** [comment]
@djansen-redhat How are we handling release notes for the 'release` branch?

**Comment by seanf** [comment]
@djansen-redhat I have imported the release notes from master and added a line for this bug fix.

**Comment by djansen-redhat** [comment]
This does not seem to work for me. The test passes, but sending emails from the UI shows them still in the language chosen by the user.

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by seanf** [comment]
The arquillian test `org.zanata.rest.compat.TranslationsRawCompatibilityITCase.getJsonTranslations` is failing, but it seems to be triggered by https://github.com/zanata/zanata-server/commit/36ed1f6d76a7796cee49e54e1ce3946743b9956b, not by these changes.

**Pull request merged**
