### PR TITLE
exclude jersey dependency from zanata-api

### PR DESCRIPTION
**Pull request by aeng**

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
If Jenkins greenlights this then I have no objections.

**Comment by djansen-redhat** [comment]
Failed org.zanata.rest.compat.ProjectRawCompatibilityITCase.getAllProjectsXml
```
javax.xml.bind.UnmarshalException: unexpected element (uri:"", local:"collection"). Expected elements are <{http://zanata.org/namespace/api/}project>,<{http://zanata.org/namespace/api/}project-iteration>,<{http://zanata.org/namespace/api/}projects>
```
http://zanata-build.lab.eng.bne.redhat.com/job/zanata-server-github-pull-requests/org.zanata$zanata-war/4763/testReport/junit/org.zanata.rest.compat/ProjectRawCompatibilityITCase/getAllProjectsXml/

**Comment by djansen-redhat** [comment]
The test failure in build 4773 (JoinLanguageTeamTest.translatorJoinsLanguageTeam) can be ignored.

**Pull request merged**
