### PR TITLE
refactor(bookmark): Update bookmark button in editor

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: https://zanata.atlassian.net/browse/ZNTA-16

Update bookmark link in editor to be more meaningful and visible

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1307)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1307#-:-KSsD5F04Ff2WJEQPou0:b49ms4)*

**Comment by djansen-redhat** [comment]
Had a look at this - not sure it's the "right" fix. Let's talk with @kathryngo on Monday.

**Comment by aeng** [comment]
@djansen-redhat I actually got her to look at the change, but lets discuss it on Monday

**Comment by kathryngo** [comment]
@djansen-redhat , @aeng , yes let's look Tuesday.
It was a really difficult design to formulate on the spot without spending some time scribbling stuff down so I am sure it can be improved.

**Comment by kathryngo** [comment]
I'm having trouble building these changes - @djansen-redhat could you please post or send me a screenshot of the changes? That way I can at least look at it and find ways to improve it before Tuesday.

**Comment by kathryngo** [comment]
@aeng , @djansen-redhat:  I tried to improve things with this design. This probably does not resolve all the issues but it's a step in the right direction. Discuss more next week.

- made both links buttons, to show that they do some action when clicked. 
- changed the terminology to use the word Bookmark, and included a bookmark icon 
- text box is now the width of its container
- added better contrast between the link text and the select background colour


*Collapsed*
bookmark-button-v1

*Expanded*
bookmark-button-expand-v1

**Comment by djansen-redhat** [comment]
:white_check_mark: tested, good work @aeng @kathryngo

**Pull request merged**
