### PR TITLE
Disable CommonMark preview

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/876" target="_blank">ReviewNinja

**Comment by aeng** [comment]
Build failed

**Comment by aeng** [comment]
:+1:  for https://github.com/zanata/zanata-server/commit/527634b55f0c497e0b01b4f8b1610ad5c1c3ca98

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Pull request merged**
