### PR TITLE
fix(url):handle whitespace and slash in doc id url

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-767

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:+1: looks good

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
Tested with Firefox 42.0
It uploaded with out problem, but after I clicked the document to translate that.
1. It shows **No document selected**
2. No entries was listed, and **(No Content)**  is shown.

**Comment by definite** [comment]
Seems the error in my machine seems to be a configuration issue, not the scope of this PR. I will file another bug for that.
This bug should be verified.

**Pull request merged**
