### PR TITLE
fix(Project search&replace):fix bad encoding in search text

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-812

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. This fixes the issue, and doesn't appear to break anything else.

**Comment by aeng** [comment]
I think this might need more testing in GWT section as its an upgrade of version.

**Comment by aeng** [comment]
Didn't see you comment. Ignore my previous comment.

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins test this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
:+1:

**Pull request merged**
