### PR TITLE
Redux app reviewed

### PR DESCRIPTION
**Pull request by aeng**
Changed on reviewed branch of https://github.com/zanata/zanata-server/pull/1125

### CODE REVIEW

**Comment by djansen-redhat** [comment]
The Update buttons don't work in Glossary (updating 'Part of speech')

**Comment by djansen-redhat** [comment]
Pagination in language team results (Explore) does not work.

**Comment by davidmason** [comment]
@aeng this should target `redux-app` since we want the review fixes to merge to there.

**Comment by aeng** [comment]
@davidmason Good point.

**Pull request closed without merging**
