### PR TITLE
rhbz1205512 - run validation button on document list page wont be disabled

### PR DESCRIPTION
**Pull request by huangp**
when there is no validation to run

https://bugzilla.redhat.com/show_bug.cgi?id=1205512

### CODE REVIEW

**Comment by djansen-redhat** [comment]
- [ ] Release note

**Comment by huangp** [comment]
@zanata-jenkins retest this please

**Comment by huangp** [comment]
@zanata-jenkins retest this please

**Comment by davidmason** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Pull request merged**
