### PR TITLE
Update activity table with deleted version/project

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1229940

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/861" target="_blank">ReviewNinja

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, waiting for green light

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/0682460404a44efa37ecb81acf68c2fe3875f222

**Pull request closed without merging**
