### PR TITLE
feat(paging): replace glossary list with paging

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1136

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1199)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: but Entry.js file has only whitespace changes. Not sure what happen there.

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### feat\(paging\): replace glossary list with paging
> 
> https://zanata.atlassian.net/browse/ZNTA-1136
> 
> 
> 
</details>


---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1199#-:-KJrwkyqT0tqfXNH9sWj:-1253286079)*

**Comment by aeng** [comment]
Its corrected format, space before `/>`

<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> :lgtm: but Entry.js file has only whitespace changes. Not sure what happen there.
</details>


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1199#-:-KJsAGHK0RlMjNT4ClnK:-980919175)*

**Comment by djansen-redhat** [comment]
It seems you can trick the paging to show the wrong items if you click the < or > buttons quickly enough.
e.g. I clicked > twice slowly to page 3, then quickly back two pages. It showed items for page 2, but the counter was on 1.

**Comment by djansen-redhat** [comment]
Reviewed 3 of 5 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1199)*

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. I suggest an RFE of allowing the user to select the page length.

**Comment by djansen-redhat** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1199)*

**Pull request merged**
