### PR TITLE
Fix 'restore default' for editor

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=895881

### CODE REVIEW

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by huangp** [comment]
:+1:

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
- [ ] Missing release note

**Comment by definite** [comment]
Note that "Show reference translations from <language>" is not restored.

**Comment by definite** [comment]
:+1:

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/a0152f0726f0fca4d41482f30db67339a36c9564

**Pull request closed without merging**
