### PR TITLE
fix(terms url):fix invalid default terms url

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-817

### CODE REVIEW

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by definite** [comment]
:+1:

**Comment by aeng** [comment]
Merged into release. https://github.com/zanata/zanata-server/commit/3b8cf7e72a528f47cc43667b15707fa130f7c48a

**Pull request closed without merging**
