### PR TITLE
Fix global messages in password reset page

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1191779

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:question: Does this actually fix the problem? It tells them they aren't activated, but they still cannot recover their account - i.e. resend the activation email to the given address or something.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/b319ce824c4fd49ce86b2814f17977b2bb16eae8

**Comment by seanf** [comment]
@aeng Unfortunately, the validator doesn't pick up validation annotations on fields, only on getter methods.  See https://github.com/zanata/zanata-server/pull/699

**Comment by seanf** [comment]
@aeng correction; looks like the field annotations are okay, but the tests did need to be updated, which is in #699.

**Comment by aeng** [comment]
@seanf thanks for that.

**Pull request closed without merging**
