### PR TITLE
Upgrade Liquibase, remove workaround for startup warnings

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:+1: 
So, what is this liquibase upgrade giving us?

**Comment by seanf** [comment]
It's only a Z version update. Just bug fixes, slight lowering of tech debt
(ie keeping dependencies up to date), and we can remove a workaround in the
form of a dummy class which lives in the
package 'org.eclipse.jetty.server.handler'.



On 1 March 2016 at 08:29, Carlos Munoz <notifications@github.com> wrote:

> [image: :+1:]
> So, what is this liquibase upgrade giving us?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zanata/zanata-server/pull/1102#issuecomment-190429021>
> .
>



-- 
Sean Flanigan

Principal Software Engineer
Globalisation Tools Engineering
Red Hat

**Comment by djansen-redhat** [comment]
If Zanata's tests still pass, I'm fine with this.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
The build failed, but only because the Jenkins workspace cleanup plugin had a problem cleaning up at the end.  All the tests passed.

**Pull request merged**
