### PR TITLE
Migrate js alert and js confirm for admin pages

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1283

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1256)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-war/src/main/java/org/zanata/action/RoleAssignmentRuleAction.java, line 98 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1256#-KNiyi5jgC9eqopJc52M:-KNiyi5jgC9eqopJc52N:724544405) ([raw file](https://github.com/zanata/zanata-server/blob/327b7bb664a72ddadda54a4d26be907d6a3e4d62/zanata-war/src/main/java/org/zanata/action/RoleAssignmentRuleAction.java#L98)):*
> ```Java
>     }
> 
>     public void remove(String id) {
> ```

Are we able to make this parameter Long type? Will JSF convert it for us? I know JAX-RS can but not sure about JSF

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1256)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[zanata-war/src/main/java/org/zanata/action/RoleAssignmentRuleAction.java, line 98 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1256#-KNiyi5jgC9eqopJc52M:-KNizutQ2hGWYkZQzANr:-653506845) ([raw file](https://github.com/zanata/zanata-server/blob/327b7bb664a72ddadda54a4d26be907d6a3e4d62/zanata-war/src/main/java/org/zanata/action/RoleAssignmentRuleAction.java#L98)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Are we able to make this parameter Long type? Will JSF convert it for us? I know JAX-RS can but not sure about JSF
</details>
Tried it, does not work.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1256)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Review status: 8 of 9 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1256#-:-KNj2WfGOyNkDayClgJl:7167892)*

**Comment by aeng** [comment]
Moved to https://github.com/zanata/zanata-server/pull/1259 targetting release branch

**Pull request closed without merging**
