### PR TITLE
Remove change of 'Approved' to 'Translated' status

### PR DESCRIPTION
**Pull request by aeng**
Remove change of 'Approved' to 'Translated' status in a non require review project.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/849" target="_blank">ReviewNinja

**Comment by huangp** [comment]
:+1:

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. :+1:

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/a6c3f139ada0fdb95e27c329ed7ac3e12bab73e0

**Pull request closed without merging**
