### PR TITLE
fix(login redirect): prevent redirect to login page after login

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-815

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:+1:

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
:+1:

**Comment by aeng** [comment]
Merged into release. https://github.com/zanata/zanata-server/commit/d064326e53d2b0ffde92099f6ac6ee345c4dcfe3

**Pull request closed without merging**
