### PR TITLE
fix(ZNTA-1112): remove messages prior to openid auth

### PR DESCRIPTION
**Pull request by carlosmunoz**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1242)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
This PR replaced https://github.com/zanata/zanata-server/pull/1239 to target the release branch instead

**Comment by carlosmunoz** [comment]
@djansen-redhat Sorry for the double work. Please re-do the checks you deem necessary.

**Comment by djansen-redhat** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1242)*

**Comment by djansen-redhat** [comment]
:white_check_mark: All good @carlosmunoz

**Pull request merged**
