### PR TITLE
fix(glossary): update list after delete glossary entry

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1138

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1196)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm:

<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> #### fix\(glossary\): update list after delete glossary entry
> 
> https://zanata.atlassian.net/browse/ZNTA-1138
> 
> 
> 
</details>


---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1196#-:-KJnAQs-bcbQGPvRi29Z:1417088721)*

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
Reviewed 1 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1196)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: tested (db831e2f787ccaa4260a92225d92e026abdcc9db)

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
All good.

**Pull request merged**
