### PR TITLE
Add a new parameter includeAutomatedEntry to API getContributionStatistics

### PR DESCRIPTION
**Pull request by daisy-ycguo**
This is a patch related to https://github.com/zanata/zanata-api/pull/36.

Add a new parameter to getContributionStatistic API.
The parameter is a boolean type to control whether to include automatic entries of translation into statistic.

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins ok to test

**Comment by seanf** [comment]
:+1: The change looks good, but note that the modified server only works with the modified api, so naturally the build server fails the build. The changes have to be tested together.

**Comment by djansen-redhat** [comment]
Needs update to src/test/java/org/zanata/rest/service/StatisticsServiceImplTest.java - functions are missing the added parameter.

**Comment by aeng** [comment]
ok

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, waiting for green light and Reviewed label

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Pull request merged**
