### PR TITLE
Update 'no admin user' warning to refer to system properties

### PR DESCRIPTION
**Pull request by djansen-redhat**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1186)

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:lgtm:
Thanks, good catch.

<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary>
> #### Update &#39;no admin user&#39; warning to refer to system properties
</details>


---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1186#-:-KIeZW58h_g8AuXZ94my:-257951904)*

**Comment by djansen-redhat** [comment]
@anipeter please test (easy one, just start Zanata on an empty database)

**Comment by anipeter** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
verified and confirmed :+1:

**Comment by djansen-redhat** [comment]
Thanks @anipeter

**Pull request merged**
