### PR TITLE
Use github URL for war download

### PR DESCRIPTION
**Pull request by definite**
chore(installer): use github for war download

### CODE REVIEW

**Comment by carlosmunoz** [comment]
:+1: Looks good. Tried the url for 3.7.1 and it works.

**Comment by seanf** [comment]
@definite Good, but remember: git != github.com.

You could try the new scheme for commit messages:

    chore(installer): use github for war download

or perhaps

    chore(installer): download zanata.war from github

**Comment by djansen-redhat** [comment]
@definite was there a response to @seanf's comment?

**Comment by definite** [comment]
Title and description revised to according to @seanf's request.

**Comment by seanf** [comment]
@definite Could you please reword the commit message too?

**Comment by definite** [comment]
To test this:
1. Install gradle (it is in Fedora, but not in RHEL/EPEL)
2. cd to zanata-server
3. Generate overlay zip by

    git checkout use-github-for-war-download
    cd zanata-overlay
    gradle package

there will be two .zip: 
 * zanata-<version>-eap-6.zip
 * zanata-<version>-wildfly-9.zip

4. Unzip eap zip and run

    unzip -x zanata-<version>-eap-6.zip -d /tmp
    bash /tmp/bin/zanata-installer/install.sh
   
5. You can verify this if WAR download URL is from github and download successfully.

**Comment by definite** [comment]
@seanf I cannot change the commit message without changing the checksum. Should I proceed?

**Comment by definite** [comment]
After discuss, we decide to make the overlay as part of release process. That is, end-user no longer need to download the WAR file when the run the installation script. The WAR  file should be included in the archive.

**Comment by definite** [comment]
That make this pull request invalid, I'll close this PR.

**Pull request closed without merging**
