### PR TITLE
Fix inactive account redirection with openid account

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1191827

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
I think the builds got confused...

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/a828049979c44bab4d0415ac8784afacf35f04b7

**Pull request closed without merging**
