### PR TITLE
ZNTA-421 Swap TM highlighting

### PR DESCRIPTION
**Pull request by kathryngo**
https://zanata.atlassian.net/browse/ZNTA-421

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1296)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 2 of 15 files at r1.
Review status: 2 of 15 files reviewed at latest revision, 13 unresolved discussions.

---

*[pom.xml, line 2189 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4mDn0aY9UaYl9vHjh:-KS4mDn0aY9UaYl9vHji:b-5qkw85) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/pom.xml#L2189)):*
> ```XML
>     <module>zanata-war</module>
>     <module>zanata-test-war</module>
>     
> ```

Uncomment 

---

*[zanata-war/pom.xml, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4mO_08HYeA-oSW3Ua:-KS4mO_1u2NWbS21FTCG:b81kjgm) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/pom.xml#L25)):*
> ```XML
>     <war.config.dir>${basedir}/src/etc</war.config.dir>
>     <allow.deploy.skip>true</allow.deploy.skip>
>     
> ```

check with the original, try not to change whitespaces.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml, line 17 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4mWhyB2O4kCqWYbiy:-KS4mWhzVzxnzvz3SGFs:b81kjgm) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml#L17)):*
> ```XML
>     }
> ```

check with the original, try not to change whitespaces.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml, line 62 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4mldwlVYwN452Q2Vx:-KS4mldwlVYwN452Q2Vy:b7ue9j9) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml#L62)):*
> ```XML
>     </ul>
>     <ul class="list--horizontal l--push-all-quarter legend">
>       <li class="inline zeta">TM Diff Highlighting</li>
> ```

is `inline` new class? you can use `bx--inline` from assets

---

*[zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/README.txt, line 2 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4nFRFamYrxPnyABBu:-KS4nFRFamYrxPnyABBv:b-lrke5) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/README.txt#L2)):*
> ```
> Diff, Match and Patch Library
> http://code.google.com/p/google-diff-delete-patch/
> ```

Should not change this file

---

*[zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/demos/demo_diff.html, line 25 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4nq-OkTgvrEHCoDvt:-KS4nq-OkTgvrEHCoDvu:b-eq02p3) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/demos/demo_diff.html#L25)):*
> ```HTML
> 
>   function launch() {
>     var oldtext = document.getElementById('oldtext').value;
> ```

Should not change anything under /demos directory

---

*[zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/demos/demo_match.html, line 117 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4na5uCN6F3Tf-IHvv:-KS4na5uCN6F3Tf-IHvw:b-eq02p3) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/demos/demo_match.html#L117)):*
> ```HTML
> 
> <HR>
> Back to <A HREF="http://code.google.com/p/google-diff-delete-patch/">Diff, Match
> ```

Should not change anything under /demos directory

---

*[zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/demos/demo_patch.html, line 37 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4nwgHHtksoBDfhAX3:-KS4nwgHHtksoBDfhAX4:b-eq02p3) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/demos/demo_patch.html#L37)):*
> ```HTML
> 
>   function diff_launch() {
>     var oldtext = document.getElementById('oldtexta').value;
> ```

Should not change anything under /demos directory

---

*[zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/javascript/diff_match_patch.js, line 23 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4o2MxfMsfGAsVxMqg:-KS4o2MySJ4rDPZkmUJj:b-lrke5) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/javascript/diff_match_patch.js#L23)):*
> ```JavaScript
> diff_match_patch.prototype.diff_cleanupEfficiency=function(a){for(var b=false,c=[],d=0,e="",f=0,g=false,h=false,j=false,i=false;f<a.length;){if(a[f][0]==0)a[f][1].length<this.Diff_EditCost&&(j||i)?(c[d++]=f,g=j,h=i,e=a[f][1]):(d=0,e=""),j=i=false;else if(a[f][0]==-1?i=true:j=true,e&&(g&&h&&j&&i||e.length<this.Diff_EditCost/2&&g+h+j+i==3))a.splice(c[d-1],0,[-1,e]),a[c[d-1]+1][0]=1,d--,e="",g&&h?(j=i=true,d=0):(d--,f=d>0?c[d-1]:-1,j=i=false),b=true;f++}b&&this.diff_cleanupMerge(a)};
> diff_match_patch.prototype.diff_cleanupMerge=function(a){a.push([0,""]);for(var b=0,c=0,d=0,e="",f="",g;b<a.length;)switch(a[b][0]){case 1:d++;f+=a[b][1];b++;break;case -1:c++;e+=a[b][1];b++;break;case 0:c+d>1?(c!==0&&d!==0&&(g=this.diff_commonPrefix(f,e),g!==0&&(b-c-d>0&&a[b-c-d-1][0]==0?a[b-c-d-1][1]+=f.substring(0,g):(a.splice(0,0,[0,f.substring(0,g)]),b++),f=f.substring(g),e=e.substring(g)),g=this.diff_commonSuffix(f,e),g!==0&&(a[b][1]=f.substring(f.length-g)+a[b][1],f=f.substring(0,f.length-
> g),e=e.substring(0,e.length-g))),c===0?a.splice(b-c-d,c+d,[1,f]):d===0?a.splice(b-c-d,c+d,[-1,e]):a.splice(b-c-d,c+d,[-1,e],[1,f]),b=b-c-d+(c?1:0)+(d?1:0)+1):b!==0&&a[b-1][0]==0?(a[b-1][1]+=a[b][1],a.splice(b,1)):b++,c=d=0,f=e=""}a[a.length-1][1]===""&&a.pop();c=false;for(b=1;b<a.length-1;)a[b-1][0]==0&&a[b+1][0]==0&&(a[b][1].substring(a[b][1].length-a[b-1][1].length)==a[b-1][1]?(a[b][1]=a[b-1][1]+a[b][1].substring(0,a[b][1].length-a[b-1][1].length),a[b+1][1]=a[b-1][1]+a[b+1][1],a.splice(b-1,1),c=
> ```

Should not change this file

---

*[zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/javascript/diff_match_patch_test.html, line 1 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4o5zd0BbudezfeqtM:-KS4o5zd0BbudezfeqtN:b-lrke5) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/javascript/diff_match_patch_test.html#L1)):*
> ```HTML
> <!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
> ```

Should not change this file

---

*[zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/javascript/diff_match_patch_test.js, line 2 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4o7NZsG9dip8itkSf:-KS4o7NZsG9dip8itkSg:b-lrke5) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/javascript/diff_match_patch_test.js#L2)):*
> ```JavaScript
> /**
>  * Test Harness for Diff Match and Patch
> ```

Should not change this file

---

*[zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/javascript/diff_match_patch_uncompressed.js, line 4 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4o8hqChLeNVXNkpBB:-KS4o8hqChLeNVXNkpBC:b-lrke5) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/resources/org/zanata/webtrans/public/diff_match_patch/javascript/diff_match_patch_uncompressed.js#L4)):*
> ```JavaScript
>  * Diff Match and Patch
>  *
>  * Copyright 2006 Google Inc.
> ```

Should not change this file

---

*[zanata-war/src/test/java/org/zanata/rest/service/ResourceUtilsTest.java, line 89 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4oCh1Us2zddYaAmBN:-KS4oCh1Us2zddYaAmBO:b293tnx) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/test/java/org/zanata/rest/service/ResourceUtilsTest.java#L89)):*
> ```Java
>     @Test
>     public void mergeTextFlowWithOneFromChange() {
>         List<TextFlow> from = new ArrayList<TextFlow>();
> ```

Don't think you need to change this file too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1296)*

**Comment by seanf** [comment]
Reviewed 8 of 15 files at r1, 7 of 7 files at r2.
Review status: all files reviewed at latest revision, 19 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4wtdyiHG5tZcVwdgI:-KS4wtdyiHG5tZcVwdgJ:b-11kafa) (no related file):*
Other than minor styling changes (eg removing strike-through), I wouldn't expect this bug-fix to require any changes to the logic except: 

* refactoring "text1, text2", to "oldText, newText" - ie renaming only, no swapping
* swapping the comparison order in one, maybe two methods - possibly just `org.zanata.webtrans.client.view.TransMemoryView#createSourcePanel`

The highlighting colour was already correct for translation histories, wasn't it? (I can't remember for sure.) If we keep the logic changes to a bare minimum, it should be easier to avoid breaking the translation history view by accident.

---

*[functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java, line 536 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4ttUj7BQzuwhc5zWC:-KS4ttUkiv8TM2Wkg5I-:bdhxrau) ([raw file](https://github.com/zanata/zanata-server/blob/754601db195b36028a3f2c8367f4e2d870060506/functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java#L536)):*
> ```Java
>         for (WebElement element : getCompareTabEntries()) {
>             for (WebElement diffElement : element.findElements(By.className("diff-delete"))) {
>                 diffs.add("++" + diffElement.getText());
> ```

I don't remember what this code does, but associating "delete" with "++", and "insert" with "--" seems more confusing.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml, line 34 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4uDh49bj2h30_F_W-:-KS4uDh5aQh81Z7dQl0g:bmwu7ty) ([raw file](https://github.com/zanata/zanata-server/blob/754601db195b36028a3f2c8367f4e2d870060506/zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml#L34)):*
> ```XML
>         <tr>
>           <td class="diff-delete">
>             <ui:text from="{messages.greenColor}" />
> ```

I think this will be more confusing: delete should be red, and insert should be green. If things are coming back as deleted when they should be inserted, that's what we need to change.

I think the real problem might be in `org.zanata.webtrans.client.view.TransMemoryView#createSourcePanel` which calls `org.zanata.webtrans.client.ui.TextContentsDisplay#asDiff(originalContents, diffContents)` with (queriesPadded, sourceContents). (With a similar problem a few lines down calling asDiffHighlight.)


queriesPadded is presumably the currentText being queried, and sourceContents seems to be the TM-match's text, so that call would appear to be the wrong way around.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 77 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4uXwYiMMNv9Wwi9bt:-KS4uXwYiMMNv9Wwi9bu:b4ak9ee) ([raw file](https://github.com/zanata/zanata-server/blob/754601db195b36028a3f2c8367f4e2d870060506/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L77)):*
> ```Java
>     }-*/;
> 
>     public static String diffAsHtml(String text2, String text1) {
> ```

I think these methods (diffAsHtml, diff, diffAsHighlight)  should stay as "text1, text2", or better still, change to "oldText, newText".

They shouldn't change to "text2, text1".

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 117 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4uvLwSVzWRgfPr-QO:-KS4uvLwSVzWRgfPr-QP:b-a5fgn7) ([raw file](https://github.com/zanata/zanata-server/blob/754601db195b36028a3f2c8367f4e2d870060506/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L117)):*
> ```Java
>       case $wnd['DIFF_INSERT']:
>         html[x] = '<ins class="diff-insert">' + text + '</ins>';
>         break;
> ```

There doesn't seem to be any reason to move this.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 150 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4v5tC9j5aDon_FO5F:-KS4v5tC9j5aDon_FO5G:b-kcdd8g) ([raw file](https://github.com/zanata/zanata-server/blob/106e478c5a5b70bb10409e51d1129d59c9e90d44/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L150)):*
> ```Java
>         html[x] = text;
>         break;
>       case $wnd['DIFF_DELETE']:
> ```

Again, there doesn't seem to be a reason to change the order. Plus the formatting of "switch (op) {" has been changed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1296)*

**Comment by kathryngo** [comment]
*[functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java, line 536 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4ttUj7BQzuwhc5zWC:-KS8s6ZVmjVQCXyF251r:b3h3uvo) ([raw file](https://github.com/zanata/zanata-server/blob/754601db195b36028a3f2c8367f4e2d870060506/functional-test/src/main/java/org/zanata/page/webtrans/EditorPage.java#L536)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I don't remember what this code does, but associating "delete" with "++", and "insert" with "--" seems more confusing.
</details>
Since pulling a new version of master, this has been resolved.  diff-insert uses add ++, and diff-delete uses --

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1296)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml, line 62 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4mldwlVYwN452Q2Vx:-KS8tNVlw6_CZgi1p3Rw:bcyrmgs) ([raw file](https://github.com/zanata/zanata-server/blob/94c51e2fe4b5f7be796ac5dea42173804e3270ed/zanata-war/src/main/java/org/zanata/webtrans/client/view/TransMemoryView.ui.xml#L62)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> is `inline` new class? you can use `bx--inline` from assets
</details>
Thanks. I'll make sure to remove my inline class from the assets css too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1296)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml, line 34 at r2](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-KS4uDh49bj2h30_F_W-:-KS8tusCAjvLb6PeVvkB:b-ruxxe7) ([raw file](https://github.com/zanata/zanata-server/blob/754601db195b36028a3f2c8367f4e2d870060506/zanata-war/src/main/java/org/zanata/webtrans/client/ui/DiffColorLegendPanel.ui.xml#L34)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I think this will be more confusing: delete should be red, and insert should be green. If things are coming back as deleted when they should be inserted, that's what we need to change.
> 
> I think the real problem might be in `org.zanata.webtrans.client.view.TransMemoryView#createSourcePanel` which calls `org.zanata.webtrans.client.ui.TextContentsDisplay#asDiff(originalContents, diffContents)` with (queriesPadded, sourceContents). (With a similar problem a few lines down calling asDiffHighlight.)
> 
> 
> queriesPadded is presumably the currentText being queried, and sourceContents seems to be the TM-match's text, so that call would appear to be the wrong way around.
</details>
Like most of these issues, it has been resolved with a fresh pull of master and just swapping queriesPadded and sourceContents

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1296)*

**Comment by kathryngo** [comment]
Since this pull request is an absolute mess, I have created a new branch and ensured that the changes you have flagged below have been made (although most weren't needed)

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1296#-:-KS91LMTd817Wl64eF-t:b4phwy3)*

**Comment by kathryngo** [comment]
I have created a new pull request (TM-highlight-2) so I shall close this one.

**Pull request closed without merging**
