### PR TITLE
chore(dependency): update version for server-3.8.0

### PR DESCRIPTION
**Pull request by definite**
Point zanata dependency to the one that in integration/master

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, just waiting on Jenkins

**Comment by djansen-redhat** [comment]
It appears that this upgrade breaks things, e.g. the Delete button in project settings

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Pull request merged**
