### PR TITLE
disable rendering in filter list if empty string

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1190557

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
- [ ] Spaces actually affect the behaviour (i.e. will filter for documents with a space) so using trim() breaks the Cancel if the user entered a space.  I suggest Cancel clears the field if there is anything in there.

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/51fd4b3e3c756b831026f9e01682edebd9fd40b1

**Pull request closed without merging**
