### PR TITLE
Fix the 404 page

### PR DESCRIPTION
**Pull request by djansen-redhat**
Template used by 404 page was removed, update to existing template.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1198)

### CODE REVIEW

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1198)*

**Comment by aeng** [comment]
:lgtm:

<details><summary><i>Previously, djansen-redhat (Damian Jansen) wrote…</i></summary>
> #### Fix the 404 page
> 
> Template used by 404 page was removed, update to existing template.
> 
> 
> 
</details>


---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1198#-:-KJnnhEKg2v_RezHJd6F:1417088721)*

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
:+1:

**Pull request merged**
