### PR TITLE
update docker script

### PR DESCRIPTION
**Pull request by huangp**
update docker image file and docker run script:
- docker image will create a mysql module and use that. No more jar file to deploy.
- map a folder as docker volume to jboss deployments folder. Now you can just hard link your war file to that folder. Rebuild the war will get automatically picked up by jboss. Deploying exploded war is also possible.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

- it will map a docker volume to JBoss deployments folder
- the image will use a mysql module

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1314)

### CODE REVIEW

**Comment by seanf** [comment]
Reviewed 2 of 5 files at r1.
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/README.md, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRYEl1ZLJiJau5u3gc:-KTRYEl1ZLJiJau5u3gd:b-mdb0mb) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/README.md#L81)):*
> ```Markdown
> This container will have a mapped volume to your `$HOME/docker-volumes/zanata` directory to store files, stats, caches, etc. This will allow for backups if you wish to switch between different versions of zanata for instance.
> 
> This container will also map `$HOME/docker-volumes/zanata-deployments` directory to the container's JBoss deployments directory.
> ```

`docker-volumes` lives under `$HOME` because it contains long-lived data. I'm not sure zanata-deployments is in that category. It might be better if it lived under `target/`. 

In fact, isn't there some way you could map `zanata-war/target/zanata/` (ie the exploded directory which is created during the build process) directly into the docker container for deployment?

---

*[docker/rundev.sh, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXkg48cJtXy3oIFrF:-KTRXkg48cJtXy3oIFrG:b-5ev6do) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/rundev.sh#L24)):*
> ```Shell
>     echo "===== Please copy or hard link your $ZANATA_WAR file to $ZANATA_DEPLOYMENTS_DIR"
> #    we can not use symlink as JBoss inside docker can't properly read the symlink file
>     echo "- linux : ln $ZANATA_WAR $ZANATA_DEPLOYMENTS_DIR/ROOT.war"
> ```

Why doesn't the script do this automatically? Until now, if you had compiled zanata.war, you just had to invoke `./rundev.sh`. We should make sure that still works for the common case.

---

*[docker/rundev.sh, line 63 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXQGuS-vbyexEl7VK:-KTRXQGuS-vbyexEl7VL:b1ws0gz) ([raw file](https://github.com/zanata/zanata-server/blob/2713672f1be0909567c181de2fce258fb14f2608/docker/rundev.sh#L63)):*
> ```Shell
> # create the data directory and set permissions (SELinux)
> mkdir -p $ZANATA_DIR && chcon -Rt svirt_sandbox_file_t "$ZANATA_DIR"
> # make zanata directory and standalone.xml file accessible to docker containers (SELinux)
> ```

I think we should keep this comment. It should probably appear *above* the `chcon` command.

---

*[docker/conf/standalone.xml, line 473 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXJIEwyMbhbvp3G4v:-KTRXJIEwyMbhbvp3G4w:b-zbhsjw) ([raw file](https://github.com/zanata/zanata-server/blob/2713672f1be0909567c181de2fce258fb14f2608/docker/conf/standalone.xml#L473)):*
> ```XML
>                 value="${zanata.file.directory}"/>
>               <lookup name="java:jboss/exported/zanata/files/document-storage-directory"
>                 lookup="java:global/zanata/files/document-storage-directory"/>
> ```

Don't we need this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by huangp** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/README.md, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRYEl1ZLJiJau5u3gc:-KTRhdPviww3nUPtRzi_:b7i3mzr) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/README.md#L81)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> `docker-volumes` lives under `$HOME` because it contains long-lived data. I'm not sure zanata-deployments is in that category. It might be better if it lived under `target/`. 
> 
> In fact, isn't there some way you could map `zanata-war/target/zanata/` (ie the exploded directory which is created during the build process) directly into the docker container for deployment?
</details>
If it lives under target/, it defeat the purpose of having a running container but deploy/redeploy artifact from different build. If you run mvn clean, it will delete the folder and I am not sure what that will do to a running JBoss. After recreating the folder, we need to rerun chcon for it to work. It's just a hard link for the war file so no space wasted.

---

*[docker/rundev.sh, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXkg48cJtXy3oIFrF:-KTRi9SqQFrw0GT8Tvss:b-9ambr5) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/rundev.sh#L24)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Why doesn't the script do this automatically? Until now, if you had compiled zanata.war, you just had to invoke `./rundev.sh`. We should make sure that still works for the common case.
</details>
I remember your previous comment was this is fedora/linux specific.  I thought I might let the option open (e.g. deploy under different context name, multiple artifacts, exploded war)

---

*[docker/conf/standalone.xml, line 473 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXJIEwyMbhbvp3G4v:-KTRipMOqODS-Gv28xLM:bn9k6lj) ([raw file](https://github.com/zanata/zanata-server/blob/2713672f1be0909567c181de2fce258fb14f2608/docker/conf/standalone.xml#L473)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Don't we need this?
</details>
We switched to use system properties. This is generating a warning on startup as one of the variable is not set (zanata.security.adminusers). I just checked release branch, it's still using jndi so I will revert this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by huangp** [comment]
Review status: 2 of 5 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/rundev.sh, line 63 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXQGuS-vbyexEl7VK:-KTRp9BxHajlEOoiKwVg:b-896fix) ([raw file](https://github.com/zanata/zanata-server/blob/2713672f1be0909567c181de2fce258fb14f2608/docker/rundev.sh#L63)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I think we should keep this comment. It should probably appear *above* the `chcon` command.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by seanf** [comment]
Reviewed 1 of 2 files at r2.
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docker/README.md, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRYEl1ZLJiJau5u3gc:-KTl55ywLwZm8YvAJDAo:b-oho1mf) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/README.md#L81)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> If it lives under target/, it defeat the purpose of having a running container but deploy/redeploy artifact from different build. If you run mvn clean, it will delete the folder and I am not sure what that will do to a running JBoss. After recreating the folder, we need to rerun chcon for it to work. It's just a hard link for the war file so no space wasted.
</details>
If you want to switch branches, it doesn't seem like much of an imposition to stop and start the container. And if you want to do exploded deployment, why would you be using mvn clean?

---

*[docker/rundev.sh, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXkg48cJtXy3oIFrF:-KTl5Q7CdcHguZ9Cc3Cn:bu5ucap) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/rundev.sh#L24)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I remember your previous comment was this is fedora/linux specific.  I thought I might let the option open (e.g. deploy under different context name, multiple artifacts, exploded war)
</details>
Which previous comment?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by huangp** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docker/README.md, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRYEl1ZLJiJau5u3gc:-KTl6IUFGEZXMkUbuGrH:b-l9zpy4) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/README.md#L81)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> If you want to switch branches, it doesn't seem like much of an imposition to stop and start the container. And if you want to do exploded deployment, why would you be using mvn clean?
</details>
Not just switching branch. You could be in development process and constantly changing your code and want to see the effect. Right now, you will need to stop and restart your container every time. This will enable you leave the container running but just rebuilt (with mvn clean) and redeploy the war/exploded war. Nothing wrong with mvn clean when using exploded war.

---

*[docker/rundev.sh, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXkg48cJtXy3oIFrF:-KTl6sHaF7HSXv-2qPdE:bj8ii5c) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/rundev.sh#L24)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Which previous comment?
</details>
https://github.com/zanata/zanata-server/pull/1311#issuecomment-251558321 last sentence. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by huangp** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docker/README.md, line 81 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRYEl1ZLJiJau5u3gc:-KTl7BhgqNktLVo3f92w:b-vukywa) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/README.md#L81)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Not just switching branch. You could be in development process and constantly changing your code and want to see the effect. Right now, you will need to stop and restart your container every time. This will enable you leave the container running but just rebuilt (with mvn clean) and redeploy the war/exploded war. Nothing wrong with mvn clean when using exploded war.
</details>
see also https://trello.com/c/iQOBhUyr/13-no-redeploy-to-docker-dev-server-lost-time-on-manual-process

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by seanf** [comment]
*[docker/rundev.sh, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXkg48cJtXy3oIFrF:-KTl8Dfi4rLajHsVgD_n:b-poxc6b) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/rundev.sh#L24)):*
You mean this:
>> ln -sf /usr/share/java/mysql-connector-java.jar ${ZANATA_DEPLOYMENTS_DIR}/mysql-connector-java.jar
> This seems very Fedora specific. Kind of defeats the point of using Docker.

This was a reference to the Fedora-specific path `/usr/share/java/mysql-connector-java.jar` not the idea of symlinking. Anyone with `docker` should have the `ln` command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by huangp** [comment]
Review status: 3 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[docker/rundev.sh, line 24 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTRXkg48cJtXy3oIFrF:-KTlL_dUZMMbnF3t9AY4:b-896fix) ([raw file](https://github.com/zanata/zanata-server/blob/9b51b1dca3e3521d28b3b5d668fbb91ffb062029/docker/rundev.sh#L24)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> You mean this:
> >> ln -sf /usr/share/java/mysql-connector-java.jar ${ZANATA_DEPLOYMENTS_DIR}/mysql-connector-java.jar
> > This seems very Fedora specific. Kind of defeats the point of using Docker.
> 
> This was a reference to the Fedora-specific path `/usr/share/java/mysql-connector-java.jar` not the idea of symlinking. Anyone with `docker` should have the `ln` command.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by seanf** [comment]
Reviewed 1 of 5 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[docker/rundev.sh, line 23 at r3](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTld-6WF1G4WK2IhaQU:-KTld-6WF1G4WK2IhaQV:bkkgw3v) ([raw file](https://github.com/zanata/zanata-server/blob/da444a1a02992984d5b1c8d851e48ac201e91d7a/docker/rundev.sh#L23)):*
> ```Shell
> if [ -f "$ZANATA_WAR" ]
> then
>     echo "===== Please copy or hard link your $ZANATA_WAR file to $ZANATA_DEPLOYMENTS_DIR"
> ```

This needs to be updated.

---

*[docker/rundev.sh, line 28 at r3](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTld80xh271nRPL8jnH:-KTld80xh271nRPL8jnI:b76bend) ([raw file](https://github.com/zanata/zanata-server/blob/da444a1a02992984d5b1c8d851e48ac201e91d7a/docker/rundev.sh#L28)):*
> ```Shell
>     ln ${ZANATA_WAR} ${ZANATA_DEPLOYMENTS_DIR}/ROOT.war || cp ${ZANATA_WAR} ${ZANATA_DEPLOYMENTS_DIR}/ROOT.war
> else
>     echo "===== NO war file found. Please build Zanata war first then hard link/copy it to $ZANATA_DEPLOYMENTS_DIR/ROOT.war ====="
> ```

This could probably be changed back now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by huangp** [comment]
Review status: 4 of 5 files reviewed at latest revision, 2 unresolved discussions.

---

*[docker/rundev.sh, line 23 at r3](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTld-6WF1G4WK2IhaQU:-KTlxbhcVJn3sB0Rrpef:b-896fix) ([raw file](https://github.com/zanata/zanata-server/blob/da444a1a02992984d5b1c8d851e48ac201e91d7a/docker/rundev.sh#L23)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> This needs to be updated.
</details>
Done.

---

*[docker/rundev.sh, line 28 at r3](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTld80xh271nRPL8jnH:-KTlxcB9jmFRu7OfufTY:b-896fix) ([raw file](https://github.com/zanata/zanata-server/blob/da444a1a02992984d5b1c8d851e48ac201e91d7a/docker/rundev.sh#L28)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> This could probably be changed back now.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by seanf** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker/rundev.sh, line 25 at r4](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTmb35coMjpLSu8am1S:-KTmb35coMjpLSu8am1T:b-mfua81) ([raw file](https://github.com/zanata/zanata-server/blob/dc2cad10552fc848fd0d7a9f2eb6583461e0e726/docker/rundev.sh#L25)):*
> ```Shell
> #    we can not use symlink as JBoss inside docker can't properly read the symlink file
>     # try to link or copy the war file to deployments directory
>     ln ${ZANATA_WAR} ${ZANATA_DEPLOYMENTS_DIR}/ROOT.war || cp ${ZANATA_WAR} ${ZANATA_DEPLOYMENTS_DIR}/ROOT.war
> ```

If you already have `ROOT.war` in the zanata-deployments directory (eg from running `rundev.sh` in another working directory), the script fails to install the new war file:

    + ln /home/sflaniga/NotBackedUp/src/zanata-root/server/zanata-war/target/zanata-4.0.0-SNAPSHOT.war /home/sflaniga/docker-volumes/zanata-deployments/ROOT.war
    ln: failed to create hard link ‘/home/sflaniga/docker-volumes/zanata-deployments/ROOT.war’: File exists

We should probably have this at the top, to fail in case of error:

      #!/bin/bash -ex

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by huangp** [comment]
Review status: 4 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker/rundev.sh, line 25 at r4](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-KTmb35coMjpLSu8am1S:-KTrXyGA9eYDH5D37uVd:b-896fix) ([raw file](https://github.com/zanata/zanata-server/blob/dc2cad10552fc848fd0d7a9f2eb6583461e0e726/docker/rundev.sh#L25)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> If you already have `ROOT.war` in the zanata-deployments directory (eg from running `rundev.sh` in another working directory), the script fails to install the new war file:
> 
>     + ln /home/sflaniga/NotBackedUp/src/zanata-root/server/zanata-war/target/zanata-4.0.0-SNAPSHOT.war /home/sflaniga/docker-volumes/zanata-deployments/ROOT.war
>     ln: failed to create hard link ‘/home/sflaniga/docker-volumes/zanata-deployments/ROOT.war’: File exists
> 
> We should probably have this at the top, to fail in case of error:
> 
>       #!/bin/bash -ex
> 
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314)*

**Comment by seanf** [comment]
:lgtm:

Although redeployments aren't working at all for me...

---

Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-:-KTvSePmJPKBMsxSvUon:b-9fttsj)*

**Comment by huangp** [comment]
01:03:35,075 INFO  [org.jboss.as.server.deployment.scanner] (DeploymentScanner-threads - 1) WFLYDS0010: Scan found incompletely copied file content for deployment /opt/jboss/wildfly/standalone/deployments/ROOT.war. Deployment changes will not be processed until all content is complete.
01:03:40,124 INFO  [org.jboss.as.repository] (DeploymentScanner-threads - 1) WFLYDR0001: Content added at location /opt/jboss/wildfly/standalone/data/content/f4/8fda61191c28ee4448d147c1cf4c1b1d1fa3e5/content


This might be the cause of all the thread leak listener interruption exception.

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1314#-:-KTv_fbt686m2GvATM6Y:b-dnk2jc)*

**Pull request merged**
