### PR TITLE
ZNTA-686 fix(editor) - fix date validator pattern

### PR DESCRIPTION
**Pull request by huangp**
https://zanata.atlassian.net/browse/ZNTA-686

### CODE REVIEW

**Comment by huangp** [comment]
Build passed http://zanata-build.lab.eng.bne.redhat.com/job/zanata-server-github-pull-requests/4473/console (failed calling github api)

**Comment by aeng** [comment]
:+1: when check passes.

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested.
The test failure ServerSettingsTest.setPiwikTest can be ignored.

**Pull request merged**
