### PR TITLE
Prepare for CDI move

### PR DESCRIPTION
**Pull request by seanf**
Part of https://bugzilla.redhat.com/show_bug.cgi?id=1094534

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@aeng would you mind reviewing this?  I think we should be able to merge this if the full functional tests pass.

**Comment by seanf** [comment]
:+1: on changes by @carlosmunoz

**Comment by seanf** [comment]
:+1: on changes by @aeng

**Comment by seanf** [comment]
@aeng you might find it easier to review my commit e22728b by itself.

**Comment by aeng** [comment]
:+1: on https://github.com/zanata/zanata-server/commit/e22728b9dbfcc8f53b240580fc7095bb72372f4c

**Comment by djansen-redhat** [comment]
:white_check_mark: Functional tests and a cursory examination indicate this can be merged with a reasonable degree of confidence

**Pull request merged**
