### PR TITLE
Disable require review option

### PR DESCRIPTION
**Pull request by aeng**
Disable require review option until https://bugzilla.redhat.com/show_bug.cgi?id=1211137 is implemented.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/830" target="_blank">ReviewNinja

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by huangp** [comment]
:+1:

**Comment by definite** [comment]
The Label "Review" is still there. Please either hide or remove it.

**Comment by definite** [comment]
:+1:

**Pull request merged**
