### PR TITLE
fix(group): fix group filtering

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1243688

### CODE REVIEW

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
Are they supposed to show to all users?  I thought only admin users are supposed to see them, but this change allows all to see them.

**Comment by aeng** [comment]
rookie mistake. Fixed in https://github.com/zanata/zanata-server/commit/ca2b4c785bc32f5904bf51eb1a51ac8ecb4684c2

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/79e3ee6c8c93461c1dc54649bbc0093390d5a5b1

**Pull request closed without merging**
