### PR TITLE
fix(merge translation):Translation merge targets the wrong source version

### PR DESCRIPTION
**Pull request by aeng**
Translation merge targets the wrong source version

https://zanata.atlassian.net/browse/ZNTA-719

### CODE REVIEW

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by huangp** [comment]
:+1:

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
The test failure in build 4779 (updateActivationEmail) can be ignored.

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
Merged into integration/master. https://github.com/zanata/zanata-server/commit/7c87b489a6dcfe741bcec209cbf71d01212d88c2

**Pull request closed without merging**
