### PR TITLE
fix(search): rhbz1244612 close EntityManagerFactory at shutdown

### PR DESCRIPTION
**Pull request by seanf**
https://bugzilla.redhat.com/show_bug.cgi?id=1244612

### CODE REVIEW

**Comment by seanf** [comment]
@carlosmunoz Could you review this PR, please?

**Comment by carlosmunoz** [comment]
:+1:

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. I *believe* this is fixed, but it's a tricky one to test.

**Pull request merged**
