### PR TITLE
fix(file project type):fix pot file download in file project type

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-811

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:+1:

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
:+1:

**Comment by aeng** [comment]
Merged into release. https://github.com/zanata/zanata-server/commit/2e364d5100b6c05215601da330e5e6349dc692dd

**Pull request closed without merging**
