### PR TITLE
feat(TM details): Add editor url to TM results

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-448

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1301)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 26 of 26 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1301#-:-KSZiooQaQJPzq8cJ-bI:b49ms4)*

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: tested.

**Comment by aeng** [comment]
Fixing failing test.

**Pull request merged**
