### PR TITLE
shrinkwrap npm modules and fix webpack build problem

### PR DESCRIPTION
**Pull request by huangp**
There is a build problem with webpack 1.9.11. I submitted an issue and got back the answer:
https://github.com/webpack/webpack/issues/1168#issuecomment-111968406

Also ran shrinkwrap to fix the npm modules so we won't have issues like this anymore (repeatable build)

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/875" target="_blank">ReviewNinja

**Comment by davidmason** [comment]
@huangp can we add a note in the readme about how to update and shrinkwrap the dependencies? Maybe just a link to this: https://docs.npmjs.com/cli/shrinkwrap#building-shrinkwrapped-packages

**Comment by davidmason** [comment]
:+1: these changes look fine

**Comment by davidmason** [comment]
:+1: for the readme change.

**Pull request merged**
