### PR TITLE
ZNTA-421 - tm-highlighting

### PR DESCRIPTION
**Pull request by aeng**
JIRA issue URL: *https://zanata.atlassian.net/browse/ZNTA-421*

*TM diff color update*

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1309)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: -(Awaiting review) +Reviewed +(On QA) 

---

Reviewed 2 of 3 files at r1, 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-:-KTHNuKPIZAo8GIx1bDu:b49ms4)*

**Comment by djansen-redhat** [comment]
- [ ] There's a change to quickbuild.sh that may not be favourable. Having clean as a non-default option would be better

- [ ] I entered a term and got a strange result, seemingly appending the matched part.
screenshot from 2016-10-06 13-51-28

- [ ] "Plain text" not aligned h'ly.
screenshot from 2016-10-06 13-51-44

- [ ] To be honest, I'm still not sure I understand the diff...

**Comment by kathryngo** [comment]
1. I will remove the clean part from quickbuild - had to put it there to get things to update properly and of course I forgot to remove it....

2. Logic issue - best for someone else to deal with this issue

3. I can fix that plain text alignment tomorrow

4. Is it the language used? It took me a while to get my head around the concept and even now I am not sure that it is clear enough.

**Comment by kathryngo** [comment]
@aeng, @seanf: changes to the pop-up legend have been made, in addition to a colour change for the legend (in assets - to improve the highlight diff legend contrast) - looks like it's ready for a check. 

Do we still need this other branch?
https://github.com/zanata/zanata-server/tree/TM-highlight-fixes
It looks really bad. A heap of language page commits with editor stuff on top. That must have been something I did by mistake.  -_-  I will make sure this does not ever happen again.

**Comment by aeng** [comment]
@kathryngo you can delete the other branch. I will look at the changes.

**Comment by huangp** [comment]
:lgtm:

---

Reviewed 4 of 7 files at r3, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-:-KTRMpDd9OzCyLWZkwYU:bnfp4nl)*

**Comment by seanf** [comment]
Reviewed 1 of 3 files at r1, 2 of 6 files at r2, 4 of 7 files at r3, 4 of 4 files at r5.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 419 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbUfp_BCfcrxm92cW:-KTRbUfp_BCfcrxm92cX:bwkcdh3) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L419)):*
> ```Java
> 
>     @DefaultMessage("Blue color")
>     String blueColor();
> ```

Why do we need a string that says "Blue color"? Is this obsolete?

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 422 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbgimlEng6qUkq-He:-KTRbginLCoMjKwQP1aE:buzpazx) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L422)):*
> ```Java
> 
>     @DefaultMessage("No match")
>     String noMatch();
> ```

Is this for the highlighting mode? Perhaps "non-matching (text)" would be clearer.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 428 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbpKz6NMjr3500-ho:-KTRbpKz6NMjr3500-hp:b-b3jbun) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L428)):*
> ```Java
> 
>     @DefaultMessage("Yellow color")
>     String yellowColor();
> ```

Obsolete?

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 434 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbqNAXpvpI4Qw29tO:-KTRbqNAXpvpI4Qw29tP:b-b3jbun) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L434)):*
> ```Java
> 
>     @DefaultMessage("Red color")
>     String redColor();
> ```

Obsolete?

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 439 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbuIdgsdp34nkO2aW:-KTRbuIdgsdp34nkO2aX:b9hl5fx) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L439)):*
> ```Java
>     String tmInsertTagDesc();
> 
>     @DefaultMessage("Text contained in result but not in search term")
> ```

Perhaps result -> TM for consistency?

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 443 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRc0flcxkD1BJNSw-C:-KTRc0flcxkD1BJNSw-D:bqjbdw9) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L443)):*
> ```Java
> 
>     @DefaultMessage("Text contained in both search term and result")
>     String tmYellowTextDesc();
> ```

Perhaps result -> TM for consistency?

Also, yellow -> highlighted or something.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 127 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbIAN6XiSMfgXY5Ii:-KTRbIAN6XiSMfgXY5Ij:b2hgfds) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L127)):*
> ```Java
> 
>     public static String diffAsHighlight(String oldText, String newText) {
>         JavaScriptObject diffs = diff(newText, oldText, false);
> ```

This doesn't seem right. Why are we swapping new and old around?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 419 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbUfp_BCfcrxm92cW:-KTRdG_62yGSoa3NIeb7:b-qlpkky) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L419)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Why do we need a string that says "Blue color"? Is this obsolete?
</details>
Obsolete, will remove.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 422 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbgimlEng6qUkq-He:-KTRdKxBBsUWoHDpwJin:b-rmko3d) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L422)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Is this for the highlighting mode? Perhaps "non-matching (text)" would be clearer.
</details>
Yes it is. Good idea.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 428 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbpKz6NMjr3500-ho:-KTRdZ50C23xRh7mZI6L:bf0lhj9) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L428)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Obsolete?
</details>
Needed for the highlight legend

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 428 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbpKz6NMjr3500-ho:-KTRevDwOffGvPwpWox-:b6dby1d) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L428)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary>
> Needed for the highlight legend
</details>
Can't we say highlighted or something? Specifying colours by name seems a bit fragile from a maintenance point of view. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 127 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbIAN6XiSMfgXY5Ii:-KTRfiYKlBokbQBbBq_2:bvd3a2p) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L127)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> This doesn't seem right. Why are we swapping new and old around?
</details>
No that does not seem right at all. I'll fix that too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 428 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbpKz6NMjr3500-ho:-KTRgdFFHZaji-BJ92Zy:b-dbdwbr) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L428)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Can't we say highlighted or something? Specifying colours by name seems a bit fragile from a maintenance point of view. 
</details>
Good point. Will do that also.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 434 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbqNAXpvpI4Qw29tO:-KTRhfi5GK3t1h8Z0ox1:b-agzz29) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L434)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Obsolete?
</details>
Incorrect text - needed for popup legends. Will fix.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java, line 127 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbIAN6XiSMfgXY5Ii:-KTS8Eub_kEbbqBEBtOL:bfviabh) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/ui/Highlighting.java#L127)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary>
> No that does not seem right at all. I'll fix that too.
</details>
Delay in pushing changes due to api build errors (on right branch, checked all my usual mistakes). I will need to spend some time on this Monday. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 419 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbUfp_BCfcrxm92cW:-KTfeLgm9m8zk-UygTY9:b-as98zm) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L419)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary>
> Obsolete, will remove.
</details>
Correction: this sets the colour of the search only legend label.  Is needed as far as I can see. I would change it to something meaningful like Search only but that is taken. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 419 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRbUfp_BCfcrxm92cW:-KTfg7X3r63BYToqgWod:b-mks35z) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L419)):*
<details><summary><i>Previously, kathryngo wrote…</i></summary>
> Correction: this sets the colour of the search only legend label.  Is needed as far as I can see. I would change it to something meaningful like Search only but that is taken. 
</details>
Changes to searchColor, red is now tmColor and yellow is highlightColor.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by kathryngo** [comment]
@seanf, changes made. ready for review.

**Comment by kathryngo** [comment]
@seanf ready for review :)

**Comment by seanf** [comment]
Reviewed 3 of 3 files at r6.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java, line 443 at r5](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-KTRc0flcxkD1BJNSw-C:-KTgWSd7VP3JkmEg1IH2:b-nc2cr7) ([raw file](https://github.com/zanata/zanata-server/blob/e2791ac41992deca51b24f0119852bb510f4595f/zanata-war/src/main/java/org/zanata/webtrans/client/resources/WebTransMessages.java#L443)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Perhaps result -> TM for consistency?
> 
> Also, yellow -> highlighted or something.
</details>
Perhaps this should be called something like `tmHighlightedTextDesc()`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309)*

**Comment by aeng** [comment]
The different label is used in Search and Replace screen. And I think now the label is broken.

**Comment by huangp** [comment]
-(Under review) 

---

Reviewed 1 of 3 files at r6, 2 of 3 files at r7, 3 of 3 files at r8.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1309#-:-KTwBmeW4EgMcAbK7-T3:b-ma1cjt)*

**Pull request merged**
