### PR TITLE
rejected state in redux  ZNTA-132

### PR DESCRIPTION
**Pull request by davidmason**
https://zanata.atlassian.net/browse/ZNTA-132

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1277)

### CODE REVIEW

**Comment by davidmason** [comment]
@aeng do you have time to review this one? I don't think it will take long.

**Comment by aeng** [comment]
looks good, :+1: when the build is green.

**Comment by aeng** [comment]
Reviewed 8 of 9 files at r1, 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1277)*

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3.
Review status: 11 of 12 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1277#-:-KQ3kkwObu1qrFfCt0Vc:bnfp4nl)*

**Comment by aeng** [comment]
Reviewed 1 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1277)*

**Comment by djansen-redhat** [comment]
- [ ] The Save As button does not show, unless the text is changed (Intended? Does not seem like it should be.)

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1277)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1277#-:-KQNaO8Or7LzOSSPMILQ:bnfp4nl)*

**Comment by davidmason** [comment]
@djansen-redhat updated so that:

 - rejected text flow that has no text change: the save button shows "Needs Work" but is disabled (consistent with needswork text flows)
 - rejected text flow that has text change: the save button shows "Translated" and is enabled
 - both "Needs Work" and "Translated" are available in the dropdown in both states

**Comment by djansen-redhat** [comment]
:white_check_mark: I like it.

**Comment by djansen-redhat** [comment]
Reviewed 2 of 2 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1277)*

**Pull request merged**
