### PR TITLE
fix(user): profile link to user page

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-412

### CODE REVIEW

**Comment by huangp** [comment]
:+1: 
but you need to resolve merge conflicts

**Comment by aeng** [comment]
Previously from https://github.com/zanata/zanata-server/pull/922. Updated based on components in jsf.

**Comment by djansen-redhat** [comment]
Test failure: functional-test/src/main/java/org/zanata/page/projects/ProjectPeoplePage.java:getPeople() is still looking for an anchor object rather than a zanata:person-tile

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, waiting for Jenkins green light

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@djansen-redhat , happy for me to merge in?

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Pull request merged**
