### PR TITLE
Add tooltip to dashboard remove language icon

### PR DESCRIPTION
**Pull request by djansen-redhat**
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1209)

### CODE REVIEW

**Comment by aeng** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1209#-:-KKMwMNoRNTEhYi-CNRW:1417088721)*

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
screenshot from 2016-06-22 11-51-41

**Comment by anipeter** [comment]
Looks good :+1:

**Pull request merged**
