### PR TITLE
Fix the lt Plural-Forms expression

### PR DESCRIPTION
**Pull request by dashea**
Zanata is currently producing broken lt.po files.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1175)

### CODE REVIEW

**Comment by aeng** [comment]
@zanata-jenkins ok to test

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1175)*

**Comment by aeng** [comment]
Check with http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms and the regex is correct.

**Comment by seanf** [comment]
Looks like the error came from upstream originally: http://web.archive.org/web/20110314225121/http://translate.sourceforge.net/wiki/l10n/pluralforms#l

Fortunately, we don't have any other plural forms containing "or" or "and".

**Comment by djansen-redhat** [comment]
:white_check_mark: verified regex

**Pull request merged**
