### PR TITLE
docs(docker): add docker startup instructions

### PR DESCRIPTION
**Pull request by davidmason**
**Migrated to https://github.com/zanata/zanata-platform/pull/28**

This just adds an overview of the steps needed to get the dev environment running, and a section to guide users in making sure that the docker service is running.

---

This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1304)

### CODE REVIEW

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KSe0aIzxDnfccPmVPh1:b2o1myk) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
> ```Markdown
> 
> ```
> systemctl enable docker.service
> ```

`systemctl` is limited to Fedora user. 

Unless you want to write guide for all platform, I'm not sure about us having to maintain guide for installing docker.  User who wish to use docker should follow the official instructions: https://docs.docker.com/engine/installation/

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304)*

**Comment by davidmason** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KSe2z8qRDU8ELmHMn_o:b-arck0m) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> `systemctl` is limited to Fedora user. 
> 
> Unless you want to write guide for all platform, I'm not sure about us having to maintain guide for installing docker.  User who wish to use docker should follow the official instructions: https://docs.docker.com/engine/installation/
> 
</details>
Good point. Are most of the dev team using Fedora? If so maybe we could have a few quick reference things like this for the team, and a link or links to send people to instructions for other platforms.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304)*

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KSe45SQZThyY4b2tAsd:b-a7568s) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> Good point. Are most of the dev team using Fedora? If so maybe we could have a few quick reference things like this for the team, and a link or links to send people to instructions for other platforms.
</details>
Well, there's no way to tell if most dev is using Fedora and we certainly don't want to limit that. I would say for installation, refer them to the docker guide, but keep the steps from 1-4 you have in there.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304)*

**Comment by seanf** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KSe4l14-GPNZ-JKseLi:b-8fx2u7) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> Well, there's no way to tell if most dev is using Fedora and we certainly don't want to limit that. I would say for installation, refer them to the docker guide, but keep the steps from 1-4 you have in there.
</details>
:+1: 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304)*

**Comment by davidmason** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KSe5Z2wKo6ORWuLLtPJ:b92gcmw) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> :+1: 
</details>
I just mean the devs on our team. We're the main consumers of all our docs so we should at least make sure they work well for us.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304)*

**Comment by aeng** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KSe6vdQbR6mtUD4pzVq:bac630i) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
<details><summary><i>Previously, davidmason (David Mason) wrote…</i></summary>
> I just mean the devs on our team. We're the main consumers of all our docs so we should at least make sure they work well for us.
</details>
We are main consumer for most of our docs, but for readme.md which is public, I prefer to have it general enough for all consumer. If you want something only for our internal devs, then it should be in our internal wiki.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KSeD95URgXGMJavybSM:bcr1h6v) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> We are main consumer for most of our docs, but for readme.md which is public, I prefer to have it general enough for all consumer. If you want something only for our internal devs, then it should be in our internal wiki.
</details>
So, we keep these documented Fedora steps, add a link to https://docs.docker.com/engine/installation/ for non-Fedora users, and we're done. Right? That's all I was +1-ing.

If it's worth documenting, I see no problem with putting it in this file, although the public wiki might work too. 

You could argue that it's not worth documenting because it's not worth duplicating docker's documentation, but we can always delete it if it becomes a maintenance burden.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-:-KSeEfmwiScJFYZvLTnU:bnfp4nl)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KSeMGwCmhD9Z7awzlxU:bydl8yv) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> So, we keep these documented Fedora steps, add a link to https://docs.docker.com/engine/installation/ for non-Fedora users, and we're done. Right? That's all I was +1-ing.
> 
> If it's worth documenting, I see no problem with putting it in this file, although the public wiki might work too. 
> 
> You could argue that it's not worth documenting because it's not worth duplicating docker's documentation, but we can always delete it if it becomes a maintenance burden.
</details>
To me I'm still prefer it to refer to the guide given that we don't need to worry about maintaining it. 
But I'm fine with just Fedora steps if that's what you guys prefer.  

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304)*

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[docker/README.md, line 64 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1304#-KSe0aIzxDnfccPmVPh0:-KUQiaVAoeV8W_uTnwIt:b73oqqm) ([raw file](https://github.com/zanata/zanata-server/blob/18aa215a317a4f90eec026912c1987d3b3ce26ca/docker/README.md#L64)):*
<details><summary><i>Previously, aeng (Alex Eng) wrote…</i></summary>
> To me I'm still prefer it to refer to the guide given that we don't need to worry about maintaining it. 
> But I'm fine with just Fedora steps if that's what you guys prefer.  
</details>
To be fair, the systems that use **systemd** should have the command systemctl. That include RHEL7, and Ubuntu newer that 16.04.
It may not work for MacOS and Windows, of course.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1304)*

**Comment by davidmason** [comment]
Closing since this has been migrated to zanata-platform: https://github.com/zanata/zanata-platform/pull/28

**Pull request closed without merging**
