### PR TITLE
Redirect user to dashboard after openid login

### PR DESCRIPTION
**Pull request by aeng**
https://bugzilla.redhat.com/show_bug.cgi?id=1098878

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/837" target="_blank">ReviewNinja

**Comment by huangp** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by aeng** [comment]
Merge into integration/master. https://github.com/zanata/zanata-server/commit/39fd57d752b42a1b4e264128c34c89a8aa7886dc

**Pull request closed without merging**
