### PR TITLE
feat(glossary): page size selection

### PR DESCRIPTION
**Pull request by aeng**
https://zanata.atlassian.net/browse/ZNTA-1168

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1227)

### CODE REVIEW

**Comment by huangp** [comment]
:lgtm: +Reviewed +(On QA) 

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1227#-:-KLV3BRM33Irp1z685Ei:561125758)*

**Comment by anipeter** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
* Here is how the glossary page looks when no entries available in glossary:
glossary page - before adding glossary file
* Successfully uploaded 2041 entries for French language and here is how it looks:
glossary page - after adding glossary file
* Page size selections 20, 50, 100, 300 & 500 displayed well.

Few observations:
* The options on the glossary page looks bit cluttered & need to be more user-friendly
* No tool tips for any of the items displayed on the page

**Comment by anipeter** [comment]
@zanata-jenkins retest this please

**Comment by anipeter** [comment]
* The page selection works fine.
* Confirmed all the navigation icons have required tool tips like First Page, Previous Page, Next Page, Last Page and Total glossary terms. Sample screenshot attached.
tootl tips for page selection - glossary

**Pull request merged**
