### PR TITLE
Docker script

### PR DESCRIPTION
**Pull request by huangp**
*Customize docker dev run script*

Provides support for offsetting the container listening ports. Also provide support to deploy an exploded war. One drawback will be it now requires the host machine to have mysql-connector-java package installed.

## Reviewer tasks

The following is based on the
[Zanata Development Guidelines](https://github.com/zanata/zanata-server/wiki/Development-Guidelines).
As a reviewer, you should check the guidelines regularly for updates, and just
to refresh your memory.

The reviewer can use this list for reference to make sure
they have considered all the important points.

Use the checkboxes or not, whatever works best for you.

 - Code quality
   - [ ] Code passes style check (checkstyle/eslint)
   - [ ] Code is clear and concise
   - [ ] UI code is internationalised
   - [ ] Code has adequate comments where appropriate
   - Code is in an appropriate place
     - [ ] Classes are in appropriate packages
     - [ ] Code fits with class's responsibilities (SRP)
   - [ ] Configuration files are documented enough
   - If code is removed
     - [ ] No remaining code references the removed code
       - [ ] No orphaned rewrite rules
       - [ ] No orphaned config settings
     - [ ] No remaining comments refer to the removed code
     - [ ] Unused imports and libraries are removed
 - Testing
   - [ ] New code has tests
   - [ ] Changed code has tests
   - [ ] All tests pass
   - [ ] Test coverage stable or increased
 - Documentation
   - [ ] New features are documented
   - [ ] Docs removed for deleted features
   - [ ] Docs updated for all changed features
   - [ ] Developer/sysadmin docs updated if appropriate
 - If there are new dependencies
   - [ ] Does each new dependency pass all the
         [Considerations for new dependencies](https://github.com/zanata/zanata-server/wiki/Development-Guidelines#new-technologies-and-dependencies)?

----
*This template can be updated in .github/PULL_REQUEST_TEMPLATE.md*

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1311)

### CODE REVIEW

**Comment by seanf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/Dockerfile, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHO2Ry7MQVxqDcTTww:-KTHO2Ry7MQVxqDcTTwx:b4csypy) ([raw file](https://github.com/zanata/zanata-server/blob/6a1b18bfa8ce7fd840f578ed538eb2c9424eab63/docker/Dockerfile#L6)):*
> ```Dockerfile
> RUN yum -y install mysql-connector-java wget && yum clean all
> 
> RUN ln -sf /usr/share/java/mysql-connector-java.jar /opt/jboss/wildfly/standalone/deployments/mysql-connector-java.jar
> ```

Why change this? It doesn't seem incompatible with your other goals for this PR.

---

*[docker/README.md, line 75 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHOICbIZ5oBreM5dax:-KTHOICbIZ5oBreM5day:b-710jlj) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/README.md#L75)):*
> ```Markdown
> This script will start another docker container with the Zanata server, and will log the server output. Unlike the database container, the server container will run in daemon mode.
> 
> You can offset the standard ports if you want to avoid port conflicts on your host machine. e.g. you have other container/instance running and listening to port 8080. Give option `-p 100` will offset standard JBoss port by 100. e.g. server will be running on http://localhost:8180/ and debug port will be 8887.
> ```

This is a good change, but wouldn't it have been easier to change the default ports for Zanata Sync? The default ports for Zanata server have seniority, you know!

---

*[docker/rundev.sh, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHOtDEyIt7PJDgryJ9:-KTHOtDFAitzNUuGI-_s:br1235t) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L21)):*
> ```Shell
> then
>     mkdir -p ${ZANATA_DEPLOYMENTS_DIR} && chcon -Rt svirt_sandbox_file_t ${ZANATA_DEPLOYMENTS_DIR}
>     cp ${ZANATA_WAR} ${ZANATA_DEPLOYMENTS_DIR}/ROOT.war
> ```

Do we really need to be copying war files around? That's going to slow things down. Why can't we continue to map in the war from target/*.war (when using file deployment)? (Or from somewhere else when using exploded deployment.)

---

*[docker/rundev.sh, line 36 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHPQP8-By2cb_vTgaL:-KTHPQP8-By2cb_vTgaM:b-hwisae) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L36)):*
> ```Shell
>     if [ -f "/usr/share/java/mysql-connector-java.jar" ]
>     then
>         ln -sf /usr/share/java/mysql-connector-java.jar ${ZANATA_DEPLOYMENTS_DIR}/mysql-connector-java.jar
> ```

This seems very Fedora specific. Kind of defeats the point of using Docker.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1311)*

**Comment by huangp** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/Dockerfile, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHO2Ry7MQVxqDcTTww:-KTHSzgJoTVzT0grCO4j:bakcjcv) ([raw file](https://github.com/zanata/zanata-server/blob/6a1b18bfa8ce7fd840f578ed538eb2c9424eab63/docker/Dockerfile#L6)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Why change this? It doesn't seem incompatible with your other goals for this PR.
</details>
Because if we map the deployments/ folder, this will get overridden. So it's useless

---

*[docker/README.md, line 75 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHOICbIZ5oBreM5dax:-KTHTMU54bNUZLHjky1a:b-a83h8g) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/README.md#L75)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> This is a good change, but wouldn't it have been easier to change the default ports for Zanata Sync? The default ports for Zanata server have seniority, you know!
</details>
It's harder... I tried that first. But since Zanata Sync has two wars and they need to talk to each other. Inside docker, it's all still 8080 but from the host, it become something else. Which means, I can't construct a host url from a servlet request (as it will be the external port). 

---

*[docker/rundev.sh, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHOtDEyIt7PJDgryJ9:-KTHUgqFEn7JwrrXBY4J:bryx3v6) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L21)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Do we really need to be copying war files around? That's going to slow things down. Why can't we continue to map in the war from target/*.war (when using file deployment)? (Or from somewhere else when using exploded deployment.)
</details>
I find it limited when we only map the war file to docker. It means, if I want to deploy a different war (give it a different context path), I won't be able to do that. This way, I can put two wars side by side without modifying existing docker build file or setup. Just drop in the war. That said, this is not a change I definitely need (to support linking with Zanata Sync). 

---

*[docker/rundev.sh, line 36 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHPQP8-By2cb_vTgaL:-KTHVVzrHeBHn4R_uc74:b-9rrjdq) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L36)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> This seems very Fedora specific. Kind of defeats the point of using Docker.
</details>
It is. A better way will be to create the docker image with mysql as a jboss module (I've done that in Zanata Sync). This way we can skip this step. But only if we are all happy to map the `deployments/` folder instead of just the war file.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1311)*

**Comment by seanf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/Dockerfile, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHO2Ry7MQVxqDcTTww:-KTHbrccEzbKv6qSd-HH:bdeppeq) ([raw file](https://github.com/zanata/zanata-server/blob/6a1b18bfa8ce7fd840f578ed538eb2c9424eab63/docker/Dockerfile#L6)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> Because if we map the deployments/ folder, this will get overridden. So it's useless
</details>
Do you have to map the whole deployments folder?

There's also the option of jboss modules for jdbc drivers.

And I believe it's possible to scan multiple deployment folders.

---

*[docker/README.md, line 75 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHOICbIZ5oBreM5dax:-KTHcILYAa8LyINOiU9i:bfnvcvg) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/README.md#L75)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> It's harder... I tried that first. But since Zanata Sync has two wars and they need to talk to each other. Inside docker, it's all still 8080 but from the host, it become something else. Which means, I can't construct a host url from a servlet request (as it will be the external port). 
</details>
But only Zanata Sync's front end needs to be exposed on the host. You can still link to ports on the Docker network, as long as you use the internal IP.

---

*[docker/rundev.sh, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHOtDEyIt7PJDgryJ9:-KTHdCVQk9NE-w4bSaEz:b81c3ew) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L21)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> I find it limited when we only map the war file to docker. It means, if I want to deploy a different war (give it a different context path), I won't be able to do that. This way, I can put two wars side by side without modifying existing docker build file or setup. Just drop in the war. That said, this is not a change I definitely need (to support linking with Zanata Sync). 
</details>
It does seem like this should be two PRs. Adding the option to control the port numbers is fine, and should go through quickly. It's all the changes to support exploded deployment that concern me.

---

*[docker/rundev.sh, line 36 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHPQP8-By2cb_vTgaL:-KTHct-Nt_fDNCsiAyGr:bdy9ls4) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L36)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> It is. A better way will be to create the docker image with mysql as a jboss module (I've done that in Zanata Sync). This way we can skip this step. But only if we are all happy to map the `deployments/` folder instead of just the war file.
</details>
Huh? You don't have to map the whole deployments directory to use a jdbc module.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1311)*

**Comment by huangp** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[docker/Dockerfile, line 6 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHO2Ry7MQVxqDcTTww:-KTHo3K5T76UhUXUkQQ7:b69mkuq) ([raw file](https://github.com/zanata/zanata-server/blob/6a1b18bfa8ce7fd840f578ed538eb2c9424eab63/docker/Dockerfile#L6)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Do you have to map the whole deployments folder?
> 
> There's also the option of jboss modules for jdbc drivers.
> 
> And I believe it's possible to scan multiple deployment folders.
</details>
This is the easiest option. But I will create a separate PR for this.

---

*[docker/README.md, line 75 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHOICbIZ5oBreM5dax:-KTHoBnrD0m4FWC1l4T2:b-3kbaus) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/README.md#L75)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> But only Zanata Sync's front end needs to be exposed on the host. You can still link to ports on the Docker network, as long as you use the internal IP.
</details>
The two war in Zanata Sync live in one docker container. So it's not the issue of internal IP or ports. 
The main reason I choose to change Zanata script is: Zanata already have admin configuration page to set server URL (otherwise fallback to construct one from HTTP request, which will be wrong if you have proxy or having docker port mapping using different port). Zanata Sync doesn't have admin configuration page yet. So it makes it harder to work properly with different port mapping. 

---

*[docker/rundev.sh, line 21 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHOtDEyIt7PJDgryJ9:-KTHpEtb-Ur2937yIbtb:b-2v72as) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L21)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> It does seem like this should be two PRs. Adding the option to control the port numbers is fine, and should go through quickly. It's all the changes to support exploded deployment that concern me.
</details>
Yes will create two separate PRs

---

*[docker/rundev.sh, line 36 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHPQP8-By2cb_vTgaL:-KTHpJFaVpBcuMTdr9Q0:b2vzdq8) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L36)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Huh? You don't have to map the whole deployments directory to use a jdbc module.
</details>
What I meant was, I will use jdbc module so that I don't need to put the jdbc jar or symlink into deployments folder. What's wrong with mapping the deployments folder? It's more flexible than mapping a single war file. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1311)*

**Comment by seanf** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[docker/rundev.sh, line 36 at r1](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-KTHPQP8-By2cb_vTgaL:-KTHtk-WcfqPcyPwI-7H:b-6bwuvp) ([raw file](https://github.com/zanata/zanata-server/blob/997e71181eb4d4299d10b58859387ad7da51da34/docker/rundev.sh#L36)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> What I meant was, I will use jdbc module so that I don't need to put the jdbc jar or symlink into deployments folder. What's wrong with mapping the deployments folder? It's more flexible than mapping a single war file. 
</details>
By itself, nothing. I just don't want anything to make rundev.sh slower for the common case (.war files), or less portable. (I would also prefer to avoid making it harder to maintain than it needs to be.)

Perhaps you could avoid the extra copying by using symlinks.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1311)*

**Comment by huangp** [comment]
now just one commit for the port offset. Can you please review again?

---

Review status: 0 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-:-KTMVZlKogAVhPLnpvKl:b-ws614a)*

**Comment by seanf** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1311#-:-KTNPibITSbfxlz878Xo:bnfp4nl)*

**Pull request merged**
