### PR TITLE
Upgrade to commonmark.js 0.20

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/878" target="_blank">ReviewNinja

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by carlosmunoz** [comment]
:+1:

**Comment by seanf** [comment]
@djansen-redhat Happy with the auto tests?

**Comment by djansen-redhat** [comment]
@seanf This now conflicts with 877, I think?

**Comment by seanf** [comment]
@djansen-redhat git and github did consider it a conflict, but just now when I rebased this branch, kdiff3 resolved it automatically.  It's building again now.

**Pull request merged**
