### PR TITLE
add plural form for me-ME

### PR DESCRIPTION
**Pull request by huangp**
Plural information from the user:
"Plural-Forms: nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;\n"

### CODE REVIEW

**Comment by seanf** [comment]
We should make sure the plural forms for `me` are correct, and get it added to our upstream source for plural info: http://docs.translatehouse.org/projects/localization-guide/en/latest/l10n/pluralforms.html?id=l10n/pluralforms

**Comment by djansen-redhat** [comment]
@huangp Why does your comment differ to the code i.e. (n%100=20) vs (n%100<10 || n%100>=20)?

**Comment by djansen-redhat** [comment]
I take it the forms are identical to Serbian/Russian etc?

**Comment by huangp** [comment]
github removed the greater than or less than sign in comment. The code is correct. 

Patrick Huang 
Senior Software Engineer 
Engineering - Internationalisation 
Red Hat 

----- Original Message -----

**Comment by huangp** [comment]
I don't know how to verify it's correct. It's from the user in his po file. I have put in a PR to update the page https://github.com/translate/l10n-guide/pull/26

**Comment by seanf** [comment]
Which user?  The Translate Toolkit people will probably ask.

**Comment by huangp** [comment]
I don't want to disclose that user's email here. But it's from Zanata user "Filip" with id "fvisic" on translate.zanata.org. 

Patrick Huang 
Senior Software Engineer 
Engineering - Internationalisation 
Red Hat 

----- Original Message -----

**Pull request merged**
