### PR TITLE
Cache downloaded wildfly modules to ~/Downloads

### PR DESCRIPTION
**Pull request by seanf**
If Sourceforge is in "Disaster Recovery mode", you will need to download the module zips to `~/Downloads` using your browser, from here: http://sourceforge.net/projects/zanata/files/wildfly/

### CODE REVIEW

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested

**Comment by seanf** [comment]
@djansen-redhat Could you please take another look?

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
This is the correct commit: https://github.com/zanata/zanata-server/commit/2f8549ec2c7365f9911b97a11370251a5e81a93f

**Comment by djansen-redhat** [comment]
This appears to work fine for me, via blocking sourceforge.net
:white_check_mark: Tested

**Pull request merged**
