### PR TITLE
fix(ZNTA-1084): NoSuchElementException in event handler

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1084

### CODE REVIEW

**Comment by seanf** [comment]
@djansen-redhat This should fix the stack-trace you saw when testing the PO upload for a file project.

**Comment by aeng** [comment]
:+1:

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested. I think this needs to be rebased on top of @definite's fix for the language breakage

**Comment by aeng** [comment]
I've backport the fix to release. https://github.com/zanata/zanata-server/pull/1166

**Comment by seanf** [comment]
@zanata-jenkins retest this please

**Pull request merged**
