### PR TITLE
Increase timeout on server startup in all standalone.xml files.

### PR DESCRIPTION
**Pull request by davidmason**
Changes the timeout to 1000 seconds (16min 40s) from default 300s (5min)
to prevent timeout when liquibase changesets take longer than 5 minutes
to run.

### CODE REVIEW

**Comment by seanf** [comment]
:+1:

**Comment by djansen-redhat** [comment]
:see_no_evil: I've already tested that this works, and is a configuration change.

**Comment by djansen-redhat** [comment]
Due to #734 this will need to be in release branch also

**Comment by carlosmunoz** [comment]
:memo: Lets add a note about this in the docs.
It isn't a mandatory thing, so we should mention what it's for and how to set it up.

**Comment by davidmason** [comment]
@carlosmunoz it is mentioned in the release notes, but I agree it would be worth a mention in the server config documentation. I will add that in a separate branch since this change needs to be applied to release.

**Comment by davidmason** [comment]
Rebased onto master, see https://github.com/zanata/zanata-server/pull/739

**Pull request closed without merging**
