### PR TITLE
fix(docker): build with mac os and staff_selinux

### PR DESCRIPTION
**Pull request by definite**
Fix the docker build for [staff_selinux](http://linux.die.net/man/8/staff_selinux) and mac os

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1230)

### CODE REVIEW

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/rundev.sh, line 19 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1230#-KLnfdXqha3_Sz6QoK4d:-KLnmsA94vV52ijv_tKk:608688714) ([raw file](https://github.com/zanata/zanata-server/blob/a35e08179a8cd0828882bb42a7d944489f54c70c/docker/rundev.sh#L19)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> I think the intention was to run chcon only when the directory  was actually created, but I guess that wasn't true with `-p`.
> 
> Perhaps we ought to check for the existence of $ZANATA_DIR before mkdir and chcon.
</details>
`mkdir -p` should create the dir when missing, and ignore if the target is already created.
If it does encounter the permission deny, the script should be fail because `bash -e`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1230)*

**Comment by definite** [comment]
Reviewed 2 of 2 files at r1, 1 of 3 files at r2.
Review status: 1 of 3 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1230)*

**Comment by seanf** [comment]
Reviewed 2 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/function.sh, line 33 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-server/1230#-KLoC0oXcWYk7alO8T16:-KLoC0oXcWYk7alO8T17:65423878) ([raw file](https://github.com/zanata/zanata-server/blob/c217788f715efe3e8bdfd22e6452ea554cb6a9fd/docker/function.sh#L33)):*
> ```Shell
> 
> function file_setup_for_docker(){
>     local f="$1"
> ```

Can you have these two functions do nothing (ie no chcon) if the file/directory already exists?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1230)*

**Comment by definite** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[docker/function.sh, line 33 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-server/1230#-KLoC0oXcWYk7alO8T16:-KLoFhyeM4V9hBry354U:1655881504) ([raw file](https://github.com/zanata/zanata-server/blob/c217788f715efe3e8bdfd22e6452ea554cb6a9fd/docker/function.sh#L33)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> Can you have these two functions do nothing (ie no chcon) if the file/directory already exists?
</details>
It is useful when the file/directory exists, but incorrect permission.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1230)*

**Comment by definite** [comment]
@zanata-jenkins retest this please

**Comment by definite** [comment]
This PR is no longer relevant, as we are now in flavour of data volume.

**Pull request closed without merging**
