### PR TITLE
Feat(ZNTA-786) : Post-CDI cleanup (ServiceLocator)

### PR DESCRIPTION
**Pull request by broccolinisoup**
I worked on a few classes to understand CDI for a kick start.
Here are the changes for these classes;
  - Replace ServiceLocator with typesafe injection
  - Remove unnecessary @Named from beans

Any ideas, solutions, suggestions are very welcome.

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1217)

### CODE REVIEW

**Comment by seanf** [comment]
So far, so good (as long as the tests still pass).

---

Reviewed 18 of 18 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1217#-:-KKv37MZpk5ssWH8vnu9:294270295)*

**Comment by seanf** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[zanata-war/src/main/java/org/zanata/ui/AbstractAutocomplete.java, line 42 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-server/1217#-KKvsxzaJ8COurxn5aIh:-KKvsxzaJ8COurxn5aIi:-203339066) ([raw file](https://github.com/zanata/zanata-server/blob/f16593b0d581352dc9a24785735855a25f7c2a99/zanata-war/src/main/java/org/zanata/ui/AbstractAutocomplete.java#L42)):*
> ```Java
> 
>     @Inject
>     protected Messages msgs;
> ```

In Java, default scope (also known as package scope; ie visible to any code in the same package) is actually wider than `protected` scope (which is visible to code in the same package, and in subclasses of this class). 

I don't think you need to widen the scope here. Would narrowing to `private` scope work?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1217)*

**Comment by seanf** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[zanata-war/src/main/java/org/zanata/ui/AbstractAutocomplete.java, line 42 \[r2\]](https://reviewable.io:443/reviews/zanata/zanata-server/1217#-KKvsxzaJ8COurxn5aIh:-KKvzJLJFkCAXT63oJvX:731712612) ([raw file](https://github.com/zanata/zanata-server/blob/f16593b0d581352dc9a24785735855a25f7c2a99/zanata-war/src/main/java/org/zanata/ui/AbstractAutocomplete.java#L42)):*
<details><summary><i>Previously, seanf (Sean Flanigan) wrote…</i></summary>
> In Java, default scope (also known as package scope; ie visible to any code in the same package) is actually wider than `protected` scope (which is visible to code in the same package, and in subclasses of this class). 
> 
> I don't think you need to widen the scope here. Would narrowing to `private` scope work?
</details>
You're quite right; I've got that the wrong way around: `protected` scope is wider than default scope..

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1217)*

**Comment by broccolinisoup** [comment]
@zanata-jenkins retest this please

**Comment by broccolinisoup** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@broccolinisoup I got some of the failing tests working. See the branch ZNTA-786 on the main repo: https://github.com/zanata/zanata-server/commits/ZNTA-786

**Comment by broccolinisoup** [comment]
@carlosmunoz More broken functional tests :/ We should find another solution.

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@broccolinisoup The rebuild succeeded! Looks like the previous build only failed because of a socket problem (it's to do with SMTP, but we haven't been able to track down the cause yet).

**Comment by broccolinisoup** [comment]
@seanf  Wow! Great news! So what should we do now for this PR? Is anyone continue to this? If not, I am willing to continue.

**Comment by seanf** [comment]
@broccolinisoup  I suggest we review what's here and try to get it merged soon, before the code changes too much (which will lead to merge conflicts). 

If you want to tackle more of the same (ie more CDI cleanup), I would suggest starting another pull request. (I think experimenting with Immutables will be more interesting though.)

**Comment by broccolinisoup** [comment]
@seanf Yes, I agree with you. I just started and I am happy with researching Immutables. Just in case, I asked if you need somebody to continue. Then, I am just waiting for your reviews for this PR.

**Comment by seanf** [comment]
LGTM, but  I'd like @carlosmunoz to review it too, because some of the code is mine, and I shouldn't be reviewing my own code.

---

Reviewed 17 of 24 files at r3, 1 of 1 files at r4, 3 of 6 files at r5, 8 of 8 files at r7, 6 of 6 files at r8.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1217#-:-KMw5VIbtQQPLQLiq5oR:989845400)*

**Comment by carlosmunoz** [comment]
:lgtm: 

---

Reviewed 7 of 18 files at r1, 2 of 5 files at r2, 17 of 24 files at r3, 1 of 1 files at r4, 3 of 6 files at r5, 8 of 8 files at r7, 6 of 6 files at r8.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1217#-:-KMwHUNZj1QavSROYpTR:980077423)*

**Comment by djansen-redhat** [comment]
:white_check_mark: I did some cursory testing on this, I feel the functional tests have done most of the necessary effort.

**Comment by seanf** [comment]
Merged! Thanks @broccolinisoup

**Comment by broccolinisoup** [comment]
Thanks for all your help. @seanf

**Pull request merged**
