### PR TITLE
Increase other password lengths to 1024

### PR DESCRIPTION
**Pull request by pokemmo-kyu**
Fix missing password length changes from PR #989

### CODE REVIEW

**Comment by aeng** [comment]
:+1:

**Comment by aeng** [comment]
Actually, you might want to increase the maxlength too in /layout/dashboard/settings.xtml

`<h:inputSecret id="oldPassword"` and <h:inputSecret id="newPassword"

**Comment by aeng** [comment]
:+1:

**Comment by aeng** [comment]
@zanata-jenkins ok to test.

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by djansen-redhat** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
:white_check_mark: Tested, looks good.
Thanks for the contribution!

**Comment by djansen-redhat** [comment]
Waiting for Jenkins' green light

**Comment by djansen-redhat** [comment]
ChangePasswordTest.java needs to be updated to reflect the change, in function changePasswordAreOfRequiredLength
```
Error Message

Expecting:
 <["size must be between 6 and 1024"]>
to contain:
 <["size must be between 6 and 20"]>
but could not find:
 <["size must be between 6 and 20"]>

	at org.zanata.feature.account.ChangePasswordTest.changePasswordAreOfRequiredLength(ChangePasswordTest.java:126)
```

**Comment by pokemmo-kyu** [comment]
Is org.jboss.seam.util.RandomStringUtils or org.apache.commons.lang.RandomStringUtils preferred here? Both are in use

**Comment by aeng** [comment]
org.apache.commons.lang.RandomStringUtils

**Comment by pokemmo-kyu** [comment]
Anyone want to take this before rc4? I don't have a proper build environment for zanata set up so I can't debug these functional tests efficiently

**Comment by aeng** [comment]
I'm happy to take it, but need commit access to `pokemmo-kyu:fix-password-lengths`

**Comment by aeng** [comment]
@zanata-jenkins retest this please

**Comment by djansen-redhat** [comment]
@aeng Removed?

**Comment by aeng** [comment]
Because we limit length of input in html. The test was to input text with
length more than limited in the bean.

Alex Eng

**Comment by djansen-redhat** [comment]
Ah, gotcha.

**Pull request merged**
