### PR TITLE
Use embedded JAX-RS, not the container's

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="http://app.review.ninja/zanata/zanata-server/pull/847" target="_blank">ReviewNinja

**Comment by seanf** [comment]
@djansen-redhat anything you want to do?

**Comment by seanf** [comment]
@djansen-redhat This fixes `TranslationResourceRestITCase` which has been failing with "Caused by: java.lang.AbstractMethodError: javax.ws.rs.core.Response.getStatusInfo()" on WildFly.

**Comment by djansen-redhat** [comment]
@seanf :see_no_evil:

**Pull request merged**
