### PR TITLE
fix(login redirect): preserves hash location after login

### PR DESCRIPTION
**Pull request by aeng**
fix(profile): redirect to login is user not logged in

https://zanata.atlassian.net/browse/ZNTA-1051

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1228)

### CODE REVIEW

**Comment by huangp** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[frontend/src/main/web/src/containers/UserProfile/index.jsx, line 54 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1228#-KLZVfhpT6uk5Upts_Xx:-KLZVfhpT6uk5Upts_Xy:-939252871) ([raw file](https://github.com/zanata/zanata-server/blob/052863d0cd6331de761765d8d2b63c81f64adb0a/frontend/src/main/web/src/containers/UserProfile/index.jsx#L54)):*
> ```JSX
>   componentDidMount () {
>     const paramUsername = this.props.params.username
>     const username = (!paramUsername || paramUsername === 'undefined')
> ```

you have quote around undefined, will the value be a string 'undefined'?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1228)*

**Comment by aeng** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[frontend/src/main/web/src/containers/UserProfile/index.jsx, line 54 \[r1\]](https://reviewable.io:443/reviews/zanata/zanata-server/1228#-KLZVfhpT6uk5Upts_Xx:-KLZXjdlDsrijKZ5U634:316114137) ([raw file](https://github.com/zanata/zanata-server/blob/052863d0cd6331de761765d8d2b63c81f64adb0a/frontend/src/main/web/src/containers/UserProfile/index.jsx#L54)):*
<details><summary><i>Previously, huangp (Patrick Huang) wrote…</i></summary>
> you have quote around undefined, will the value be a string 'undefined'?
</details>
Yes. This is because react-router convert `undefined` to string. The actual `undefined` is in the first condition- `!paramUsername`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1228)*

**Comment by huangp** [comment]
:lgtm: -(Awaiting review)  +Reviewed +(On QA) 

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1228#-:-KLZfPMJdEOJPRntV7Jx:-1425745978)*

**Comment by djansen-redhat** [comment]
:white_check_mark: tested - but there are test failures.

**Comment by definite** [comment]
@zanata-jenkins  retest this please

**Comment by definite** [comment]
:+1:

**Pull request merged**
