### PR TITLE
test: fix NPEs where ResourceUtils is used

### PR DESCRIPTION
**Pull request by seanf**

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
Changes to ResourceUtils.getNumPlurals have been moved to https://github.com/zanata/zanata-server/pull/958

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by huangp** [comment]
:+1: 
The tests failed in build are the ones that I mentioned in retrospective. I made it to use chain rule in https://github.com/zanata/zanata-server/pull/928

**Pull request merged**
