### PR TITLE
fix(ZNTA-1386): update Piwik code (async), add image tracker

### PR DESCRIPTION
**Pull request by seanf**
https://zanata.atlassian.net/browse/ZNTA-1386

---
This change is [Reviewable](https://reviewable.io/reviews/zanata/zanata-server/1291)

### CODE REVIEW

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
@aeng Could you review this please?

**Comment by aeng** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1291)*

**Comment by aeng** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/zanata/zanata-server/1291#-:-KSBCqHv6LwRmX3ued0b:bnfp4nl)*

**Pull request merged**
