### PR TITLE
BACKPORT feat(logging): include MDC values and time in emails

### PR DESCRIPTION
**Pull request by seanf**
(cherry picked from commit 4a4793da7b8603c331e161fdf0b7ae0661e23897) https://github.com/zanata/zanata-server/pull/946

### CODE REVIEW

**Comment by djansen-redhat** [comment]
Blocked by dependency failure: Found Banned Dependency: system:jdk-tools:jar:jdk

**Comment by seanf** [comment]
> Blocked by dependency failure: Found Banned Dependency: system:jdk-tools:jar:jdk

Thanks @djansen-redhat, but argh!  I ran into this earlier, but I can't remember how I fixed it.  I think I added an exception to Enforcer's config, but where?

**Comment by seanf** [comment]
It turns out enforcer stopped working in `master` when we upgraded zanata-parent to 25-SNAPSHOT (apparently due to https://github.com/zanata/zanata-parent/commit/9592b8dce1cc2515f44971b905ac56c1c7fb75d3 which removed oss-parent and some inherited enforcer config).

I think this enforcer failure didn't show up in our other `release` builds because they don't use `-Dappserver=jbosseap6`, a setting which brings in `system:jdk-tools:jar`.

I have created https://github.com/zanata/zanata-parent/pull/44 to bring back enforcer in `master`, with an exception for tools.jar.  And https://github.com/zanata/zanata-server/commit/ce7cadfc1ae3f1075068977b03dfb8cff686fb72 to add the tools.jar exception in `release` (with parent 24).

**Comment by seanf** [comment]
@carlosmunoz Are you happy for this to go into `release`?

**Comment by seanf** [comment]
@zanata-jenkins test this please

**Comment by seanf** [comment]
Sorry, I had to swap the commits around so that the enforcer fix could be used in #953.  No other changes, except to rebase on top of `release`.

**Pull request merged**
